/**
 * Catalog F2 `target-browser-driver` — Section 25 BROW.
 *
 * Codegen for the computer-use target. Emits a single `agent.ts` that:
 *
 *   1. Constructs the chromium driver (Playwright-backed).
 *   2. Optionally navigates to `driver.startUrl` before agent input.
 *   3. Registers Screenshot + Click + Type + Key + Scroll + FindElement
 *      as runtime tools — destructive ones at the `flag` rule layer
 *      ONLY when the spec carries explicit `alwaysAllow` rules for
 *      them (the smoke's permission-floor probe relies on this — same
 *      spec without `alwaysAllow` rules → denial cites destructive
 *      flag).
 *   4. Reads a single user prompt from `--prompt <text>` or stdin and
 *      runs `runChatLoop` in single-turn mode. The interpreter path
 *      (`crewhaus run`) mirrors this same wiring — keep them in sync.
 *   5. On exit, calls driver.disconnect() so chromium doesn't leak.
 */
import { CrewhausError } from "@crewhaus/errors";
import { escapeJsonString } from "@crewhaus/infra-utils";
import type { Bundle, IrBrowserV0 } from "@crewhaus/ir";

export class TargetEmitError extends CrewhausError {
  override readonly name = "TargetEmitError";
  constructor(message: string, cause?: unknown) {
    super("compiler", message, cause);
  }
}

export function emitBrowserDriver(ir: IrBrowserV0): Bundle {
  return { files: [{ path: "agent.ts", content: renderAgent(ir) }] };
}

function renderAgent(ir: IrBrowserV0): string {
  const startUrl = ir.driver.startUrl;
  const hasRules = ir.permissions.rules.length > 0;
  const permImport = hasRules
    ? `import { BUILTIN_DEFAULT_RULES } from "@crewhaus/permission-engine";\n`
    : "";
  const permField = renderPermissionsField(ir);
  return `#!/usr/bin/env bun
// Generated by crewhaus. DO NOT EDIT.
// Source spec: ${ir.name} (target: browser, ir version: ${ir.version})
import { createDriver } from "@crewhaus/computer-use-driver";
import { createScreenshotTool } from "@crewhaus/tool-screen-capture";
import { createAllMouseKeyboardTools } from "@crewhaus/tool-mouse-keyboard";
import { createFindElementTool } from "@crewhaus/tool-vision-grounding";
import { runChatLoop } from "@crewhaus/runtime-core";
import { createRunContext } from "@crewhaus/run-context";
import { defaultCatalog } from "@crewhaus/tool-catalog";
${permImport}
const SPEC_NAME = ${escapeJsonString(ir.name)};
const SPEC_MODEL = ${escapeJsonString(ir.agent.model)};
const SPEC_INSTRUCTIONS = ${escapeJsonString(ir.agent.instructions)};
const SPEC_GROUNDING_MODEL = ${escapeJsonString(ir.groundingModel)};
const SPEC_BACKEND: "host" | "chromium" | "remote" = ${escapeJsonString(ir.driver.backend)};
const SPEC_VIEWPORT = { width: ${ir.driver.viewport.width}, height: ${ir.driver.viewport.height} };
const SPEC_START_URL = ${startUrl !== undefined ? escapeJsonString(startUrl) : "undefined"};

function emit(event: Record<string, unknown>): void {
  process.stdout.write(\`\${JSON.stringify(event)}\\n\`);
}

function parseArgs(): { prompt: string | undefined } {
  const args = process.argv.slice(2);
  const i = args.indexOf("--prompt");
  if (i !== -1 && i + 1 < args.length) return { prompt: String(args[i + 1]) };
  return { prompt: undefined };
}

async function readStdin(): Promise<string> {
  if (process.stdin.isTTY) return "";
  const chunks: Buffer[] = [];
  for await (const chunk of process.stdin) chunks.push(chunk as Buffer);
  return Buffer.concat(chunks).toString("utf-8").trim();
}

async function main(): Promise<void> {
  const { prompt: argPrompt } = parseArgs();
  const stdinPrompt = argPrompt ?? (await readStdin());
  if (stdinPrompt.length === 0) {
    process.stderr.write("[browser-driver] no prompt (pass --prompt <text> or pipe stdin)\\n");
    process.exit(2);
  }

  emit({ kind: "browser_start", backend: SPEC_BACKEND });
  const driver = createDriver({ backend: SPEC_BACKEND, viewport: SPEC_VIEWPORT });
  await driver.connect();
  if (SPEC_START_URL !== undefined) {
    await driver.goto(SPEC_START_URL);
    emit({ kind: "navigated", url: SPEC_START_URL });
  }

  const screenshotTool = createScreenshotTool({ driver });
  const mk = createAllMouseKeyboardTools({ driver });
  const findElement = createFindElementTool({ driver, model: SPEC_GROUNDING_MODEL });
  const tools = [screenshotTool, mk.click, mk.type, mk.key, mk.scroll, findElement, ...defaultCatalog.list()];

  const runContext = createRunContext();
  let finalText = "";
  try {
    finalText = await runChatLoop({
      model: SPEC_MODEL,
      instructions: SPEC_INSTRUCTIONS,
      runContext,
      sessionName: SPEC_NAME,
      sessionTarget: "browser",
      singleTurn: true,
      seedMessages: [{ role: "user", content: stdinPrompt }],
      tools,
      installSigintHandler: false,
      maxTokens: 4096,${permField}
    });
  } finally {
    await driver.disconnect();
  }
  emit({ kind: "browser_done", finalText });
}

main().catch((err) => {
  process.stderr.write(\`[browser-driver] fatal: \${(err as Error).message}\\n\`);
  process.exit(1);
});
`;
}

function renderPermissionsField(ir: IrBrowserV0): string {
  const { mode, rules } = ir.permissions;
  if (mode === undefined && rules.length === 0) return "";
  const lines: string[] = [];
  if (mode !== undefined) {
    lines.push(`        permissionMode: ${escapeJsonString(mode)},`);
  }
  if (rules.length > 0) {
    const ruleLits = rules
      .map(
        (r) =>
          `            { type: ${escapeJsonString(r.type)}, pattern: ${escapeJsonString(r.pattern)}, source: "yaml" },`,
      )
      .join("\n");
    lines.push(
      [
        "        permissionRules: {",
        "          flag: [],",
        "          settings: [],",
        "          yaml: [",
        ruleLits,
        "          ],",
        "          hooks: [],",
        "          builtin: BUILTIN_DEFAULT_RULES,",
        "        },",
      ].join("\n"),
    );
  }
  return `\n${lines.join("\n")}`;
}
