import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { type TargetShape, isTargetShape } from "@crewhaus/docker-images";
/**
 * Section 32 — `@crewhaus/crewhaus-cloud`
 *
 * Composite "managed-as-a-service" recipe:
 *   - default tier: 1× gateway-server, 3× target-managed replicas, 1×
 *     studio replica, Postgres for spec-registry, Redis Streams for
 *     queue-protocol, S3 for hash-chained §20 audit log
 *   - `renderKustomizeOverlay({provider, region, tier})` produces a
 *     deterministic kustomize overlay layered on top of the §32
 *     helm-chart's rendered manifests
 *   - `renderTerraformModule({provider, region})` produces the
 *     Terraform HCL bringing up the cluster (GKE / EKS / AKS) and
 *     associated resources (RDS, ElastiCache, S3 bucket)
 *   - `deployCloud({provider, region, runner})` orchestrates the
 *     terraform → kubectl-apply pipeline; live `terraform apply` is
 *     gated on `TF_BIN` env or an injectable runner (the test pattern
 *     mirrors the §30 SQS adapter — ship the abstraction + injection
 *     point, gate live SDK calls on env)
 *
 * `crewhaus cloud deploy --provider aws --region us-east-1` and
 * `crewhaus cloud teardown` (apps/cli/src/index.ts) call into this
 * package.
 */
import { CrewhausError } from "@crewhaus/errors";
import { type ChartValues, defaultValues, renderChart, validateValues } from "@crewhaus/helm-chart";

export class CrewhausCloudError extends CrewhausError {
  override readonly name = "CrewhausCloudError";
  constructor(message: string, cause?: unknown) {
    super("config", message, cause);
  }
}

export const PROVIDERS = ["aws", "gcp", "azure", "aws-localstack"] as const;
export type CloudProvider = (typeof PROVIDERS)[number];

export const TIERS = ["dev", "default", "production"] as const;
export type Tier = (typeof TIERS)[number];

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const RECIPES_ROOT = join(PACKAGE_ROOT, "recipes");

export function recipesRoot(): string {
  return RECIPES_ROOT;
}

export type CloudConfig = {
  readonly provider: CloudProvider;
  readonly region: string;
  readonly tier: Tier;
  readonly clusterName: string;
  readonly imageTag: string;
};

export function defaultCloudConfig(provider: CloudProvider, region: string): CloudConfig {
  if (!(PROVIDERS as readonly string[]).includes(provider)) {
    throw new CrewhausCloudError(`unknown provider: ${provider}`);
  }
  if (!region || /\s/.test(region)) {
    throw new CrewhausCloudError(`invalid region: ${JSON.stringify(region)}`);
  }
  return {
    provider,
    region,
    tier: "default",
    clusterName: `crewhaus-${provider}-${region}`.replace(/[^a-z0-9-]/g, "-"),
    imageTag: "latest",
  };
}

// ─── Tier sizing ─────────────────────────────────────────────────────────────

export type TierShape = {
  readonly target: TargetShape;
  readonly replicas: number;
};

export function tierShapes(tier: Tier): readonly TierShape[] {
  switch (tier) {
    case "dev":
      return [{ target: "managed", replicas: 1 }];
    case "default":
      return [
        { target: "managed", replicas: 3 },
        // Studio v1 (§31) ships as a managed-shape side helper deployment
      ];
    case "production":
      return [{ target: "managed", replicas: 5 }];
    default: {
      const _exhaustive: never = tier;
      throw new CrewhausCloudError(`unhandled tier: ${String(_exhaustive)}`);
    }
  }
}

// ─── Kustomize overlay rendering ─────────────────────────────────────────────

/** Builds a kustomization.yaml + chart-rendered manifests directory. */
export function renderKustomizeOverlay(config: CloudConfig): {
  kustomization: string;
  manifests: Record<string, string>;
} {
  const shapes = tierShapes(config.tier);
  const manifests: Record<string, string> = {};
  const resourceFiles: string[] = [];

  for (const shape of shapes) {
    const values: ChartValues = {
      ...defaultValues(),
      target: shape.target,
      replicas: shape.replicas,
      image: { ...defaultValues().image, tag: config.imageTag },
    };
    validateValues(values);
    const rendered = renderChart(values, `${config.clusterName}-${shape.target}`);
    for (const [name, body] of Object.entries(rendered)) {
      const fileName = `${shape.target}-${name}`;
      manifests[fileName] = body;
      resourceFiles.push(fileName);
    }
  }

  const kustomization = `# Generated by @crewhaus/crewhaus-cloud (Section 32) — do not edit by hand.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${config.clusterName}
commonLabels:
  crewhaus.ai/cluster: ${config.clusterName}
  crewhaus.ai/provider: ${config.provider}
  crewhaus.ai/region: ${config.region}
  crewhaus.ai/tier: ${config.tier}
resources:
${resourceFiles.map((f) => `  - ${f}`).join("\n")}
`;

  return { kustomization, manifests };
}

// ─── Terraform module rendering ──────────────────────────────────────────────

export function renderTerraformModule(config: CloudConfig): string {
  validateValues({
    ...defaultValues(),
    target: "managed",
    image: { ...defaultValues().image, tag: config.imageTag },
  });
  switch (config.provider) {
    case "aws":
    case "aws-localstack":
      return renderAwsTerraform(config);
    case "gcp":
      return renderGcpTerraform(config);
    case "azure":
      return renderAzureTerraform(config);
    default: {
      const _exhaustive: never = config.provider;
      throw new CrewhausCloudError(`unhandled provider: ${String(_exhaustive)}`);
    }
  }
}

function renderAwsTerraform(config: CloudConfig): string {
  const localstackBlock =
    config.provider === "aws-localstack"
      ? `\n  # LocalStack overrides — wires every AWS service to the LocalStack endpoint
  endpoints {
    eks            = var.localstack_endpoint
    rds            = var.localstack_endpoint
    elasticache    = var.localstack_endpoint
    s3             = var.localstack_endpoint
    ecr            = var.localstack_endpoint
  }
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true`
      : "";

  return `# Generated by @crewhaus/crewhaus-cloud — Terraform module for ${config.provider} (${config.region})
terraform {
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
  }
}

variable "localstack_endpoint" {
  type    = string
  default = "http://localhost:4566"
}

provider "aws" {
  region = "${config.region}"${localstackBlock}
}

resource "aws_eks_cluster" "crewhaus" {
  name     = "${config.clusterName}"
  role_arn = aws_iam_role.cluster.arn
  version  = "1.30"

  vpc_config {
    subnet_ids = aws_subnet.crewhaus[*].id
  }
}

resource "aws_iam_role" "cluster" {
  name = "${config.clusterName}-cluster-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Service = "eks.amazonaws.com" }
      Action = "sts:AssumeRole"
    }]
  })
}

resource "aws_subnet" "crewhaus" {
  count             = 2
  vpc_id            = aws_vpc.crewhaus.id
  cidr_block        = "10.0.\${count.index + 1}.0/24"
  availability_zone = "${config.region}a"
}

resource "aws_vpc" "crewhaus" {
  cidr_block = "10.0.0.0/16"
  tags = { Name = "${config.clusterName}-vpc" }
}

resource "aws_db_instance" "spec_registry" {
  identifier        = "${config.clusterName}-spec-registry"
  engine            = "postgres"
  engine_version    = "15"
  instance_class    = "db.t3.micro"
  allocated_storage = 20
  username          = "crewhaus"
  password          = var.spec_registry_password
  skip_final_snapshot = true
}

resource "aws_elasticache_cluster" "queue" {
  cluster_id           = "${config.clusterName}-queue"
  engine               = "redis"
  node_type            = "cache.t3.micro"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis7"
  port                 = 6379
}

resource "aws_s3_bucket" "audit_log" {
  bucket = "${config.clusterName}-audit"
}

variable "spec_registry_password" {
  type      = string
  sensitive = true
}

output "cluster_endpoint" {
  value = aws_eks_cluster.crewhaus.endpoint
}

output "audit_bucket" {
  value = aws_s3_bucket.audit_log.bucket
}
`;
}

function renderGcpTerraform(config: CloudConfig): string {
  return `# Generated by @crewhaus/crewhaus-cloud — Terraform module for GCP (${config.region})
terraform {
  required_providers {
    google = { source = "hashicorp/google", version = "~> 5.0" }
  }
}

provider "google" {
  region = "${config.region}"
}

resource "google_container_cluster" "crewhaus" {
  name     = "${config.clusterName}"
  location = "${config.region}"

  initial_node_count       = 3
  remove_default_node_pool = false
}

resource "google_sql_database_instance" "spec_registry" {
  name             = "${config.clusterName}-spec-registry"
  database_version = "POSTGRES_15"
  region           = "${config.region}"
  settings { tier = "db-f1-micro" }
}

resource "google_storage_bucket" "audit_log" {
  name     = "${config.clusterName}-audit"
  location = "${config.region}"
  force_destroy = true
}

output "cluster_endpoint" {
  value = google_container_cluster.crewhaus.endpoint
}
`;
}

function renderAzureTerraform(config: CloudConfig): string {
  return `# Generated by @crewhaus/crewhaus-cloud — Terraform module for Azure (${config.region})
terraform {
  required_providers {
    azurerm = { source = "hashicorp/azurerm", version = "~> 3.0" }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "crewhaus" {
  name     = "${config.clusterName}"
  location = "${config.region}"
}

resource "azurerm_kubernetes_cluster" "crewhaus" {
  name                = "${config.clusterName}"
  location            = azurerm_resource_group.crewhaus.location
  resource_group_name = azurerm_resource_group.crewhaus.name
  dns_prefix          = "${config.clusterName}"

  default_node_pool {
    name       = "default"
    node_count = 3
    vm_size    = "Standard_D2_v2"
  }

  identity { type = "SystemAssigned" }
}

resource "azurerm_postgresql_flexible_server" "spec_registry" {
  name                   = "${config.clusterName}-spec-registry"
  resource_group_name    = azurerm_resource_group.crewhaus.name
  location               = azurerm_resource_group.crewhaus.location
  administrator_login    = "crewhaus"
  administrator_password = var.spec_registry_password
  version                = "15"
  sku_name               = "B_Standard_B1ms"
  storage_mb             = 32768
  backup_retention_days  = 7
}

variable "spec_registry_password" {
  type      = string
  sensitive = true
}

output "cluster_fqdn" {
  value = azurerm_kubernetes_cluster.crewhaus.fqdn
}
`;
}

// ─── Deploy / teardown orchestration ─────────────────────────────────────────

export type CloudRunner = (
  argv: readonly string[],
  cwd: string,
) => Promise<{ exitCode: number; stdout: string; stderr: string }>;

export type DeployCloudOptions = {
  readonly config: CloudConfig;
  /** Working directory to write generated artefacts into; defaults to a temp dir. */
  readonly workingDir?: string;
  /** Override the terraform binary path; defaults to env TF_BIN or "terraform". */
  readonly tfBin?: string;
  /** Override the kubectl binary path. */
  readonly kubectlBin?: string;
  /** Test injection point. */
  readonly runner?: CloudRunner;
};

export type DeployCloudResult = {
  readonly workingDir: string;
  readonly steps: ReadonlyArray<{ readonly name: string; readonly skipped?: boolean }>;
  readonly outputs: Readonly<Record<string, string>>;
};

export async function deployCloud(opts: DeployCloudOptions): Promise<DeployCloudResult> {
  const { config } = opts;
  const workingDir = opts.workingDir ?? join(RECIPES_ROOT, ".out", config.clusterName);
  mkdirSync(join(workingDir, "terraform"), { recursive: true });
  mkdirSync(join(workingDir, "kustomize"), { recursive: true });

  // 1. Render the Terraform module + Kustomize overlay onto disk.
  const tfModule = renderTerraformModule(config);
  writeFileSync(join(workingDir, "terraform", "main.tf"), tfModule);

  const overlay = renderKustomizeOverlay(config);
  writeFileSync(join(workingDir, "kustomize", "kustomization.yaml"), overlay.kustomization);
  for (const [name, body] of Object.entries(overlay.manifests)) {
    writeFileSync(join(workingDir, "kustomize", name), body);
  }

  // 2. Run terraform apply (gated on tfBin existing). If unavailable, mark skipped.
  const tfBin = opts.tfBin ?? process.env["TF_BIN"] ?? "terraform";
  const runner = opts.runner;
  const steps: Array<{ name: string; skipped?: boolean }> = [];
  const outputs: Record<string, string> = {};

  if (runner) {
    const init = await runner([tfBin, "init"], join(workingDir, "terraform"));
    if (init.exitCode !== 0) {
      throw new CrewhausCloudError(`terraform init failed: ${init.stderr.slice(0, 1024)}`);
    }
    steps.push({ name: "terraform-init" });

    const apply = await runner(
      [tfBin, "apply", "-auto-approve", "-var", `spec_registry_password=${randomPassword()}`],
      join(workingDir, "terraform"),
    );
    if (apply.exitCode !== 0) {
      throw new CrewhausCloudError(`terraform apply failed: ${apply.stderr.slice(0, 1024)}`);
    }
    steps.push({ name: "terraform-apply" });

    const tfOut = await runner([tfBin, "output", "-json"], join(workingDir, "terraform"));
    if (tfOut.exitCode === 0) {
      try {
        const parsed = JSON.parse(tfOut.stdout) as Record<string, { value: string }>;
        for (const [k, v] of Object.entries(parsed)) {
          outputs[k] = v.value;
        }
      } catch {
        // Non-fatal — leave outputs empty.
      }
    }

    const kubectlBin = opts.kubectlBin ?? "kubectl";
    const kapply = await runner([kubectlBin, "apply", "-k", "."], join(workingDir, "kustomize"));
    if (kapply.exitCode !== 0) {
      throw new CrewhausCloudError(`kubectl apply failed: ${kapply.stderr.slice(0, 1024)}`);
    }
    steps.push({ name: "kubectl-apply" });
  } else {
    steps.push({ name: "terraform-init", skipped: true });
    steps.push({ name: "terraform-apply", skipped: true });
    steps.push({ name: "kubectl-apply", skipped: true });
  }

  return { workingDir, steps, outputs };
}

export async function teardownCloud(opts: DeployCloudOptions): Promise<void> {
  const tfBin = opts.tfBin ?? process.env["TF_BIN"] ?? "terraform";
  const workingDir = opts.workingDir ?? join(RECIPES_ROOT, ".out", opts.config.clusterName);
  if (!existsSync(workingDir)) {
    throw new CrewhausCloudError(
      `no working directory at ${workingDir} (was deployCloud ever run?)`,
    );
  }
  const runner = opts.runner;
  if (!runner) {
    return; // no-op when there's no runner available
  }
  const result = await runner(
    [tfBin, "destroy", "-auto-approve", "-var", `spec_registry_password=${randomPassword()}`],
    join(workingDir, "terraform"),
  );
  if (result.exitCode !== 0) {
    throw new CrewhausCloudError(`terraform destroy failed: ${result.stderr.slice(0, 1024)}`);
  }
}

function randomPassword(): string {
  // 24 hex chars — only used as a placeholder so the Terraform variable is set;
  // production users override via -var-file. Sourced from a CSPRNG so that, if
  // an operator does not override it, the provisioned DB admin credential is not
  // derived from a predictable Math.random() stream (CWE-338).
  return randomBytes(12).toString("hex");
}

/** Used by the CLI subcommand to enumerate provider choices. */
export function listProviders(): readonly CloudProvider[] {
  return PROVIDERS;
}

/** Used by the CLI subcommand for input validation. */
export function isCloudProvider(value: unknown): value is CloudProvider {
  return typeof value === "string" && (PROVIDERS as readonly string[]).includes(value);
}

/** Sanity check used by the smoke test. */
export function summariseDeploy(result: DeployCloudResult): string {
  const lines = [`Working dir: ${result.workingDir}`];
  for (const step of result.steps) {
    lines.push(`  ${step.skipped ? "skip" : "ok"}  ${step.name}`);
  }
  for (const [k, v] of Object.entries(result.outputs)) {
    lines.push(`  out  ${k} = ${v}`);
  }
  return lines.join("\n");
}

export { isTargetShape };
