import { describe, expect, test } from "bun:test";
import type { IrChannelV0 } from "@crewhaus/ir";
import { TargetEmitError, emitChannelBot } from "./index";

const MIN_IR: IrChannelV0 = {
  version: 0,
  name: "demo",
  target: "channel",
  agent: { model: "claude-sonnet-4-6", instructions: "be helpful" },
  tools: [],
  toolConfigs: {},
  channels: {
    slack: {
      botToken: { kind: "env", name: "SLACK_BOT_TOKEN" },
      signingSecret: { kind: "env", name: "SLACK_SIGNING_SECRET" },
    },
  },
  routing: { sessionKey: "thread" },
  mcp_servers: {},
  permissions: { rules: [] },
  subAgents: [],
  compaction: {},
};

const fileMap = (ir: IrChannelV0): Map<string, string> =>
  new Map(emitChannelBot(ir).files.map((f) => [f.path, f.content]));

describe("emitChannelBot — bundle structure (T1)", () => {
  test("emits the four code files plus the generated README.md (item 42)", () => {
    const bundle = emitChannelBot(MIN_IR);
    const paths = bundle.files.map((f) => f.path).sort();
    expect(paths).toEqual([
      "README.md",
      "agent.ts",
      "daemon.ts",
      "gateway.ts",
      "session-router.ts",
    ]);
  });

  test("readme: false restores the four-file bundle (item 42 opt-out)", () => {
    const bundle = emitChannelBot(MIN_IR, { readme: false });
    const paths = bundle.files.map((f) => f.path).sort();
    expect(paths).toEqual(["agent.ts", "daemon.ts", "gateway.ts", "session-router.ts"]);
  });

  test("each code file starts with the generated marker", () => {
    const bundle = emitChannelBot(MIN_IR);
    for (const f of bundle.files.filter((x) => x.path.endsWith(".ts"))) {
      expect(f.content).toContain("Generated by crewhaus. DO NOT EDIT.");
    }
    // The README carries its own generation marker instead.
    const readme = bundle.files.find((f) => f.path === "README.md");
    expect(readme?.content).toContain("Generated by CrewHaus");
  });

  test("daemon.ts has a shebang; non-entrypoint files do not", () => {
    const files = fileMap(MIN_IR);
    expect(files.get("daemon.ts")?.startsWith("#!/usr/bin/env bun")).toBe(true);
    expect(files.get("agent.ts")?.startsWith("#!")).toBe(false);
    expect(files.get("gateway.ts")?.startsWith("#!")).toBe(false);
    expect(files.get("session-router.ts")?.startsWith("#!")).toBe(false);
  });
});

describe("emitChannelBot — inbound reaction feedback (feedback.channelReactions)", () => {
  const withReactions = (sessionKey: "channel" | "user" | "thread"): IrChannelV0 => ({
    ...MIN_IR,
    routing: { sessionKey },
    feedback: { modality: "binary", channelReactions: true },
  });

  test("no feedback block → session-router has no handleReaction; gateway skips reactions", () => {
    const files = fileMap(MIN_IR);
    const router = files.get("session-router.ts") ?? "";
    const gateway = files.get("gateway.ts") ?? "";
    expect(router).not.toContain("handleReaction");
    expect(router).not.toContain("user_feedback");
    // Gateway still narrows the reaction kind (type-safety) but only ACKs it.
    expect(gateway).toContain('parsed.kind === "reaction"');
    expect(gateway).not.toContain("handleReaction");
  });

  test("channel session-key → handleReaction appends a channel-sourced user_feedback line", () => {
    const files = fileMap(withReactions("channel"));
    const router = files.get("session-router.ts") ?? "";
    const gateway = files.get("gateway.ts") ?? "";
    expect(router).toContain('import { openEventLog } from "@crewhaus/event-log";');
    expect(router).toContain("async handleReaction(");
    expect(router).toContain('kind: "user_feedback"');
    expect(router).toContain('source: "channel"');
    expect(router).toContain("thumbs: reaction.vote");
    // channel routing key, not the reaction's own ts.
    expect(router).toContain("${adapter.id}:${reaction.workspaceId}:${reaction.channelId}");
    // gateway dedups + dispatches the reaction (and does NOT run a model turn for it).
    expect(gateway).toContain("config.sessionRouter.handleReaction(parsed.reaction, adapter)");
    expect(gateway).toContain("dedup.remember(parsed.reaction.idempotencyKey)");
  });

  test("user session-key → reaction routing key uses the reacting user", () => {
    const router = fileMap(withReactions("user")).get("session-router.ts") ?? "";
    expect(router).toContain("${adapter.id}:${reaction.workspaceId}:${reaction.userId}");
  });

  test("thread session-key → handleReaction is a no-op (can't attribute without a join store)", () => {
    const router = fileMap(withReactions("thread")).get("session-router.ts") ?? "";
    expect(router).toContain("async handleReaction(");
    expect(router).toContain("can't attribute a reaction");
    expect(router).not.toContain('kind: "user_feedback"');
  });
});

describe("emitChannelBot — daemon.ts wiring", () => {
  test("imports the channel-generic gateway, session-router, and agent", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain('import { createAgent } from "./agent.js";');
    expect(c).toContain('import { createSessionRouter } from "./session-router.js";');
    expect(c).toContain('import { createGateway } from "./gateway.js";');
  });

  test("starts a Bun.serve and registers SIGINT/SIGTERM shutdown", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain("Bun.serve({");
    expect(c).toContain('process.on("SIGINT"');
    expect(c).toContain('process.on("SIGTERM"');
    expect(c).toContain("server.stop(true)");
  });

  test("boots the self-heal janitor before serving webhooks (ops #36)", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain('import { createJanitor } from "@crewhaus/runtime-core";');
    expect(c).toContain("const __janitor = createJanitor({");
    // Boot-time runOnce, env kill-switch, and configurable hourly interval.
    expect(c).toContain('process.env["CREWHAUS_JANITOR"] !== "0"');
    expect(c).toContain("await __janitor.runOnce()");
    expect(c).toContain(
      '__janitor.start(Number(process.env["CREWHAUS_JANITOR_INTERVAL_MS"] ?? 3_600_000))',
    );
    // The janitor boots ahead of the webhook listener.
    expect(c.indexOf("createJanitor({")).toBeLessThan(c.indexOf("Bun.serve({"));
    // Shutdown halts the interval.
    expect(c).toContain("__janitor.stop();");
  });

  test("janitor honors .crewhaus/retention.json pins + TTL (ops-review F2)", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    // The SAME loader the retention CLI uses, so the two paths cannot drift.
    expect(c).toContain('import { loadRetentionConfig } from "@crewhaus/data-retention-engine"');
    expect(c).toContain("await loadRetentionConfig(__cwd)");
    expect(c).toContain("sessionTtlDays: __retentionTtlDays");
    expect(c).toContain("pinnedSessionIds: __retentionPins");
    // A malformed config fails safe: eviction disabled, daemon keeps serving.
    expect(c).toContain("__retentionTtlDays = Number.POSITIVE_INFINITY");
    expect(c).toContain("janitor session eviction disabled");
  });

  test("constructs createSlackAdapter with the configured secret references", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain("createSlackAdapter({");
    expect(c).toContain('process.env["SLACK_BOT_TOKEN"]');
    expect(c).toContain('process.env["SLACK_SIGNING_SECRET"]');
    expect(c).toContain('registerChannelAdapter("slack", slackAdapter);');
  });

  test("emits a startup-time check that exits non-zero when env vars are unset", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain('"SLACK_BOT_TOKEN"');
    expect(c).toContain('"SLACK_SIGNING_SECRET"');
    expect(c).toContain("process.exit(2)");
    expect(c).toContain("missing required env vars");
  });

  test("literal secret values are embedded verbatim and skip the channel env-check", () => {
    const irLit: IrChannelV0 = {
      ...MIN_IR,
      channels: {
        slack: {
          botToken: { kind: "literal", value: "xoxb-literal" },
          signingSecret: { kind: "literal", value: "literal-signing" },
        },
      },
    };
    const c = fileMap(irLit).get("daemon.ts") ?? "";
    expect(c).toContain('"xoxb-literal"');
    expect(c).toContain('"literal-signing"');
    // No per-name channel env list when there are no env-refs…
    expect(c).not.toContain("const __requiredEnv =");
    expect(c).not.toContain('"SLACK_BOT_TOKEN"');
    // …but the provider credential group (claude-* model → Anthropic
    // either-or) is still enforced at startup.
    expect(c).toContain("__providerEnvAnyOf");
    expect(c).toContain('["ANTHROPIC_AUTH_TOKEN","ANTHROPIC_API_KEY"]');
    expect(c).toContain("missing required env vars");
  });

  test("loads hooks/skills/slash-commands like the cli target", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain('import { loadHooks } from "@crewhaus/hooks-engine";');
    expect(c).toContain("discoverSkills({ cwd: __cwd })");
    expect(c).toContain("loadCommands({ cwd: __cwd })");
    expect(c).toContain("createSkillTool(__skills)");
  });

  test("registers ir.tools on defaultCatalog when non-empty", () => {
    const irTools: IrChannelV0 = {
      ...MIN_IR,
      tools: ["read", "bash", "sendMessage"],
    };
    const c = fileMap(irTools).get("daemon.ts") ?? "";
    expect(c).toContain('import { read } from "@crewhaus/tool-fs";');
    expect(c).toContain('import { bash } from "@crewhaus/tool-bash";');
    expect(c).toContain('import { sendMessage } from "@crewhaus/tool-message-channel";');
    expect(c).toContain("defaultCatalog.register(read);");
    expect(c).toContain("defaultCatalog.register(bash);");
    expect(c).toContain("defaultCatalog.register(sendMessage);");
  });

  test("rejects unknown tool names", () => {
    const irBad: IrChannelV0 = { ...MIN_IR, tools: ["nonexistent"] };
    expect(() => emitChannelBot(irBad)).toThrow(TargetEmitError);
    expect(() => emitChannelBot(irBad)).toThrow(/unknown tool/);
  });

  test("emits MCP boot block when mcp_servers is non-empty", () => {
    const irMcp: IrChannelV0 = {
      ...MIN_IR,
      mcp_servers: {
        fs: { transport: "stdio", command: "npx", args: ["-y", "fs-server"] },
      },
    };
    const c = fileMap(irMcp).get("daemon.ts") ?? "";
    expect(c).toContain("new McpHost();");
    expect(c).toContain('mcpHost.addServer("fs"');
    expect(c).toContain("mcpHost.disconnectAll()");
  });

  test("0.3.0 — env secret refs are embedded UNRESOLVED and resolved at daemon boot", () => {
    const irMcp: IrChannelV0 = {
      ...MIN_IR,
      mcp_servers: {
        thredz: {
          transport: "stdio",
          command: "npx",
          args: ["-y", "thredz-mcp@0.2.0"],
          env: { THREDZ_API_KEY: { kind: "env", name: "THREDZ_API_KEY" } },
        },
      },
    };
    const c = fileMap(irMcp).get("daemon.ts") ?? "";
    expect(c).toContain('import { McpHost, resolveMcpServerConfig } from "@crewhaus/mcp-host";');
    expect(c).toContain('{"kind":"env","name":"THREDZ_API_KEY"}');
    expect(c).toContain("resolveMcpServerConfig(");
    expect(c).toContain('{ name: "thredz" }');
  });
});

describe("emitChannelBot — session-router.ts", () => {
  test("derives sess_<16hex> ids via sha256 of the routing key", () => {
    const c = fileMap(MIN_IR).get("session-router.ts") ?? "";
    expect(c).toContain('createHash("sha256")');
    expect(c).toContain('"sess_" +');
    expect(c).toContain(".slice(0, 16)");
  });

  test("threadKey strategy keys by workspace + channel + thread", () => {
    const c = fileMap(MIN_IR).get("session-router.ts") ?? "";
    expect(c).toContain("event.threadTs ?? event.ts");
    expect(c).toContain("event.workspaceId");
    expect(c).toContain("event.channelId");
  });

  test("user strategy keys by workspace + user only", () => {
    const irUser: IrChannelV0 = { ...MIN_IR, routing: { sessionKey: "user" } };
    const c = fileMap(irUser).get("session-router.ts") ?? "";
    expect(c).toContain("event.userId");
    expect(c).not.toContain("event.threadTs");
  });

  test("channel strategy keys by workspace + channel only", () => {
    const irCh: IrChannelV0 = { ...MIN_IR, routing: { sessionKey: "channel" } };
    const c = fileMap(irCh).get("session-router.ts") ?? "";
    expect(c).toContain("event.channelId");
    expect(c).not.toContain("event.threadTs");
    expect(c).not.toContain("event.userId");
  });

  test("creates a fresh session on first inbound and resumes after that", () => {
    const c = fileMap(MIN_IR).get("session-router.ts") ?? "";
    expect(c).toContain("sessionStore.get(sessionId)");
    expect(c).toContain("sessionStore.create({");
    expect(c).toContain("isNew");
  });
});

describe("emitChannelBot — agent.ts", () => {
  test("uses singleTurn + resume for non-new turns and just singleTurn for first turn", () => {
    const c = fileMap(MIN_IR).get("agent.ts") ?? "";
    expect(c).toContain("singleTurn: true");
    expect(c).toContain("resume: { sessionId: args.sessionId }");
    // The seed now carries the boundary-classified inbound (__inbound), not
    // the raw args.message — see the Pillar-3 channel-boundary test below.
    expect(c).toContain('seedMessages: [{ role: "user", content: __inbound }]');
    expect(c).not.toContain('seedMessages: [{ role: "user", content: args.message }]');
    expect(c).toContain('sessionTarget: "channel"');
    expect(c).toContain('sessionName: "demo"');
  });

  test("threads compaction.model into runChatLoop as compactionModel (escaped); omitted when absent", () => {
    const withModel: IrChannelV0 = {
      ...MIN_IR,
      compaction: { model: "claude-haiku-4-5-20251001" },
    };
    const c = fileMap(withModel).get("agent.ts") ?? "";
    expect(c).toContain('compactionModel: "claude-haiku-4-5-20251001"');
    const without = fileMap(MIN_IR).get("agent.ts") ?? "";
    expect(without).not.toContain("compactionModel:");
  });

  test("classifies inbound channel text at the boundary before seeding the model (Pillar 3, FR-005)", () => {
    const c = fileMap(MIN_IR).get("agent.ts") ?? "";
    // Imports the channel boundary chokepoint.
    expect(c).toContain('import { classifyInbound } from "@crewhaus/channel-adapter-base";');
    // Calls it on the inbound message with the per-run runContext + channel origin.
    expect(c).toContain('classifyInbound(args.message, runContext, { origin: "channel" })');
    // The classify runs BEFORE the runChatLoop call (the redacted/tagged text
    // is what reaches the model), and its result feeds the seed.
    const classifyIdx = c.indexOf("classifyInbound(args.message");
    const loopIdx = c.indexOf("runChatLoop({");
    expect(classifyIdx).toBeGreaterThan(-1);
    expect(loopIdx).toBeGreaterThan(-1);
    expect(classifyIdx).toBeLessThan(loopIdx);
    expect(c).toContain("const __inbound = await classifyInbound(");
  });

  test("threads model + instructions + permissions from the IR", () => {
    const irPerm: IrChannelV0 = {
      ...MIN_IR,
      permissions: {
        mode: "auto",
        rules: [{ type: "alwaysAllow", pattern: "Read" }],
      },
    };
    const c = fileMap(irPerm).get("agent.ts") ?? "";
    expect(c).toContain('"claude-sonnet-4-6"');
    expect(c).toContain('"be helpful"');
    expect(c).toContain('permissionMode: "auto"');
    expect(c).toContain('pattern: "Read"');
    expect(c).toContain("BUILTIN_DEFAULT_RULES");
  });
});

describe("emitChannelBot — gateway.ts", () => {
  test("dedups by adapter-supplied idempotencyKey", () => {
    const c = fileMap(MIN_IR).get("gateway.ts") ?? "";
    expect(c).toContain("idempotencyKey");
    expect(c).toContain("dedup");
  });

  // SECURITY (audit R3): the dedup store is pluggable, the in-memory default
  // is behavior-preserving, and remember() is awaited (an unawaited Promise
  // is always truthy — every inbound event would be dropped as a duplicate).
  test("dedup runs through a pluggable DedupStore and remember() is awaited", () => {
    const c = fileMap(MIN_IR).get("gateway.ts") ?? "";
    expect(c).toContain('from "@crewhaus/durable-state"');
    expect(c).toContain("dedupStore?: DedupStore");
    expect(c).toContain("config.dedupStore ?? new InMemoryDedupStore");
    expect(c).toContain("await dedup.remember(parsed.event.idempotencyKey)");
  });

  test("daemon wires CREWHAUS_DEDUP_STORE through createDedupStore", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain('createDedupStore(process.env["CREWHAUS_DEDUP_STORE"] ?? "memory")');
    expect(c).toContain("dedupStore: __dedupStore");
  });

  test("returns 401 on signature mismatch", () => {
    const c = fileMap(MIN_IR).get("gateway.ts") ?? "";
    expect(c).toContain("status: 401");
    expect(c).toContain("invalid signature");
  });

  test("handles url_verification challenge with a plaintext body", () => {
    const c = fileMap(MIN_IR).get("gateway.ts") ?? "";
    expect(c).toContain('"text/plain"');
    expect(c).toContain("parsed.challenge");
  });

  test("matches /<adapter>/events path prefix", () => {
    const c = fileMap(MIN_IR).get("gateway.ts") ?? "";
    // The generated regex literal is /^\/([^/]+)\/events$/ — match the
    // /events$ tail to confirm the routing pattern is in place.
    expect(c).toContain("/events$/");
  });

  test("ACKs 200 immediately and dispatches the model turn asynchronously", () => {
    // Slack/Telegram/Discord/WhatsApp all expect a fast ACK on inbound
    // webhooks (Slack's documented bound is 3 s). Driving the model turn
    // synchronously would block the response and surface transient API
    // errors as 500s, prompting platform-side retries and duplicate work.
    // Confirm the generated handler dispatches the model call out-of-band
    // and never returns 500 from the inline handler path.
    const c = fileMap(MIN_IR).get("gateway.ts") ?? "";
    expect(c).toContain("queueMicrotask(");
    expect(c).toContain("config.sessionRouter.handle(parsed.event, adapter).catch");
    // The 500-on-handler-error branch from the prior synchronous-await
    // implementation should be gone. Any remaining `status: 500` in this
    // file would indicate a regression.
    expect(c).not.toContain("status: 500");
    expect(c).not.toContain('"handler error"');
  });
});

describe("emitChannelBot — error cases", () => {
  test("throws TargetEmitError when the channels block has no channels at all", () => {
    const irNoChannels: IrChannelV0 = {
      ...MIN_IR,
      channels: {},
    };
    expect(() => emitChannelBot(irNoChannels)).toThrow(TargetEmitError);
  });
});

describe("emitChannelBot — Telegram channel (Section 33)", () => {
  const TELEGRAM_IR: IrChannelV0 = {
    ...MIN_IR,
    channels: {
      telegram: {
        botToken: { kind: "env", name: "TELEGRAM_BOT_TOKEN" },
        secretToken: { kind: "env", name: "TELEGRAM_SECRET_TOKEN" },
      },
    },
  };

  test('daemon.ts imports createTelegramAdapter and registers under "telegram"', () => {
    const c = fileMap(TELEGRAM_IR).get("daemon.ts") ?? "";
    expect(c).toContain(
      'import { createTelegramAdapter } from "@crewhaus/channel-adapter-telegram";',
    );
    expect(c).toContain('registerChannelAdapter("telegram", telegramAdapter);');
    expect(c).toContain('["telegram", telegramAdapter]');
  });

  test("daemon.ts wires Telegram secret env vars into the startup env-check", () => {
    const c = fileMap(TELEGRAM_IR).get("daemon.ts") ?? "";
    expect(c).toContain('"TELEGRAM_BOT_TOKEN"');
    expect(c).toContain('"TELEGRAM_SECRET_TOKEN"');
    expect(c).toContain("missing required env vars");
  });

  test("daemon.ts can register both slack and telegram side-by-side", () => {
    const both: IrChannelV0 = {
      ...MIN_IR,
      channels: {
        slack: {
          botToken: { kind: "env", name: "SLACK_BOT_TOKEN" },
          signingSecret: { kind: "env", name: "SLACK_SIGNING_SECRET" },
        },
        telegram: {
          botToken: { kind: "env", name: "TELEGRAM_BOT_TOKEN" },
          secretToken: { kind: "env", name: "TELEGRAM_SECRET_TOKEN" },
        },
      },
    };
    const c = fileMap(both).get("daemon.ts") ?? "";
    expect(c).toContain("createSlackAdapter");
    expect(c).toContain("createTelegramAdapter");
    expect(c).toContain('["slack", slackAdapter]');
    expect(c).toContain('["telegram", telegramAdapter]');
  });

  test("literal Telegram secrets embed verbatim and skip the channel env-check", () => {
    const irLit: IrChannelV0 = {
      ...MIN_IR,
      channels: {
        telegram: {
          botToken: { kind: "literal", value: "literal-bot-token" },
          secretToken: { kind: "literal", value: "literal-secret" },
        },
      },
    };
    const c = fileMap(irLit).get("daemon.ts") ?? "";
    expect(c).toContain('"literal-bot-token"');
    expect(c).toContain('"literal-secret"');
    // No per-name channel env list — only the provider either-or group
    // (claude-* model) remains.
    expect(c).not.toContain("const __requiredEnv =");
    expect(c).toContain("__providerEnvAnyOf");
  });
});

// ---------------------------------------------------------------------------
// Provider credential groups — derived from agent.model via parseModelString
// at emit time. Either-or semantics: any ONE name per group satisfies the
// startup check (distinct from the all-required channel-secret list).
// ---------------------------------------------------------------------------

describe("emitChannelBot — provider env requirement (model-derived)", () => {
  const withModel = (model: string): IrChannelV0 => ({
    ...MIN_IR,
    agent: { ...MIN_IR.agent, model },
  });

  test("claude-* model requires ANTHROPIC_AUTH_TOKEN or ANTHROPIC_API_KEY (either)", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain('["ANTHROPIC_AUTH_TOKEN","ANTHROPIC_API_KEY"]');
    expect(c).toContain(".filter((g) => !g.some((n) => process.env[n]))");
    // The channel secrets stay individually required alongside the group.
    expect(c).toContain('"SLACK_BOT_TOKEN"');
    expect(c).toContain('"SLACK_SIGNING_SECRET"');
  });

  test("openai/ model requires OPENAI_API_KEY or OPENAI_BASE_URL — and NOT Anthropic creds", () => {
    const c = fileMap(withModel("openai/gpt-4o-mini")).get("daemon.ts") ?? "";
    expect(c).toContain('["OPENAI_API_KEY","OPENAI_BASE_URL"]');
    expect(c).not.toContain("ANTHROPIC_AUTH_TOKEN");
  });

  test("gemini/ model requires GEMINI_API_KEY or GOOGLE_API_KEY", () => {
    const c = fileMap(withModel("gemini/gemini-2.5-flash")).get("daemon.ts") ?? "";
    expect(c).toContain('["GEMINI_API_KEY","GOOGLE_API_KEY"]');
    expect(c).not.toContain("ANTHROPIC_AUTH_TOKEN");
  });

  test("bedrock/ model adds no provider group (AWS SDK credential chain is authoritative)", () => {
    const c =
      fileMap(withModel("bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0")).get("daemon.ts") ??
      "";
    expect(c).not.toContain("__providerEnvAnyOf");
    // The channel-secret check is still present.
    expect(c).toContain('"SLACK_BOT_TOKEN"');
    expect(c).toContain("missing required env vars");
  });

  test("local/<m>@<url> model adds no provider group (no credentials needed)", () => {
    const c = fileMap(withModel("local/llama3.2@http://localhost:11434/v1")).get("daemon.ts") ?? "";
    expect(c).not.toContain("__providerEnvAnyOf");
  });

  test("a model outside the router grammar adds no provider group (runtime raises the real error)", () => {
    // The spec layer does not enforce the router grammar at emit time —
    // compiler fixtures use placeholder models like "m". resolveModel
    // raises the authoritative ConfigError when the daemon actually runs.
    const c = fileMap(withModel("gpt-4o-mini")).get("daemon.ts") ?? "";
    expect(c).not.toContain("__providerEnvAnyOf");
    expect(c).toContain('"SLACK_BOT_TOKEN"'); // channel check unaffected
  });

  test("the generated startup check enforces either-or at runtime (executable semantics)", () => {
    // Execute the generated check's exact predicate in-process with a
    // synthetic env to pin the either-or semantics (not just source text).
    const groups: string[][] = [["ANTHROPIC_AUTH_TOKEN", "ANTHROPIC_API_KEY"]];
    const env1: Record<string, string | undefined> = { ANTHROPIC_API_KEY: "k" };
    const env2: Record<string, string | undefined> = {};
    const missing1 = groups.filter((g) => !g.some((n) => env1[n])).map((g) => g.join(" or "));
    const missing2 = groups.filter((g) => !g.some((n) => env2[n])).map((g) => g.join(" or "));
    expect(missing1).toEqual([]);
    expect(missing2).toEqual(["ANTHROPIC_AUTH_TOKEN or ANTHROPIC_API_KEY"]);
  });
});

describe("emitChannelBot — Discord channel (Section 33)", () => {
  const DISCORD_IR: IrChannelV0 = {
    ...MIN_IR,
    channels: {
      discord: {
        applicationId: { kind: "env", name: "DISCORD_APPLICATION_ID" },
        botToken: { kind: "env", name: "DISCORD_BOT_TOKEN" },
        publicKeyHex: { kind: "env", name: "DISCORD_PUBLIC_KEY" },
      },
    },
  };

  test('daemon.ts imports createDiscordAdapter and registers under "discord"', () => {
    const c = fileMap(DISCORD_IR).get("daemon.ts") ?? "";
    expect(c).toContain(
      'import { createDiscordAdapter } from "@crewhaus/channel-adapter-discord";',
    );
    expect(c).toContain('registerChannelAdapter("discord", discordAdapter);');
    expect(c).toContain('["discord", discordAdapter]');
  });

  test("daemon.ts wires Discord secrets into startup env-check", () => {
    const c = fileMap(DISCORD_IR).get("daemon.ts") ?? "";
    expect(c).toContain('"DISCORD_APPLICATION_ID"');
    expect(c).toContain('"DISCORD_BOT_TOKEN"');
    expect(c).toContain('"DISCORD_PUBLIC_KEY"');
  });

  test("daemon.ts can register slack + telegram + discord side-by-side", () => {
    const all: IrChannelV0 = {
      ...MIN_IR,
      channels: {
        slack: {
          botToken: { kind: "env", name: "SLACK_BOT_TOKEN" },
          signingSecret: { kind: "env", name: "SLACK_SIGNING_SECRET" },
        },
        telegram: {
          botToken: { kind: "env", name: "TELEGRAM_BOT_TOKEN" },
          secretToken: { kind: "env", name: "TELEGRAM_SECRET_TOKEN" },
        },
        discord: {
          applicationId: { kind: "env", name: "DISCORD_APPLICATION_ID" },
          botToken: { kind: "env", name: "DISCORD_BOT_TOKEN" },
          publicKeyHex: { kind: "env", name: "DISCORD_PUBLIC_KEY" },
        },
      },
    };
    const c = fileMap(all).get("daemon.ts") ?? "";
    expect(c).toContain("createSlackAdapter");
    expect(c).toContain("createTelegramAdapter");
    expect(c).toContain("createDiscordAdapter");
    expect(c).toContain('["slack", slackAdapter]');
    expect(c).toContain('["telegram", telegramAdapter]');
    expect(c).toContain('["discord", discordAdapter]');
  });
});

describe("emitChannelBot — WhatsApp channel (Section 33)", () => {
  const WHATSAPP_IR: IrChannelV0 = {
    ...MIN_IR,
    channels: {
      whatsapp: {
        phoneNumberId: { kind: "env", name: "WHATSAPP_PHONE_NUMBER_ID" },
        accessToken: { kind: "env", name: "WHATSAPP_ACCESS_TOKEN" },
        appSecret: { kind: "env", name: "WHATSAPP_APP_SECRET" },
      },
    },
  };

  test('daemon.ts imports createWhatsAppAdapter and registers under "whatsapp"', () => {
    const c = fileMap(WHATSAPP_IR).get("daemon.ts") ?? "";
    expect(c).toContain(
      'import { createWhatsAppAdapter } from "@crewhaus/channel-adapter-whatsapp";',
    );
    expect(c).toContain('registerChannelAdapter("whatsapp", whatsappAdapter);');
    expect(c).toContain('["whatsapp", whatsappAdapter]');
  });

  test("daemon.ts wires WhatsApp secrets into startup env-check", () => {
    const c = fileMap(WHATSAPP_IR).get("daemon.ts") ?? "";
    expect(c).toContain('"WHATSAPP_PHONE_NUMBER_ID"');
    expect(c).toContain('"WHATSAPP_ACCESS_TOKEN"');
    expect(c).toContain('"WHATSAPP_APP_SECRET"');
  });

  test("daemon.ts can register all four channel adapters side-by-side", () => {
    const all: IrChannelV0 = {
      ...MIN_IR,
      channels: {
        slack: {
          botToken: { kind: "env", name: "SLACK_BOT_TOKEN" },
          signingSecret: { kind: "env", name: "SLACK_SIGNING_SECRET" },
        },
        telegram: {
          botToken: { kind: "env", name: "TELEGRAM_BOT_TOKEN" },
          secretToken: { kind: "env", name: "TELEGRAM_SECRET_TOKEN" },
        },
        discord: {
          applicationId: { kind: "env", name: "DISCORD_APPLICATION_ID" },
          botToken: { kind: "env", name: "DISCORD_BOT_TOKEN" },
          publicKeyHex: { kind: "env", name: "DISCORD_PUBLIC_KEY" },
        },
        whatsapp: {
          phoneNumberId: { kind: "env", name: "WHATSAPP_PHONE_NUMBER_ID" },
          accessToken: { kind: "env", name: "WHATSAPP_ACCESS_TOKEN" },
          appSecret: { kind: "env", name: "WHATSAPP_APP_SECRET" },
        },
      },
    };
    const c = fileMap(all).get("daemon.ts") ?? "";
    expect(c).toContain("createSlackAdapter");
    expect(c).toContain("createTelegramAdapter");
    expect(c).toContain("createDiscordAdapter");
    expect(c).toContain("createWhatsAppAdapter");
    expect(c).toContain('["whatsapp", whatsappAdapter]');
  });
});

describe("emitChannelBot — iMessage channel (Section 33)", () => {
  const IMESSAGE_IR: IrChannelV0 = {
    ...MIN_IR,
    channels: {
      imessage: {},
    },
  };

  test('daemon.ts imports createIMessageAdapter and registers under "imessage"', () => {
    const c = fileMap(IMESSAGE_IR).get("daemon.ts") ?? "";
    expect(c).toContain(
      'import { createIMessageAdapter } from "@crewhaus/channel-adapter-imessage";',
    );
    expect(c).toContain('registerChannelAdapter("imessage", imessageAdapter);');
    expect(c).toContain('["imessage", imessageAdapter]');
  });

  test("daemon.ts emits imessage adapter with no fields when none configured", () => {
    const c = fileMap(IMESSAGE_IR).get("daemon.ts") ?? "";
    expect(c).toContain("createIMessageAdapter({");
    // No channel env-check entries because none of the optional fields are
    // set; only the model-derived provider group remains.
    expect(c).not.toContain("const __requiredEnv =");
    expect(c).toContain("__providerEnvAnyOf");
  });

  test("daemon.ts emits chatDbPath / cursorPath when configured via env", () => {
    const irWithPaths: IrChannelV0 = {
      ...MIN_IR,
      channels: {
        imessage: {
          chatDbPath: { kind: "env", name: "MY_CHAT_DB" },
          cursorPath: { kind: "env", name: "MY_CURSOR" },
        },
      },
    };
    const c = fileMap(irWithPaths).get("daemon.ts") ?? "";
    expect(c).toContain('chatDbPath: process.env["MY_CHAT_DB"]');
    expect(c).toContain('cursorPath: process.env["MY_CURSOR"]');
    expect(c).toContain('"MY_CHAT_DB"');
    expect(c).toContain('"MY_CURSOR"');
  });
});

describe("emitChannelBot — emoji reactions (Phase 3 §3.2)", () => {
  test("session-router emits tryReact eyes/white_check_mark/warning", () => {
    const c = fileMap(MIN_IR).get("session-router.ts") ?? "";
    expect(c).toContain("tryReact");
    expect(c).toContain('"eyes"');
    expect(c).toContain('"white_check_mark"');
    expect(c).toContain('"warning"');
    // Should guard on adapter.react presence before calling.
    expect(c).toContain("if (!adapter.react)");
  });

  test("react failures are best-effort (try/catch)", () => {
    const c = fileMap(MIN_IR).get("session-router.ts") ?? "";
    // The tryReact helper catches errors and swallows them so the
    // model turn proceeds even if Slack's reactions.add 5xxs.
    expect(c).toMatch(/try\s*\{[^}]*await adapter\.react/);
  });

  test("warning emoji fires when the runTurn throws", () => {
    const c = fileMap(MIN_IR).get("session-router.ts") ?? "";
    // The outer try/catch around runTurn re-throws after warning react
    // so the gateway can return a 5xx; this is the right contract.
    expect(c).toContain("throw err");
  });
});

describe("emitChannelBot — gateway control-UI (Phase 3 §3.4)", () => {
  test("omits gateway server when ir.gateway is undefined", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).not.toContain("__gatewayServer");
    expect(c).not.toContain("/status");
  });

  test("emits Bun.serve on configured port when gateway is set", () => {
    const ir: IrChannelV0 = {
      ...MIN_IR,
      gateway: { port: 19001, ui: true },
    };
    const c = fileMap(ir).get("daemon.ts") ?? "";
    expect(c).toContain("19001");
    expect(c).toContain("__gatewayServer = Bun.serve");
    expect(c).toContain('"/status"');
    expect(c).toContain("[gateway] listening on");
  });

  test("gateway.ui:false suppresses HTML dashboard route", () => {
    const ir: IrChannelV0 = {
      ...MIN_IR,
      gateway: { port: 18080, ui: false },
    };
    const c = fileMap(ir).get("daemon.ts") ?? "";
    // The ui-flag is a runtime boolean (rendered as literal),
    // and the HTML branch checks it before serving.
    expect(c).toContain("__gatewayUiEnabled = false");
    expect(c).toContain("18080");
  });

  test("status endpoint reports declared channels", () => {
    const ir: IrChannelV0 = {
      ...MIN_IR,
      channels: {
        slack: MIN_IR.channels.slack,
        telegram: {
          botToken: { kind: "env", name: "TG_BOT_TOKEN" },
          secretToken: { kind: "env", name: "TG_SECRET_TOKEN" },
        },
      },
      gateway: { port: 19001, ui: false },
    };
    const c = fileMap(ir).get("daemon.ts") ?? "";
    expect(c).toContain('"slack"');
    expect(c).toContain('"telegram"');
  });

  test("gateway is cleanly stopped on shutdown", () => {
    const ir: IrChannelV0 = {
      ...MIN_IR,
      gateway: { port: 19001, ui: false },
    };
    const c = fileMap(ir).get("daemon.ts") ?? "";
    expect(c).toContain("__gatewayServer.stop(true)");
  });
});

describe("emitChannelBot — heartbeat (Phase 3 §3.1)", () => {
  test("omits heartbeat boot when ir.heartbeat is undefined", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).not.toContain("setInterval");
    expect(c).not.toContain("[heartbeat]");
    expect(c).not.toContain("__heartbeatTimer");
  });

  test("emits a setInterval loop and shutdown clearInterval when heartbeat is set", () => {
    const irWithHeartbeat: IrChannelV0 = {
      ...MIN_IR,
      heartbeat: {
        everyMs: 7_200_000, // 2h
        instructions: "Wake and decide what's useful.",
      },
    };
    const c = fileMap(irWithHeartbeat).get("daemon.ts") ?? "";
    expect(c).toContain("setInterval(");
    expect(c).toContain("7200000"); // 2h in ms
    expect(c).toContain('"Wake and decide what\'s useful."');
    expect(c).toContain("[heartbeat] tick");
    expect(c).toContain("clearInterval(__heartbeatTimer)");
    expect(c).toContain("import { randomBytes as __hbRandomBytes }");
    // The heartbeat fires the agent via the same runTurn surface as
    // inbound messages, so each tick gets a fresh session id.
    expect(c).toContain("agent.runTurn({");
    expect(c).toContain("isNew: true");
  });

  test("heartbeat coexists with sub-agents and MCP servers", () => {
    const ir: IrChannelV0 = {
      ...MIN_IR,
      subAgents: [
        {
          name: "planner",
          description: "plans things",
          instructions: "Plan, do not execute.",
          tools: ["read"],
          permissions: { allow: ["Read"], deny: [] },
          inheritBypass: false,
        },
      ],
      heartbeat: { everyMs: 60_000, instructions: "tick" },
    };
    const c = fileMap(ir).get("daemon.ts") ?? "";
    expect(c).toContain("setInterval(");
    expect(c).toContain("60000");
    expect(c).toContain("Sub-agents (Section 13)");
  });
});

describe("emitChannelBot — terminal-failure reporting (0.3.0 Goal 6)", () => {
  test("main().catch renders the structured report and exits with the coded status", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain('import { formatRunFailure, toFailureReport } from "@crewhaus/errors";');
    expect(c).toContain("const __report = toFailureReport(err);");
    expect(c).toContain(
      'process.stderr.write(`${formatRunFailure(__report, { prefix: "[daemon]" })}\\n`);',
    );
    expect(c).toContain("process.exit(__report.exitCode);");
    // The pre-0.3.0 bare fatal line is gone.
    expect(c).not.toContain("[daemon] fatal:");
    // Without a heartbeat, the tick-only helper is not imported.
    expect(c).not.toContain("isRunFailedError");
  });

  test("heartbeat tick renders the classified report but keeps the bare line for other errors — and never exits", () => {
    const irWithHeartbeat: IrChannelV0 = {
      ...MIN_IR,
      heartbeat: { everyMs: 60_000, instructions: "tick" },
    };
    const c = fileMap(irWithHeartbeat).get("daemon.ts") ?? "";
    expect(c).toContain(
      'import { formatRunFailure, isRunFailedError, toFailureReport } from "@crewhaus/errors";',
    );
    expect(c).toContain("if (isRunFailedError(__err)) {");
    expect(c).toContain(
      'process.stderr.write(`${formatRunFailure(__err.report, { prefix: "[heartbeat]" })}\\n`);',
    );
    // Unclassifiable tick errors keep the pre-0.3.0 bare line…
    expect(c).toContain("[heartbeat] error:");
    // …and the tick catch never kills the daemon: no process.exit between
    // the heartbeat catch and the end of the setInterval callback.
    const tickCatch = c.indexOf("if (isRunFailedError(__err)) {");
    const tickEnd = c.indexOf("[heartbeat] enabled every");
    expect(tickCatch).toBeGreaterThan(-1);
    expect(c.slice(tickCatch, tickEnd)).not.toContain("process.exit");
  });
});

describe("emitChannelBot — provider failover chain (item 22)", () => {
  test("agent.ts threads modelFallbacks + circuitBreaker into runChatLoop when set", () => {
    const irFailover: IrChannelV0 = {
      ...MIN_IR,
      agent: {
        ...MIN_IR.agent,
        modelFallbacks: ["openai/gpt-4o-mini"],
        circuitBreaker: { failureThreshold: 3, windowMs: 60000 },
      },
    };
    const agentTs =
      emitChannelBot(irFailover).files.find((f) => f.path === "agent.ts")?.content ?? "";
    expect(agentTs).toContain('modelFallbacks: ["openai/gpt-4o-mini"],');
    expect(agentTs).toContain('circuitBreaker: {"failureThreshold":3,"windowMs":60000},');
  });

  test("agent.ts omits both fields when the IR leaves them unset", () => {
    const agentTs = emitChannelBot(MIN_IR).files.find((f) => f.path === "agent.ts")?.content ?? "";
    expect(agentTs).not.toContain("modelFallbacks:");
    expect(agentTs).not.toContain("circuitBreaker:");
  });
});

describe("emitChannelBot — run-level budget field (item 27)", () => {
  test("agent.ts threads budget into runChatLoop when set", () => {
    const irBudget: IrChannelV0 = {
      ...MIN_IR,
      budget: { usdMicros: 2_000_000, onExceed: { kind: "stop" } },
    };
    const agentTs =
      emitChannelBot(irBudget).files.find((f) => f.path === "agent.ts")?.content ?? "";
    expect(agentTs).toContain('budget: {"usdMicros":2000000,"onExceed":{"kind":"stop"}},');
  });

  test("agent.ts omits budget when the IR leaves it unset", () => {
    const agentTs = emitChannelBot(MIN_IR).files.find((f) => f.path === "agent.ts")?.content ?? "";
    expect(agentTs).not.toContain("budget:");
  });
});

describe("emitChannelBot — dream janitor step (v0.3.0 PR 14, §6.3)", () => {
  const DREAM_IR: IrChannelV0 = {
    ...MIN_IR,
    memory: { dream: { everyMs: 86_400_000, mode: "full", budgetUsd: 0.5 } },
    continuity: {
      plan: true,
      proof: "ladder",
      ledger: true,
      handoff: true,
      scope: "session",
    },
  };

  test("agent.ts exports createDreamStep with the runChatLoop model phase", () => {
    const agent = fileMap(DREAM_IR).get("agent.ts") ?? "";
    expect(agent).toContain("export function createDreamStep(): DreamJanitorStep | null");
    expect(agent).toContain(
      'import { wireMemory, type MemoryWiringFragment, createDreamJanitorStep, type DreamJanitorStep } from "@crewhaus/memory-service";',
    );
    expect(agent).toContain('import { createCostTracker } from "@crewhaus/cost-tracker";');
    // The bounded fresh session (§6.2): dream target, single turn, capped
    // tool loop, the item-27 budget option fed from the seam input.
    expect(agent).toContain('sessionTarget: "dream"');
    expect(agent).toContain("maxToolIterations: input.maxToolIterations");
    expect(agent).toContain("usdMicros: Math.round(input.budgetUsd * 1_000_000)");
    expect(agent).toContain('onExceed: { kind: "stop" }');
  });

  test("the dream fragment is SPEC-scoped even when interactive continuity is session-scoped", () => {
    const agent = fileMap(DREAM_IR).get("agent.ts") ?? "";
    const match = agent.match(/const __DREAM_FRAGMENT: MemoryWiringFragment = (\{.*?\});\n/);
    expect(match).not.toBeNull();
    const fragment = JSON.parse(match?.[1] ?? "{}") as {
      memory?: { dream?: { everyMs: number } };
      continuity?: { scope?: string };
    };
    expect(fragment.memory?.dream?.everyMs).toBe(86_400_000);
    expect(fragment.continuity?.scope).toBe("spec");
  });

  test("daemon.ts registers the step into createJanitor({ steps })", () => {
    const daemon = fileMap(DREAM_IR).get("daemon.ts") ?? "";
    expect(daemon).toContain('import { createAgent, createDreamStep } from "./agent.js";');
    expect(daemon).toContain("const __dreamStep = createDreamStep();");
    expect(daemon).toContain("steps: __dreamStep !== null ? [__dreamStep] : [],");
  });

  test("no dream schedule → zero dream codegen (byte-identity guard)", () => {
    const files = fileMap({ ...MIN_IR, memory: { autoRecall: true } });
    for (const path of ["agent.ts", "daemon.ts"]) {
      const content = files.get(path) ?? "";
      expect(content).not.toContain("createDreamStep");
      expect(content).not.toContain("__DREAM_FRAGMENT");
      expect(content).not.toContain("steps:");
    }
  });
});
