import { describe, expect, test } from "bun:test";
import type { IrChannelV0 } from "@crewhaus/ir";
import { TargetEmitError, emitChannelBot } from "./index";

const MIN_IR: IrChannelV0 = {
  version: 0,
  name: "demo",
  target: "channel",
  agent: { model: "claude-sonnet-4-6", instructions: "be helpful" },
  tools: [],
  channels: {
    slack: {
      botToken: { kind: "env", name: "SLACK_BOT_TOKEN" },
      signingSecret: { kind: "env", name: "SLACK_SIGNING_SECRET" },
    },
  },
  routing: { sessionKey: "thread" },
  mcp_servers: {},
  permissions: { rules: [] },
};

const fileMap = (ir: IrChannelV0): Map<string, string> =>
  new Map(emitChannelBot(ir).files.map((f) => [f.path, f.content]));

describe("emitChannelBot — bundle structure (T1)", () => {
  test("emits exactly four files: agent.ts, session-router.ts, gateway.ts, daemon.ts", () => {
    const bundle = emitChannelBot(MIN_IR);
    const paths = bundle.files.map((f) => f.path).sort();
    expect(paths).toEqual(["agent.ts", "daemon.ts", "gateway.ts", "session-router.ts"]);
  });

  test("each file starts with the generated marker", () => {
    const bundle = emitChannelBot(MIN_IR);
    for (const f of bundle.files) {
      expect(f.content).toContain("Generated by crewhaus-factory. DO NOT EDIT.");
    }
  });

  test("daemon.ts has a shebang; non-entrypoint files do not", () => {
    const files = fileMap(MIN_IR);
    expect(files.get("daemon.ts")?.startsWith("#!/usr/bin/env bun")).toBe(true);
    expect(files.get("agent.ts")?.startsWith("#!")).toBe(false);
    expect(files.get("gateway.ts")?.startsWith("#!")).toBe(false);
    expect(files.get("session-router.ts")?.startsWith("#!")).toBe(false);
  });
});

describe("emitChannelBot — daemon.ts wiring", () => {
  test("imports the channel-generic gateway, session-router, and agent", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain('import { createAgent } from "./agent.js";');
    expect(c).toContain('import { createSessionRouter } from "./session-router.js";');
    expect(c).toContain('import { createGateway } from "./gateway.js";');
  });

  test("starts a Bun.serve and registers SIGINT/SIGTERM shutdown", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain("Bun.serve({");
    expect(c).toContain('process.on("SIGINT"');
    expect(c).toContain('process.on("SIGTERM"');
    expect(c).toContain("server.stop(true)");
  });

  test("constructs createSlackAdapter with the configured secret references", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain("createSlackAdapter({");
    expect(c).toContain('process.env["SLACK_BOT_TOKEN"]');
    expect(c).toContain('process.env["SLACK_SIGNING_SECRET"]');
    expect(c).toContain('registerChannelAdapter("slack", slackAdapter);');
  });

  test("emits a startup-time check that exits non-zero when env vars are unset", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain('"SLACK_BOT_TOKEN"');
    expect(c).toContain('"SLACK_SIGNING_SECRET"');
    expect(c).toContain("process.exit(2)");
    expect(c).toContain("missing required env vars");
  });

  test("literal secret values are embedded verbatim and skip the env-check", () => {
    const irLit: IrChannelV0 = {
      ...MIN_IR,
      channels: {
        slack: {
          botToken: { kind: "literal", value: "xoxb-literal" },
          signingSecret: { kind: "literal", value: "literal-signing" },
        },
      },
    };
    const c = fileMap(irLit).get("daemon.ts") ?? "";
    expect(c).toContain('"xoxb-literal"');
    expect(c).toContain('"literal-signing"');
    // No env-check block when there are no env-refs.
    expect(c).not.toContain("missing required env vars");
  });

  test("loads hooks/skills/slash-commands like the cli target", () => {
    const c = fileMap(MIN_IR).get("daemon.ts") ?? "";
    expect(c).toContain('import { loadHooks } from "@crewhaus/hooks-engine";');
    expect(c).toContain("discoverSkills({ cwd: __cwd })");
    expect(c).toContain("loadCommands({ cwd: __cwd })");
    expect(c).toContain("createSkillTool(__skills)");
  });

  test("registers ir.tools on defaultCatalog when non-empty", () => {
    const irTools: IrChannelV0 = {
      ...MIN_IR,
      tools: ["read", "bash", "sendMessage"],
    };
    const c = fileMap(irTools).get("daemon.ts") ?? "";
    expect(c).toContain('import { read } from "@crewhaus/tool-fs";');
    expect(c).toContain('import { bash } from "@crewhaus/tool-bash";');
    expect(c).toContain('import { sendMessage } from "@crewhaus/tool-message-channel";');
    expect(c).toContain("defaultCatalog.register(read);");
    expect(c).toContain("defaultCatalog.register(bash);");
    expect(c).toContain("defaultCatalog.register(sendMessage);");
  });

  test("rejects unknown tool names", () => {
    const irBad: IrChannelV0 = { ...MIN_IR, tools: ["nonexistent"] };
    expect(() => emitChannelBot(irBad)).toThrow(TargetEmitError);
    expect(() => emitChannelBot(irBad)).toThrow(/unknown tool/);
  });

  test("emits MCP boot block when mcp_servers is non-empty", () => {
    const irMcp: IrChannelV0 = {
      ...MIN_IR,
      mcp_servers: {
        fs: { transport: "stdio", command: "npx", args: ["-y", "fs-server"] },
      },
    };
    const c = fileMap(irMcp).get("daemon.ts") ?? "";
    expect(c).toContain("new McpHost();");
    expect(c).toContain('mcpHost.addServer("fs"');
    expect(c).toContain("mcpHost.disconnectAll()");
  });
});

describe("emitChannelBot — session-router.ts", () => {
  test("derives sess_<16hex> ids via sha256 of the routing key", () => {
    const c = fileMap(MIN_IR).get("session-router.ts") ?? "";
    expect(c).toContain('createHash("sha256")');
    expect(c).toContain('"sess_" +');
    expect(c).toContain(".slice(0, 16)");
  });

  test("threadKey strategy keys by workspace + channel + thread", () => {
    const c = fileMap(MIN_IR).get("session-router.ts") ?? "";
    expect(c).toContain("event.threadTs ?? event.ts");
    expect(c).toContain("event.workspaceId");
    expect(c).toContain("event.channelId");
  });

  test("user strategy keys by workspace + user only", () => {
    const irUser: IrChannelV0 = { ...MIN_IR, routing: { sessionKey: "user" } };
    const c = fileMap(irUser).get("session-router.ts") ?? "";
    expect(c).toContain("event.userId");
    expect(c).not.toContain("event.threadTs");
  });

  test("channel strategy keys by workspace + channel only", () => {
    const irCh: IrChannelV0 = { ...MIN_IR, routing: { sessionKey: "channel" } };
    const c = fileMap(irCh).get("session-router.ts") ?? "";
    expect(c).toContain("event.channelId");
    expect(c).not.toContain("event.threadTs");
    expect(c).not.toContain("event.userId");
  });

  test("creates a fresh session on first inbound and resumes after that", () => {
    const c = fileMap(MIN_IR).get("session-router.ts") ?? "";
    expect(c).toContain("sessionStore.get(sessionId)");
    expect(c).toContain("sessionStore.create({");
    expect(c).toContain("isNew");
  });
});

describe("emitChannelBot — agent.ts", () => {
  test("uses singleTurn + resume for non-new turns and just singleTurn for first turn", () => {
    const c = fileMap(MIN_IR).get("agent.ts") ?? "";
    expect(c).toContain("singleTurn: true");
    expect(c).toContain("resume: { sessionId: args.sessionId }");
    expect(c).toContain('seedMessages: [{ role: "user", content: args.message }]');
    expect(c).toContain('sessionTarget: "channel"');
    expect(c).toContain('sessionName: "demo"');
  });

  test("threads model + instructions + permissions from the IR", () => {
    const irPerm: IrChannelV0 = {
      ...MIN_IR,
      permissions: {
        mode: "auto",
        rules: [{ type: "alwaysAllow", pattern: "Read" }],
      },
    };
    const c = fileMap(irPerm).get("agent.ts") ?? "";
    expect(c).toContain('"claude-sonnet-4-6"');
    expect(c).toContain('"be helpful"');
    expect(c).toContain('permissionMode: "auto"');
    expect(c).toContain('pattern: "Read"');
    expect(c).toContain("BUILTIN_DEFAULT_RULES");
  });
});

describe("emitChannelBot — gateway.ts", () => {
  test("dedups by adapter-supplied idempotencyKey", () => {
    const c = fileMap(MIN_IR).get("gateway.ts") ?? "";
    expect(c).toContain("idempotencyKey");
    expect(c).toContain("dedup");
  });

  test("returns 401 on signature mismatch", () => {
    const c = fileMap(MIN_IR).get("gateway.ts") ?? "";
    expect(c).toContain("status: 401");
    expect(c).toContain("invalid signature");
  });

  test("handles url_verification challenge with a plaintext body", () => {
    const c = fileMap(MIN_IR).get("gateway.ts") ?? "";
    expect(c).toContain('"text/plain"');
    expect(c).toContain("parsed.challenge");
  });

  test("matches /<adapter>/events path prefix", () => {
    const c = fileMap(MIN_IR).get("gateway.ts") ?? "";
    // The generated regex literal is /^\/([^/]+)\/events$/ — match the
    // /events$ tail to confirm the routing pattern is in place.
    expect(c).toContain("/events$/");
  });
});

describe("emitChannelBot — error cases", () => {
  test("throws TargetEmitError when the channels block has no slack config", () => {
    const irNoSlack: IrChannelV0 = {
      ...MIN_IR,
      channels: {},
    };
    expect(() => emitChannelBot(irNoSlack)).toThrow(TargetEmitError);
  });
});
