import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { IrV0 } from "@crewhaus/ir";
import { type MemoryWiringFragment, wireMemory } from "@crewhaus/memory-service";
import type { RegisteredTool } from "@crewhaus/tool-catalog";
import { TargetEmitError, emitCli } from "./index";

function baseIr(overrides: Partial<IrV0> = {}): IrV0 {
  return {
    version: 0,
    name: "smoke",
    target: "cli",
    agent: { model: "claude-sonnet-4-6", instructions: "be helpful" },
    tools: [],
    toolConfigs: {},
    mcp_servers: {},
    permissions: { rules: [] },
    subAgents: [],
    compaction: {},
    ...overrides,
  };
}

describe("emitCli — bundle shape", () => {
  test("returns agent.ts plus the generated README.md (item 42)", () => {
    const bundle = emitCli(baseIr());
    expect(bundle.files.length).toBe(2);
    expect(bundle.files[0]?.path).toBe("agent.ts");
    expect(bundle.files[1]?.path).toBe("README.md");
  });

  test("the emitted file starts with a bun shebang and DO NOT EDIT marker", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content.startsWith("#!/usr/bin/env bun")).toBe(true);
    expect(content).toContain("Generated by crewhaus. DO NOT EDIT.");
  });

  test("the IR name is embedded in the source-spec comment", () => {
    const content = emitCli(baseIr({ name: "my-bot" })).files[0]?.content ?? "";
    expect(content).toContain('Source spec: "my-bot"');
  });

  test("a newline in the spec name cannot break out of the source-spec comment (#147)", () => {
    const evil = "evil\nglobalThis.__PWNED__ = 1";
    const content = emitCli(baseIr({ name: evil })).files[0]?.content ?? "";
    const header = content.split("\n").find((l) => l.includes("Source spec:")) ?? "";
    expect(header).toContain("\\n"); // the newline is escaped inside the comment
    expect(content).not.toContain("\nglobalThis.__PWNED__ = 1"); // never emitted as live code
  });

  test("the model and instructions are escaped + embedded in the runChatLoop call", () => {
    const content =
      emitCli(
        baseIr({
          agent: { model: "claude-sonnet-4-6", instructions: 'said "hi"\nthen "bye"' },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('model: "claude-sonnet-4-6"');
    // double quotes inside the instruction must be escaped — proves escapeJsonString ran
    expect(content).toContain('said \\"hi\\"');
    expect(content).toContain('then \\"bye\\"');
  });

  test("sessionName defaults to the IR name and sessionTarget is cli", () => {
    const content = emitCli(baseIr({ name: "my-bot" })).files[0]?.content ?? "";
    expect(content).toContain('sessionName: "my-bot"');
    expect(content).toContain('sessionTarget: "cli"');
  });

  test("compaction.model is threaded into runChatLoop as compactionModel (escaped)", () => {
    const content =
      emitCli(baseIr({ compaction: { model: "claude-haiku-4-5-20251001" } })).files[0]?.content ??
      "";
    expect(content).toContain('compactionModel: "claude-haiku-4-5-20251001"');
  });

  test("no compaction.model → no compactionModel field emitted (bundles stay byte-identical)", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("compactionModel:");
  });
});

describe("emitCli — tool wiring (Section 2)", () => {
  test("an empty tools list emits no tool imports but still imports defaultCatalog", () => {
    const content = emitCli(baseIr({ tools: [] })).files[0]?.content ?? "";
    // Section 11 parity: defaultCatalog import is unconditional now
    expect(content).toContain('from "@crewhaus/tool-catalog"');
    expect(content).not.toContain("@crewhaus/tool-fs");
    expect(content).not.toContain("@crewhaus/tool-bash");
    // tools field is always defaultCatalog.list()
    expect(content).toContain("tools: defaultCatalog.list()");
  });

  test("a single tool emits one import + one register call", () => {
    const content = emitCli(baseIr({ tools: ["read"] })).files[0]?.content ?? "";
    expect(content).toContain('import { read } from "@crewhaus/tool-fs"');
    expect(content).toContain("defaultCatalog.register(read);");
  });

  test("multiple tools from the same package are grouped into one import", () => {
    const content = emitCli(baseIr({ tools: ["read", "write", "edit"] })).files[0]?.content ?? "";
    // single import line covering all three exports
    expect(content).toMatch(/import \{ edit, read, write \} from "@crewhaus\/tool-fs"/);
    // three separate register calls
    expect(content).toContain("defaultCatalog.register(read);");
    expect(content).toContain("defaultCatalog.register(write);");
    expect(content).toContain("defaultCatalog.register(edit);");
  });

  test("tools across multiple packages each get their own grouped import", () => {
    const content =
      emitCli(baseIr({ tools: ["read", "bash", "todoWrite"] })).files[0]?.content ?? "";
    expect(content).toContain('import { bash } from "@crewhaus/tool-bash"');
    expect(content).toContain('import { read } from "@crewhaus/tool-fs"');
    expect(content).toContain('import { todoWrite } from "@crewhaus/tool-todo"');
  });

  test("an unknown tool name throws TargetEmitError listing known names", () => {
    expect(() => emitCli(baseIr({ tools: ["unknownTool"] }))).toThrow(TargetEmitError);
    try {
      emitCli(baseIr({ tools: ["unknownTool"] }));
    } catch (e) {
      expect(e).toBeInstanceOf(TargetEmitError);
      expect((e as Error).message).toContain('unknown tool "unknownTool"');
      expect((e as Error).message).toContain("known tools:");
      // proves the error is helpful — names a real builtin
      expect((e as Error).message).toContain("read");
    }
  });
});

describe("emitCli — terminal-failure catch wrapper (0.3.0 Goal 6)", () => {
  test("the top-level runChatLoop is wrapped in a catch that renders the report and exits coded", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    // The bare `await runChatLoop(...)` (the "agent exited" unhandled-stack
    // path) is gone: every bundle catches, renders formatRunFailure, and
    // exits with the report's coded status.
    expect(content).toContain(
      'import { formatRunFailure, toFailureReport } from "@crewhaus/errors";',
    );
    const tryIdx = content.indexOf("try {");
    const runChatLoopIdx = content.indexOf("await runChatLoop({");
    const catchIdx = content.indexOf("} catch (__err) {");
    expect(tryIdx).toBeGreaterThanOrEqual(0);
    expect(runChatLoopIdx).toBeGreaterThan(tryIdx);
    expect(catchIdx).toBeGreaterThan(runChatLoopIdx);
    expect(content).toContain("const __report = toFailureReport(__err);");
    expect(content).toContain("process.stderr.write(`${formatRunFailure(__report)}\\n`);");
    expect(content).toContain("process.exit(__report.exitCode);");
    // No MCP → no finally block.
    expect(content).not.toContain("} finally {");
  });

  test("with MCP servers the catch precedes the cleanup finally", () => {
    const content =
      emitCli(
        baseIr({
          mcp_servers: {
            things: { transport: "stdio", command: "node", args: ["server.js"] },
          },
        }),
      ).files[0]?.content ?? "";
    const catchIdx = content.indexOf("} catch (__err) {");
    const finallyIdx = content.indexOf("} finally {");
    expect(catchIdx).toBeGreaterThanOrEqual(0);
    expect(finallyIdx).toBeGreaterThan(catchIdx);
    expect(content).toContain("await mcpHost.disconnectAll();");
  });
});

describe("emitCli — permissions (Section 7)", () => {
  test("no rules and no mode → no permissionMode or permissionRules emitted", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("permissionMode");
    expect(content).not.toContain("permissionRules");
    // and no permission-engine import
    expect(content).not.toContain("@crewhaus/permission-engine");
  });

  test("a permission mode without rules emits permissionMode only", () => {
    const content =
      emitCli(baseIr({ permissions: { mode: "plan", rules: [] } })).files[0]?.content ?? "";
    expect(content).toContain('permissionMode: "plan"');
    expect(content).not.toContain("permissionRules:");
  });

  test("permission rules emit a layered rules object with builtin defaults", () => {
    const content =
      emitCli(
        baseIr({
          permissions: {
            mode: "default",
            rules: [
              { type: "alwaysAllow", pattern: "Read" },
              { type: "alwaysDeny", pattern: "Bash(rm *)" },
            ],
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain(
      'import { BUILTIN_DEFAULT_RULES } from "@crewhaus/permission-engine"',
    );
    expect(content).toContain("permissionRules: {");
    expect(content).toContain("yaml: [");
    expect(content).toContain('type: "alwaysAllow"');
    expect(content).toContain('pattern: "Read"');
    expect(content).toContain('pattern: "Bash(rm *)"');
    expect(content).toContain('source: "yaml"');
    expect(content).toContain("builtin: BUILTIN_DEFAULT_RULES");
  });
});

describe("emitCli — MCP servers (Section 9)", () => {
  test("empty mcp_servers → no McpHost import or boot block", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/mcp-host");
    expect(content).not.toContain("new McpHost()");
    expect(content).not.toContain("disconnectAll");
  });

  test("a stdio MCP server emits boot + cleanup blocks", () => {
    const content =
      emitCli(
        baseIr({
          mcp_servers: {
            everything: {
              transport: "stdio",
              command: "npx",
              args: ["-y", "@modelcontextprotocol/server-everything"],
            },
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain(
      'import { McpHost, resolveMcpServerConfig } from "@crewhaus/mcp-host"',
    );
    expect(content).toContain('import { registerMcpServer } from "@crewhaus/tool-mcp"');
    expect(content).toContain("const mcpHost = new McpHost();");
    expect(content).toContain('mcpHost.addServer("everything"');
    expect(content).toContain("await Promise.all([");
    expect(content).toContain("registerMcpServer(mcpHost,");
    // the runChatLoop call is wrapped in try/finally so disconnectAll always runs
    expect(content).toContain("try {");
    expect(content).toContain("} finally {");
    expect(content).toContain("await mcpHost.disconnectAll();");
  });

  test("0.3.0 — env secret refs are embedded UNRESOLVED and resolved at boot", () => {
    const content =
      emitCli(
        baseIr({
          mcp_servers: {
            thredz: {
              transport: "stdio",
              command: "npx",
              args: ["-y", "thredz-mcp@0.2.0"],
              env: {
                THREDZ_API_KEY: { kind: "env", name: "THREDZ_API_KEY" },
                THREDZ_BASE_URL: { kind: "literal", value: "https://thredz.example/api" },
              },
            },
          },
        }),
      ).files[0]?.content ?? "";
    // The unresolved IrSecretRef JSON is embedded — never a resolved value —
    // and the boot line materialises it via resolveMcpServerConfig.
    expect(content).toContain('{"kind":"env","name":"THREDZ_API_KEY"}');
    expect(content).toContain(
      'mcpHost.addServer("thredz", resolveMcpServerConfig({"transport":"stdio","command":"npx","args":["-y","thredz-mcp@0.2.0"],"env":{"THREDZ_API_KEY":{"kind":"env","name":"THREDZ_API_KEY"},"THREDZ_BASE_URL":{"kind":"literal","value":"https://thredz.example/api"}}}, { name: "thredz" }));',
    );
  });
});

describe("emitCli — extension surface (Section 11)", () => {
  test("hooks/skills/slashCommands imports + boot are emitted unconditionally", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).toContain('import { loadHooks } from "@crewhaus/hooks-engine"');
    expect(content).toContain(
      'import { discoverSkills, createSkillTool } from "@crewhaus/skills-registry"',
    );
    expect(content).toContain('import { loadCommands } from "@crewhaus/slash-commands"');
    expect(content).toContain("const __cwd = process.cwd();");
    expect(content).toContain("loadHooks({ cwd: __cwd })");
    expect(content).toContain("discoverSkills({ cwd: __cwd })");
    expect(content).toContain("loadCommands({ cwd: __cwd })");
    expect(content).toContain("hooks: __hooks");
    expect(content).toContain("skills: __skills");
    expect(content).toContain("slashCommands: __slashCommands");
    // skill-tool registration is conditional on discovery returning entries
    expect(content).toContain(
      "if (__skills.length > 0) defaultCatalog.register(createSkillTool(__skills));",
    );
  });
});

describe("emitCli — sub-agents (Section 13)", () => {
  test("empty subAgents is a no-op (regression: pre-Section-13 shape preserved)", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/tool-task");
    expect(content).not.toContain("@crewhaus/sub-agent-spawner");
    expect(content).not.toContain("__subAgents");
    expect(content).not.toContain("spawnSubAgent");
  });

  test("non-empty subAgents emits imports, registry, Task tool registration, and runChatLoop wiring", () => {
    const content =
      emitCli(
        baseIr({
          subAgents: [
            {
              name: "summarizer",
              description: "summarize text",
              instructions: "Summarize input in 2 sentences.",
              tools: [],
              permissions: "scoped",
              inheritBypass: false,
            },
          ],
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('import { createTaskTool } from "@crewhaus/tool-task"');
    expect(content).toContain('import { spawnSubAgent } from "@crewhaus/sub-agent-spawner"');
    expect(content).toContain('SubAgentDefinition } from "@crewhaus/agent-context-isolation"');
    expect(content).toContain("__subAgents");
    expect(content).toContain('"summarizer"');
    expect(content).toContain('description: "summarize text"');
    expect(content).toContain('permissions: "scoped"');
    expect(content).toContain("inherit_bypass: false");
    expect(content).toContain("createTaskTool({ subAgents: __subAgents })");
    expect(content).toContain("subAgents: __subAgents");
    expect(content).toContain("spawnSubAgent,");
  });

  test("replace-style permissions render as { allow, deny }", () => {
    const content =
      emitCli(
        baseIr({
          subAgents: [
            {
              name: "rep",
              description: "x",
              instructions: "y",
              tools: ["read"],
              permissions: { allow: ["Read", "Glob"], deny: ["Bash(**)"] },
              inheritBypass: false,
            },
          ],
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('allow: ["Read","Glob"]');
    expect(content).toContain('deny: ["Bash(**)"]');
  });
});

describe("emitCli — combined", () => {
  test("everything-on emits all four extension blocks in the right order", () => {
    const content =
      emitCli(
        baseIr({
          tools: ["read", "bash"],
          mcp_servers: {
            things: { transport: "stdio", command: "node", args: ["server.js"] },
          },
          permissions: {
            mode: "default",
            rules: [{ type: "alwaysAllow", pattern: "Read" }],
          },
        }),
      ).files[0]?.content ?? "";
    // imports come before boot blocks; boot blocks before the runChatLoop call
    const importsIdx = content.indexOf('from "@crewhaus/runtime-core"');
    const mcpBootIdx = content.indexOf("new McpHost()");
    const extensionBootIdx = content.indexOf("Promise.all([\n  loadHooks");
    const runChatLoopIdx = content.indexOf("await runChatLoop({");
    expect(importsIdx).toBeGreaterThanOrEqual(0);
    expect(mcpBootIdx).toBeGreaterThan(importsIdx);
    expect(extensionBootIdx).toBeGreaterThan(importsIdx);
    expect(runChatLoopIdx).toBeGreaterThan(mcpBootIdx);
    expect(runChatLoopIdx).toBeGreaterThan(extensionBootIdx);
  });
});

describe("emitCli — CLI banner (Phase 3 §3.3)", () => {
  test("omits banner code when ir.cli.banner is undefined", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("CREWHAUS_RESUMED");
    expect(content).not.toContain("__tagline");
  });

  test("emits a static-mode banner that prints the first tagline", () => {
    const ir = baseIr({
      cli: {
        banner: {
          taglineMode: "static",
          taglines: ["🦞 EXFOLIATE! EXFOLIATE!", "🦞 second tagline"],
        },
      },
    });
    const content = emitCli(ir).files[0]?.content ?? "";
    expect(content).toContain("🦞 EXFOLIATE! EXFOLIATE!");
    expect(content).toContain("__taglines[0]");
    expect(content).not.toContain("Math.random()");
    // Resumed-session suppression
    expect(content).toContain("CREWHAUS_RESUMED");
  });

  test("emits a random-mode banner that picks via Math.random()", () => {
    const ir = baseIr({
      cli: {
        banner: {
          taglineMode: "random",
          taglines: ["one", "two", "three"],
        },
      },
    });
    const content = emitCli(ir).files[0]?.content ?? "";
    expect(content).toContain("Math.floor(Math.random()");
    expect(content).toContain('"one"');
    expect(content).toContain('"two"');
    expect(content).toContain('"three"');
  });

  test("name is escaped against backtick/template injection inside the banner", () => {
    const ir = baseIr({
      name: "evil`${process.exit(1)}",
      cli: {
        banner: { taglineMode: "static", taglines: ["t"] },
      },
    });
    const content = emitCli(ir).files[0]?.content ?? "";
    // The banner emits inside a backtick template literal. Backticks and ${
    // in the name must be escaped so they can't break out of the template
    // and run arbitrary code at startup.
    expect(content).toContain("evil\\`\\${process.exit(1)}");
    // The escaped form should appear specifically in the banner body
    // (after the "process.stdout.write" call introducing the banner).
    const writeIdx = content.indexOf("process.stdout.write(`\\n");
    const escapedIdx = content.indexOf("evil\\`\\${process.exit(1)}");
    expect(escapedIdx).toBeGreaterThan(writeIdx);
  });
});

describe("emitCli — egress matcher (Pillar 3 sink-side, FR-006)", () => {
  test("no security block → no egress-matcher wiring (substring default, zero embedding deps)", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    // The default artifact must not pull in the semantic package or the
    // embedder — the optional-dependency posture (acceptance #4) holds.
    expect(content).not.toContain("@crewhaus/egress-matcher-semantic");
    expect(content).not.toContain("@crewhaus/embedder");
    expect(content).not.toContain("egressMatcher:");
    expect(content).not.toContain("createSemanticEgressMatcher");
    expect(content).not.toContain("__egressMatcher");
  });

  test('egressMatcher: "substring" emits nothing (explicit default is still the bare bundle)', () => {
    const content =
      emitCli(baseIr({ security: { egressMatcher: "substring" } })).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/egress-matcher-semantic");
    expect(content).not.toContain("@crewhaus/embedder");
    expect(content).not.toContain("egressMatcher:");
    expect(content).not.toContain("__egressMatcher");
  });

  test("security with only justification (no egressMatcher) emits no egress wiring", () => {
    // Presence of the security block alone must not trigger emission — only
    // egressMatcher: "semantic" does.
    const content =
      emitCli(baseIr({ security: { justification: { judge: "claude" } } })).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/egress-matcher-semantic");
    expect(content).not.toContain("egressMatcher:");
  });

  test('egressMatcher: "semantic" emits imports, embedder+matcher construction, and the runChatLoop field', () => {
    const content =
      emitCli(baseIr({ security: { egressMatcher: "semantic" } })).files[0]?.content ?? "";
    // Imports for the optional embedding-backed matcher + the embedder.
    expect(content).toContain('import { createEmbedder } from "@crewhaus/embedder"');
    expect(content).toContain(
      'import { createSemanticEgressMatcher } from "@crewhaus/egress-matcher-semantic"',
    );
    // Embedder model resolved at bundle runtime: env override > documented
    // default — the standalone analogue of the run path's resolution.
    expect(content).toContain("process.env.CREWHAUS_EGRESS_EMBEDDER");
    expect(content).toContain('"openai/text-embedding-3-small"');
    // The matcher is constructed with the injected embedder…
    expect(content).toContain("createSemanticEgressMatcher({ embedder: __egressEmbedder })");
    // …and threaded into runChatLoop, mirroring the run path.
    expect(content).toContain("egressMatcher: __egressMatcher");
  });

  test("semantic: the matcher is constructed BEFORE runChatLoop (so the field references a bound symbol)", () => {
    const content =
      emitCli(baseIr({ security: { egressMatcher: "semantic" } })).files[0]?.content ?? "";
    const constructIdx = content.indexOf("const __egressMatcher =");
    const runChatLoopIdx = content.indexOf("await runChatLoop({");
    expect(constructIdx).toBeGreaterThanOrEqual(0);
    expect(runChatLoopIdx).toBeGreaterThan(constructIdx);
  });

  test("semantic + MCP: egress construction sits ahead of the mcp try/finally wrapper", () => {
    // When MCP is present the runChatLoop call is wrapped in try/finally and
    // re-indented; the egress matcher construction must still precede it.
    const content =
      emitCli(
        baseIr({
          security: { egressMatcher: "semantic" },
          mcp_servers: {
            things: { transport: "stdio", command: "node", args: ["server.js"] },
          },
        }),
      ).files[0]?.content ?? "";
    const constructIdx = content.indexOf("const __egressMatcher =");
    const tryIdx = content.indexOf("try {");
    expect(constructIdx).toBeGreaterThanOrEqual(0);
    expect(tryIdx).toBeGreaterThan(constructIdx);
    // And the field is still threaded into the (wrapped) runChatLoop options.
    expect(content).toContain("egressMatcher: __egressMatcher");
  });
});

describe("emitCli — agent.maxTokens (max output tokens)", () => {
  test("emits maxTokens in the runChatLoop call when the IR sets it", () => {
    const content =
      emitCli(
        baseIr({
          agent: { model: "claude-sonnet-4-6", instructions: "be helpful", maxTokens: 16384 },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain("maxTokens: 16384,");
  });

  test("omits maxTokens entirely when the IR leaves it unset", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("maxTokens:");
  });
});

describe("emitCli — generated README.md (item 42)", () => {
  const readmeOf = (ir: IrV0, opts?: { readme?: boolean }): string | undefined =>
    emitCli(ir, opts).files.find((f) => f.path === "README.md")?.content;

  test("README.md lands in the emitted bundle with harness metadata and the run snippet", () => {
    const md = readmeOf(baseIr({ name: "my-bot" })) ?? "";
    expect(md).toContain("# my-bot");
    expect(md).toContain("| Target | `cli` |");
    expect(md).toContain("| Model | `claude-sonnet-4-6` |");
    expect(md).toContain("bun agent.ts");
    expect(md).toContain(".crewhaus/sessions");
  });

  test("README documents the tools and the env vars the bundle needs", () => {
    const md =
      readmeOf(
        baseIr({
          tools: ["bash", "python"],
          chains: [
            {
              id: "mainnet",
              kind: "evm",
              rpcUrls: [{ kind: "env", name: "ALCHEMY_URL" }],
              rpcPolicy: "single",
              finality: { kind: "safe" },
              reorgTolerant: false,
            },
          ],
        }),
      ) ?? "";
    expect(md).toContain("| `bash` |");
    expect(md).toContain("| `python` |");
    expect(md).toContain("- `ALCHEMY_URL`");
  });

  test("README never leaks a literal secret value", () => {
    const md =
      readmeOf(
        baseIr({
          chains: [
            {
              id: "mainnet",
              kind: "evm",
              rpcUrls: [{ kind: "literal", value: "https://rpc.example.com/key/hunter2" }],
              rpcPolicy: "single",
              finality: { kind: "safe" },
              reorgTolerant: false,
            },
          ],
        }),
      ) ?? "";
    expect(md).not.toContain("hunter2");
  });

  test("readme: false opts out and restores the single-file bundle", () => {
    const bundle = emitCli(baseIr(), { readme: false });
    expect(bundle.files.length).toBe(1);
    expect(bundle.files[0]?.path).toBe("agent.ts");
  });
});

describe("emitCli — provider failover chain (item 22)", () => {
  test("emits modelFallbacks + circuitBreaker in the runChatLoop call when the IR sets them", () => {
    const content =
      emitCli(
        baseIr({
          agent: {
            model: "claude-sonnet-4-6",
            instructions: "be helpful",
            modelFallbacks: ["openai/gpt-4o-mini", "groq/llama-3.3-70b"],
            circuitBreaker: { failureThreshold: 3, cooldownMs: 15000 },
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('modelFallbacks: ["openai/gpt-4o-mini", "groq/llama-3.3-70b"],');
    expect(content).toContain('circuitBreaker: {"failureThreshold":3,"cooldownMs":15000},');
  });

  test("emits circuitBreaker alone when no fallbacks are declared (single-adapter breaker)", () => {
    const content =
      emitCli(
        baseIr({
          agent: {
            model: "claude-sonnet-4-6",
            instructions: "be helpful",
            circuitBreaker: { failureThreshold: 2 },
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).not.toContain("modelFallbacks:");
    expect(content).toContain('circuitBreaker: {"failureThreshold":2},');
  });

  test("omits both fields entirely when the IR leaves them unset", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("modelFallbacks:");
    expect(content).not.toContain("circuitBreaker:");
  });
});

describe("emitCli — failureTaxonomy field (item 23)", () => {
  test("emits failureTaxonomy in the runChatLoop call when the IR sets it", () => {
    const content =
      emitCli(
        baseIr({
          failureTaxonomy: [
            { class: "provider_overloaded", pattern: "/overloaded/i", recovery: "switch-model" },
            { class: "net", pattern: "ETIMEDOUT", recovery: "retry", hint: "back off" },
          ],
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain("failureTaxonomy:");
    expect(content).toContain('"recovery":"switch-model"');
    expect(content).toContain('"pattern":"ETIMEDOUT"');
  });

  test("omits failureTaxonomy when the IR leaves it unset or empty", () => {
    expect(emitCli(baseIr()).files[0]?.content ?? "").not.toContain("failureTaxonomy:");
    expect(emitCli(baseIr({ failureTaxonomy: [] })).files[0]?.content ?? "").not.toContain(
      "failureTaxonomy:",
    );
  });
});

describe("emitCli — run-level budget field (item 27)", () => {
  test("emits budget in the runChatLoop call when the IR sets it", () => {
    const content =
      emitCli(
        baseIr({
          budget: {
            usdMicros: 5_000_000,
            onExceed: { kind: "degrade", model: "claude-haiku-4-5" },
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('budget: {"usdMicros":5000000');
    expect(content).toContain('"kind":"degrade"');
    expect(content).toContain('"model":"claude-haiku-4-5"');
  });

  test("omits budget when the IR leaves it unset", () => {
    expect(emitCli(baseIr()).files[0]?.content ?? "").not.toContain("budget:");
  });
});

describe("emitCli — memory block (#53, rewired onto the PR 10 composition root)", () => {
  test("omits all memory wiring when the IR leaves it unset (byte-identity guard)", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/memory-service");
    expect(content).not.toContain("wireMemory");
    expect(content).not.toContain("__memWired");
    // The retired inline codegen must never resurface either.
    expect(content).not.toContain("@crewhaus/memory-store");
    expect(content).not.toContain("createMemoryTools");
    expect(content).not.toContain("\n  memory: {");
  });

  test("a memory block emits ONE stable wireMemory call with the serialized fragment", () => {
    const content = emitCli(baseIr({ memory: {} })).files[0]?.content ?? "";
    expect(content).toContain(`import { wireMemory } from "@crewhaus/memory-service";`);
    expect(content).toContain(
      'const __memWired = await wireMemory({"specName":"smoke","memory":{}}, { catalog: defaultCatalog, cwd: process.cwd() });',
    );
    expect(content).toContain("...__memWired.options,");
  });

  test("the fragment carries exactly the declared IR memory fields", () => {
    const content =
      emitCli(
        baseIr({
          memory: { enabled: true, autoRecall: true, recallK: 4, autoCapture: true },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain(
      '{"specName":"smoke","memory":{"enabled":true,"autoCapture":true,"autoRecall":true,"recallK":4}}',
    );
  });

  test("the emitted bundle contains NO inline store/seam codegen — the service owns it", () => {
    const content =
      emitCli(baseIr({ memory: { autoRecall: true, autoCapture: true } })).files[0]?.content ?? "";
    expect(content).not.toContain("createMemoryStore");
    expect(content).not.toContain("createMemoryTools");
    expect(content).not.toContain("summarizeDurableFacts");
    expect(content).not.toContain("onCapture: async");
    expect(content).not.toContain("@crewhaus/memory-store");
  });

  test("enabled:false disables all memory wiring", () => {
    const content =
      emitCli(baseIr({ memory: { enabled: false, autoRecall: true } })).files[0]?.content ?? "";
    expect(content).not.toContain("wireMemory");
    expect(content).not.toContain("@crewhaus/memory-service");
  });

  test("memory.dream emits the boot-time deterministic catch-up (PR 14, §6.3)", () => {
    const content =
      emitCli(
        baseIr({
          memory: { dream: { everyMs: 86_400_000, mode: "full", budgetUsd: 0.5 } },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain(
      `import { wireMemory, runDreamBootCatchUp } from "@crewhaus/memory-service";`,
    );
    expect(content).toContain(
      'const __dreamNote = await runDreamBootCatchUp({"specName":"smoke","memory":{"dream":{"everyMs":86400000,"mode":"full","budgetUsd":0.5}}}, { cwd: process.cwd() });',
    );
    expect(content).toContain(
      "if (__dreamNote !== null) process.stdout.write(`${__dreamNote}\\n`);",
    );
  });

  test("no dream block → no catch-up lines (pinned bytes preserved)", () => {
    const content = emitCli(baseIr({ memory: {} })).files[0]?.content ?? "";
    expect(content).not.toContain("runDreamBootCatchUp");
    expect(content).not.toContain("__dreamNote");
  });

  test("the EMITTED fragment literal drives the real wiring: tool parity + recall/capture round-trip", async () => {
    // Behavioral-equivalence pin at the emit boundary: pull the exact JSON
    // literal out of the generated bundle, run it through wireMemory (what
    // the bundle does at boot), and drive the seams end to end.
    const content =
      emitCli(baseIr({ memory: { autoRecall: true, autoCapture: true, recallK: 4 } })).files[0]
        ?.content ?? "";
    const match = content.match(/await wireMemory\((\{.*?\}), \{ catalog: defaultCatalog/);
    expect(match).not.toBeNull();
    const fragment = JSON.parse(match?.[1] ?? "{}") as MemoryWiringFragment;

    const tmp = mkdtempSync(join(tmpdir(), "target-cli-memory-"));
    try {
      const sessionId = "sess_00000000000000ff";
      const sessionsDir = join(tmp, ".crewhaus", "sessions");
      mkdirSync(sessionsDir, { recursive: true });
      writeFileSync(
        join(sessionsDir, `${sessionId}.jsonl`),
        `${[
          JSON.stringify({ kind: "user_message", payload: { content: "delimiter?" } }),
          JSON.stringify({ kind: "tool_result", payload: { toolUseId: "tu_emit_1" } }),
          JSON.stringify({
            kind: "assistant_message",
            payload: { content: "Semicolons delimit EU CSV files." },
          }),
        ].join("\n")}\n`,
      );

      const registered: RegisteredTool[] = [];
      const wired = await wireMemory(fragment, {
        catalog: { register: (t) => registered.push(t) },
        cwd: tmp,
        homeDir: join(tmp, "home"),
      });
      // Same tool surface the interpreter path wires (Remember/Recall as
      // before this PR; MemoryForget is the sanctioned §3.4 addition).
      expect(registered.map((t) => t.name)).toEqual(["Remember", "Recall", "MemoryForget"]);
      // Capture round-trip through the emitted wiring...
      await wired.options.memory?.onCapture?.(1, sessionId);
      // ...and recall of what was captured, with the emitted recallK.
      expect(wired.options.memory?.recallK).toBe(4);
      const lines = await wired.options.memory?.recall?.("EU CSV delimiter", 4);
      expect(lines).toEqual(["Semicolons delimit EU CSV files."]);
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });
});

describe("emitCli — limits block (loop contract 0.4, Batch A)", () => {
  test("emits every declared limits field into the runChatLoop call", () => {
    const content =
      emitCli(
        baseIr({
          limits: {
            maxToolIterations: 25,
            maxConcurrentTools: 2,
            contextLimit: 120_000,
            deadlineMs: 600_000,
            turnTimeoutMs: 120_000,
            modelCallTimeoutMs: 60_000,
            loopDetection: { window: 12, threshold: 3, escalation: "abort" },
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain("maxToolIterations: 25,");
    expect(content).toContain("maxConcurrentTools: 2,");
    expect(content).toContain("contextLimit: 120000,");
    expect(content).toContain("deadlineMs: 600000,");
    expect(content).toContain("turnTimeoutMs: 120000,");
    expect(content).toContain("modelCallTimeoutMs: 60000,");
    expect(content).toContain('loopDetection: {"window":12,"threshold":3,"escalation":"abort"},');
  });

  test("a partial limits block emits only the declared fields", () => {
    const content = emitCli(baseIr({ limits: { maxToolIterations: 40 } })).files[0]?.content ?? "";
    expect(content).toContain("maxToolIterations: 40,");
    expect(content).not.toContain("maxConcurrentTools:");
    expect(content).not.toContain("contextLimit:");
    expect(content).not.toContain("deadlineMs:");
    expect(content).not.toContain("turnTimeoutMs:");
    expect(content).not.toContain("modelCallTimeoutMs:");
    expect(content).not.toContain("loopDetection:");
  });

  test("loopDetection carries only the declared knobs", () => {
    const content =
      emitCli(baseIr({ limits: { loopDetection: { escalation: "justify" } } })).files[0]?.content ??
      "";
    expect(content).toContain('loopDetection: {"escalation":"justify"},');
  });

  test("no limits block → none of the limit fields are emitted (byte-identity guard)", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("maxToolIterations:");
    expect(content).not.toContain("maxConcurrentTools:");
    expect(content).not.toContain("contextLimit:");
    expect(content).not.toContain("deadlineMs:");
    expect(content).not.toContain("turnTimeoutMs:");
    expect(content).not.toContain("modelCallTimeoutMs:");
    expect(content).not.toContain("loopDetection:");
  });
});

describe("emitCli — agent.thinking (loop contract 0.4, Batch A)", () => {
  test("emits the explicit budget form verbatim", () => {
    const content =
      emitCli(
        baseIr({
          agent: {
            model: "claude-sonnet-4-6",
            instructions: "be helpful",
            thinking: { budgetTokens: 2048 },
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('thinking: {"budgetTokens":2048},');
  });

  test("emits the portable effort form verbatim", () => {
    const content =
      emitCli(
        baseIr({
          agent: {
            model: "claude-sonnet-4-6",
            instructions: "be helpful",
            thinking: { effort: "high" },
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('thinking: {"effort":"high"},');
  });

  test("omits thinking when the IR leaves it unset", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("thinking:");
  });
});

describe("emitCli — agent.streaming (loop contract 0.4, Batch A)", () => {
  test("emits streaming: true when declared", () => {
    const content =
      emitCli(
        baseIr({
          agent: { model: "claude-sonnet-4-6", instructions: "be helpful", streaming: true },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain("streaming: true,");
  });

  test("a declared streaming: false is carried verbatim (declared ≠ absent)", () => {
    const content =
      emitCli(
        baseIr({
          agent: { model: "claude-sonnet-4-6", instructions: "be helpful", streaming: false },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain("streaming: false,");
  });

  test("omits streaming when the IR leaves it unset", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("streaming:");
  });
});

describe("emitCli — agent.rateLimits (loop contract 0.4, Batch A)", () => {
  test("emits the per-tool record (incl. the * bucket) as a JSON literal", () => {
    const content =
      emitCli(
        baseIr({
          agent: {
            model: "claude-sonnet-4-6",
            instructions: "be helpful",
            rateLimits: { bash: { rpm: 30, burst: 5 }, "*": { rpm: 120 } },
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('rateLimits: {"bash":{"rpm":30,"burst":5},"*":{"rpm":120}},');
  });

  test("a hostile tool-name key cannot escape the JSON literal", () => {
    const content =
      emitCli(
        baseIr({
          agent: {
            model: "claude-sonnet-4-6",
            instructions: "be helpful",
            rateLimits: { 'evil"},pwn:{"': { rpm: 1 } },
          },
        }),
      ).files[0]?.content ?? "";
    // JSON.stringify escapes the embedded quote so the key stays inert data.
    expect(content).toContain('rateLimits: {"evil\\"},pwn:{\\"":{"rpm":1}},');
  });

  test("omits rateLimits when the IR leaves it unset", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("rateLimits:");
  });
});

describe("emitCli — compaction tuning knobs (loop contract 0.4, Batch A)", () => {
  test("threshold + snip knobs land on the runtime option names", () => {
    const content =
      emitCli(
        baseIr({
          compaction: { threshold: 0.8, snipKeepHead: 6, snipKeepTail: 30 },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain("compactionThreshold: 0.8,");
    expect(content).toContain("snipKeepHead: 6,");
    expect(content).toContain("snipKeepTail: 30,");
  });

  test("each knob is independent (threshold alone)", () => {
    const content = emitCli(baseIr({ compaction: { threshold: 0.75 } })).files[0]?.content ?? "";
    expect(content).toContain("compactionThreshold: 0.75,");
    expect(content).not.toContain("snipKeepHead:");
    expect(content).not.toContain("snipKeepTail:");
  });

  test("composes with compaction.model (both emitted)", () => {
    const content =
      emitCli(baseIr({ compaction: { model: "claude-haiku-4-5-20251001", threshold: 0.9 } }))
        .files[0]?.content ?? "";
    expect(content).toContain('compactionModel: "claude-haiku-4-5-20251001",');
    expect(content).toContain("compactionThreshold: 0.9,");
  });

  test("no tuning knobs → none of the fields are emitted (runtime defaults stay authoritative)", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("compactionThreshold:");
    expect(content).not.toContain("snipKeepHead:");
    expect(content).not.toContain("snipKeepTail:");
  });
});

describe("emitCli — spec-declared hooks (loop contract 0.4, Batch A)", () => {
  test("emits the spec-hooks literal and concatenates it BELOW the settings.json layers", () => {
    const content =
      emitCli(
        baseIr({
          hooks: [
            { event: "pre-tool", matcher: "Bash", command: "./gate.sh", timeoutMs: 3000 },
            { event: "stop", command: "./notify.sh" },
          ],
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain(
      'const __specHooks = [{"event":"pre-tool","matcher":"Bash","command":"./gate.sh","timeoutMs":3000},{"event":"stop","command":"./notify.sh"}] as const;',
    );
    // Spec hooks come FIRST in the concat — the lowest layer, mirroring the
    // permission RuleSet's settings-over-yaml precedence (aggregateDecisions'
    // mutate shallow-merge is later-wins, so settings.json entries override).
    expect(content).toContain("hooks: [...__specHooks, ...__hooks],");
    expect(content).not.toContain("hooks: __hooks,");
    // Declaration order is preserved (hooks fire in declaration order).
    const preToolIdx = content.indexOf('"event":"pre-tool"');
    const stopIdx = content.indexOf('"event":"stop"');
    expect(preToolIdx).toBeGreaterThanOrEqual(0);
    expect(stopIdx).toBeGreaterThan(preToolIdx);
  });

  test("the spec-hooks literal is declared before the runChatLoop call", () => {
    const content =
      emitCli(baseIr({ hooks: [{ event: "session-start", command: "echo hi" }] })).files[0]
        ?.content ?? "";
    const declIdx = content.indexOf("const __specHooks =");
    const callIdx = content.indexOf("await runChatLoop({");
    expect(declIdx).toBeGreaterThanOrEqual(0);
    expect(callIdx).toBeGreaterThan(declIdx);
  });

  test("a hostile hook command cannot escape the JSON literal", () => {
    const content =
      emitCli(
        baseIr({
          hooks: [{ event: "stop", command: 'x"; process.exit(1); //' }],
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('"command":"x\\"; process.exit(1); //"');
    expect(content).not.toContain('"x"; process.exit(1);');
  });

  test("no spec hooks → the plain settings.json wiring is unchanged (byte-identity guard)", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).toContain("hooks: __hooks,");
    expect(content).not.toContain("__specHooks");
  });
});

describe("emitCli — memory.embedder fallback (loop contract 0.4, Batch A)", () => {
  test("memory.embedder constructs deps.embedder for wireMemory (wins over wiki.embedder)", () => {
    const content =
      emitCli(
        baseIr({
          memory: { embedder: "openai/text-embedding-3-small", wiki: { enabled: true } },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('import { createEmbedder } from "@crewhaus/embedder";');
    // deps.embedder beats the fragment's wiki.embedder inside memory-service's
    // resolveEmbedder — the documented fallback order (embedder → wiki.embedder).
    expect(content).toContain(
      'embedder: createEmbedder({ model: "openai/text-embedding-3-small" })',
    );
  });

  test("without memory.embedder the wiki.embedder fallback rides the fragment only", () => {
    const content =
      emitCli(baseIr({ memory: { wiki: { enabled: true, embedder: "mock/deterministic" } } }))
        .files[0]?.content ?? "";
    // The fragment carries wiki.embedder; no deps-level construction.
    expect(content).toContain('"embedder":"mock/deterministic"');
    expect(content).not.toContain("embedder: createEmbedder(");
    expect(content).not.toContain('import { createEmbedder } from "@crewhaus/embedder";');
  });

  test("with the semantic egress matcher also on, createEmbedder is imported exactly once", () => {
    const content =
      emitCli(
        baseIr({
          security: { egressMatcher: "semantic" },
          memory: { embedder: "openai/text-embedding-3-small" },
        }),
      ).files[0]?.content ?? "";
    const matches = content.match(/import \{ createEmbedder \} from "@crewhaus\/embedder";/g);
    expect(matches?.length).toBe(1);
    // Both consumers still reference the binding.
    expect(content).toContain("createEmbedder({\n  model: process.env.CREWHAUS_EGRESS_EMBEDDER");
    expect(content).toContain(
      'embedder: createEmbedder({ model: "openai/text-embedding-3-small" })',
    );
  });

  test("the embedder model string is escaped (hostile spec value stays inert)", () => {
    const content =
      emitCli(baseIr({ memory: { embedder: 'x" }); process.exit(1); //' } })).files[0]?.content ??
      "";
    expect(content).toContain('createEmbedder({ model: "x\\" }); process.exit(1); //" })');
  });
});

describe("emitCli — observability.slo → sloTargets (item 37, F4 codegen parity)", () => {
  test("a compiled bundle threads sloTargets into runChatLoop so the monitor attaches", () => {
    const content =
      emitCli(
        baseIr({
          observability: {
            slo: { ttftMs: 1400, windowMs: 300_000, mitigation: ["alert"] },
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain("sloTargets:");
    expect(content).toContain('"ttftMs":1400');
    expect(content).toContain('"mitigation":["alert"]');
  });

  test("no observability block ⇒ no sloTargets field (byte-identical to before)", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("sloTargets:");
  });
});

describe('emitCli — watchme env stamp ("watch me" §6.3)', () => {
  const watchmeIr = (enabled: boolean, capture: "full" | "mirrors"): IrV0 =>
    baseIr({
      watchme: {
        enabled,
        capture,
        judgeModel: "claude-haiku-4-5",
        judgeSampleRate: 0.15,
        judgeBudgetUsd: 0,
        scope: "harness",
        share: false,
      },
    });

  test("enabled + capture full stamps CREWHAUS_WATCHME at bundle boot", () => {
    const content = emitCli(watchmeIr(true, "full")).files[0]?.content ?? "";
    expect(content).toContain('process.env["CREWHAUS_WATCHME"] ??= "1";');
  });

  test("mirrors capture / disabled / absent block ⇒ no stamp (byte-identity guard)", () => {
    for (const ir of [watchmeIr(true, "mirrors"), watchmeIr(false, "full"), baseIr()]) {
      const content = emitCli(ir).files[0]?.content ?? "";
      expect(content).not.toContain("CREWHAUS_WATCHME");
    }
  });
});

describe("emitCli — learning block (v0.3.0 §3.3, PR 17)", () => {
  const LEARNING = {
    domain: "specialty coffee extraction science",
    curriculum: "curriculum.md",
    sources: ["sca.coffee", "*.edu"],
    study: { onHeartbeat: true, onDream: true },
  } as const;

  test("learning rides the emitted fragment (skill + /study /reflect wire at boot)", () => {
    const content =
      emitCli(
        baseIr({
          memory: { wiki: { enabled: true, requireSources: true } },
          continuity: { plan: true, proof: "ladder", ledger: true, handoff: true, scope: "spec" },
          learning: LEARNING,
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('"learning":{"domain":"specialty coffee extraction science"');
    expect(content).toContain('"curriculum":"curriculum.md"');
    expect(content).toContain('"sources":["sca.coffee","*.edu"]');
    expect(content).toContain('"study":{"onHeartbeat":true,"onDream":true}');
    // No exam configured → no exam runner in the bundle.
    expect(content).not.toContain("createExamRunner");
    expect(content).not.toContain("@crewhaus/eval-runner");
  });

  test("learning.exam emits the programmatic exam runner (no Bash shell-out)", () => {
    const content =
      emitCli(
        baseIr({
          memory: { wiki: { enabled: true, requireSources: true } },
          continuity: { plan: true, proof: "ladder", ledger: true, handoff: true, scope: "spec" },
          learning: {
            ...LEARNING,
            exam: { dataset: "eval/dataset.jsonl", graders: "eval/graders.yaml" },
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('import { createExamRunner } from "@crewhaus/eval-runner";');
    expect(content).toContain(
      'examRunner: createExamRunner({ specName: "smoke", model: "claude-sonnet-4-6", instructions: "be helpful", fragment: ',
    );
    // The runner rides the SAME wireMemory call — one composition root.
    expect(content).toContain("await wireMemory(");
    expect(content).not.toContain("crewhaus eval"); // the demo's Bash hack never resurfaces
  });

  test("learning without continuity still hands the skill surface to wireMemory", () => {
    const content =
      emitCli(
        baseIr({
          memory: { wiki: { enabled: true, requireSources: true } },
          learning: LEARNING,
        }),
      ).files[0]?.content ?? "";
    // The composition root owns skills/commands (no bundle-side discovery).
    expect(content).toContain("const __skills = __memWired.options.skills ?? [];");
    expect(content).not.toContain("discoverSkills");
  });

  test("REGRESSION: no learning block → the emitted bundle is byte-identical to PR 16 (golden pin)", () => {
    const golden = readFileSync(
      join(import.meta.dir, "__fixtures__", "pr16-memory-bundle.golden.txt"),
      "utf-8",
    );
    const content =
      emitCli(
        baseIr({
          name: "pinned",
          memory: {
            enabled: true,
            autoCapture: true,
            autoRecall: true,
            recallK: 5,
            wiki: { enabled: true, autoRecall: true },
            dream: { everyMs: 86_400_000, mode: "full", budgetUsd: 0.5 },
          },
          continuity: { plan: true, proof: "ladder", ledger: true, handoff: true, scope: "spec" },
        }),
      ).files[0]?.content ?? "";
    expect(content).toBe(golden);
  });

  test("no learning block → no learning artifacts anywhere in the bundle", () => {
    const content =
      emitCli(
        baseIr({
          memory: { wiki: { enabled: true } },
          continuity: { plan: true, proof: "ladder", ledger: true, handoff: true, scope: "spec" },
        }),
      ).files[0]?.content ?? "";
    expect(content).not.toContain("learning");
    expect(content).not.toContain("run_exam");
    expect(content).not.toContain("createExamRunner");
  });
});

describe("emitCli — evaluation block (loop contract 0.4, Batch B, G02)", () => {
  test("llm_judge: emits the eval-judge wiring with the explicit judge model", () => {
    const content =
      emitCli(
        baseIr({
          evaluation: {
            grader: {
              type: "llm_judge",
              criteria: "answers cite a source",
              model: "claude-haiku-4-5",
            },
            threshold: 0.8,
            onFail: "retry",
            maxRetries: 2,
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('import type { RunEvaluation } from "@crewhaus/runtime-core";');
    expect(content).toContain('import { judge } from "@crewhaus/eval-judge";');
    expect(content).toContain("const __evaluation: RunEvaluation = {");
    expect(content).toContain('graderType: "llm_judge",');
    expect(content).toContain("threshold: 0.8,");
    expect(content).toContain('onFail: "retry",');
    expect(content).toContain("maxRetries: 2,");
    // the evaluate fn scores through judge() on the resolved judge model
    expect(content).toContain('model: "claude-haiku-4-5",');
    expect(content).toContain('description: "answers cite a source",');
    expect(content).toContain("evaluate: async ({ finalText }) => {");
    expect(content).toContain("agentOutput: finalText,");
    expect(content).toContain("(__verdict.score - 1) / 4");
    // and the option is threaded into runChatLoop
    expect(content).toContain("evaluation: __evaluation,");
  });

  test("llm_judge: the judge model defaults to the shape's primary model", () => {
    const content =
      emitCli(
        baseIr({
          evaluation: {
            grader: { type: "llm_judge", criteria: "be kind" },
            threshold: 0.7,
            onFail: "retry",
            maxRetries: 1,
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('model: "claude-sonnet-4-6",');
    expect(content).toContain('description: "be kind",');
  });

  test("llm_judge: the default threshold 0.7 is honored when the IR omits it", () => {
    const content =
      emitCli(
        baseIr({
          evaluation: {
            grader: { type: "llm_judge", criteria: "be kind" },
            onFail: "retry",
            maxRetries: 1,
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain("threshold: 0.7,");
  });

  test("contains: emits a pure fn (no eval-judge import; documented threshold 1)", () => {
    const content =
      emitCli(
        baseIr({
          evaluation: {
            grader: { type: "contains", value: "DONE" },
            onFail: "halt",
            maxRetries: 3,
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/eval-judge");
    expect(content).toContain('graderType: "contains",');
    expect(content).toContain("threshold: 1,");
    expect(content).toContain('finalText.includes("DONE")');
    expect(content).toContain('{ score: 1, rationale: "output contains \\"DONE\\"" }');
    expect(content).toContain('{ score: 0, rationale: "output missing \\"DONE\\"" }');
    expect(content).toContain('onFail: "halt",');
    expect(content).toContain("maxRetries: 3,");
    expect(content).toContain("evaluation: __evaluation,");
  });

  test("regex: emits a pure fn with a per-call lastIndex reset", () => {
    const content =
      emitCli(
        baseIr({
          evaluation: {
            grader: { type: "regex", value: "\\d{3}-\\d{4}" },
            onFail: "note",
            maxRetries: 1,
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/eval-judge");
    expect(content).toContain('const __evalRegex = new RegExp("\\\\d{3}-\\\\d{4}");');
    expect(content).toContain('graderType: "regex",');
    expect(content).toContain("threshold: 1,");
    expect(content).toContain("__evalRegex.lastIndex = 0;");
    expect(content).toContain("__evalRegex.test(finalText)");
    expect(content).toContain('onFail: "note",');
    expect(content).toContain("evaluation: __evaluation,");
  });

  test("criteria with quotes/newlines are escaped into the generated source", () => {
    const content =
      emitCli(
        baseIr({
          evaluation: {
            grader: { type: "llm_judge", criteria: 'say "yes"\nthen stop' },
            threshold: 0.7,
            onFail: "retry",
            maxRetries: 1,
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('description: "say \\"yes\\"\\nthen stop"');
    expect(content).not.toContain('\nthen stop"');
  });

  test("no evaluation block → no evaluation wiring anywhere (byte-identity guard)", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("evaluation:");
    expect(content).not.toContain("__evaluation");
    expect(content).not.toContain("@crewhaus/eval-judge");
    expect(content).not.toContain("__evalRegex");
  });
});

describe("emitCli — knowledge RAG block (Loop contract 0.4, Batch E, G22)", () => {
  const KNOWLEDGE_IR = (): IrV0 =>
    baseIr({
      knowledge: {
        vectorBackend: "in-memory",
        defaultK: 5,
        chunkSize: 400,
        chunkOverlap: 0,
        sources: [
          { kind: "path", path: "docs/manual.md" },
          { kind: "glob", glob: "kb/**/*.md" },
          { kind: "url", url: "https://example.com/faq" },
        ],
      },
    });

  test("ingests the declared sources through knowledgeRetrieve and registers the tool", () => {
    const c = emitCli(KNOWLEDGE_IR()).files[0]?.content ?? "";
    expect(c).toContain(
      'import { knowledgeRetrieve, resolveKnowledgeEmbedder } from "@crewhaus/tool-retrieve";',
    );
    expect(c).toContain("const __knowledgeTool = await knowledgeRetrieve({");
    expect(c).toContain('{"kind":"path","path":"docs/manual.md"}');
    expect(c).toContain('{"kind":"glob","glob":"kb/**/*.md"}');
    expect(c).toContain('{"kind":"url","url":"https://example.com/faq"}');
    expect(c).toContain('vectorBackend: "in-memory"');
    expect(c).toContain("defaultK: 5");
    expect(c).toContain("chunkSize: 400");
    expect(c).toContain("defaultCatalog.register(__knowledgeTool);");
  });

  test("the G76 embedder order is deferred to resolveKnowledgeEmbedder with the declared inputs", () => {
    const c =
      emitCli(
        baseIr({
          knowledge: {
            embedder: "openai/text-embedding-3-large",
            vectorBackend: "in-memory",
            defaultK: 5,
            chunkSize: 400,
            chunkOverlap: 0,
            sources: [{ kind: "path", path: "kb.md" }],
          },
          memory: {
            enabled: true,
            embedder: "mock/deterministic",
            wiki: { embedder: "mock/wiki" },
          },
        }),
      ).files[0]?.content ?? "";
    expect(c).toContain(
      'resolveKnowledgeEmbedder({ knowledgeEmbedder: "openai/text-embedding-3-large", memoryEmbedder: "mock/deterministic", wikiEmbedder: "mock/wiki" })',
    );
  });

  test("no knowledge block → no RAG wiring (byte-stable)", () => {
    const c = emitCli(baseIr()).files[0]?.content ?? "";
    expect(c).not.toContain("knowledgeRetrieve");
    expect(c).not.toContain("resolveKnowledgeEmbedder");
    expect(c).not.toContain("__knowledgeTool");
  });
});

describe("emitCli — plugin activation (Item 3 / G32)", () => {
  test("no plugins → no plugin activation artifacts (bundles stay byte-identical)", () => {
    const c = emitCli(baseIr()).files[0]?.content ?? "";
    expect(c).not.toContain("@crewhaus/plugin-loader");
    expect(c).not.toContain("activatePlugins");
    expect(c).not.toContain("__plugins");
    expect(c).not.toContain("pluginDirs");
  });

  test("plugins: list → activates them and registers contributed tools on the catalog", () => {
    const c = emitCli(baseIr({ plugins: ["acme-tools", "beta-pack"] })).files[0]?.content ?? "";
    expect(c).toContain(
      'import { activatePlugins, createDefaultPluginRuntime } from "@crewhaus/plugin-loader";',
    );
    // Names are emitted verbatim, in load order.
    expect(c).toContain('names: ["acme-tools","beta-pack"]');
    // Fail-closed loader, dev opt-out via env.
    expect(c).toContain('allowUnsigned: process.env.CREWHAUS_PLUGIN_ALLOW_UNSIGNED === "1"');
    // Contributed tools land on the shared catalog, first-party wins collisions.
    expect(c).toContain("for (const __t of __plugins.tools)");
    expect(c).toContain("defaultCatalog.register(__t);");
    expect(c).toContain("if (defaultCatalog.get(__t.name) !== undefined)");
  });

  test("plugins feed their skill dirs into discoverSkills (non-continuity path)", () => {
    const c = emitCli(baseIr({ plugins: ["acme-tools"] })).files[0]?.content ?? "";
    expect(c).toContain("discoverSkills({ cwd: __cwd, pluginDirs: __plugins.skillDirs })");
  });

  test("the plugin boot runs before the extension boot that reads __plugins.skillDirs", () => {
    const c = emitCli(baseIr({ plugins: ["acme-tools"] })).files[0]?.content ?? "";
    expect(c.indexOf("const __plugins = await activatePlugins(")).toBeGreaterThan(-1);
    expect(c.indexOf("const __plugins = await activatePlugins(")).toBeLessThan(
      c.indexOf("discoverSkills({ cwd: __cwd, pluginDirs: __plugins.skillDirs })"),
    );
  });

  test("continuity on: plugin tools still bind, but discoverSkills is not the skill source", () => {
    // With continuity on the bundle has no direct discoverSkills call (skills
    // come from wireMemory); plugin TOOLS still register on the catalog.
    const c =
      emitCli(
        baseIr({
          plugins: ["acme-tools"],
          continuity: { plan: true, proof: "ladder", ledger: true, handoff: true, scope: "spec" },
        }),
      ).files[0]?.content ?? "";
    expect(c).toContain("const __plugins = await activatePlugins(");
    expect(c).toContain("defaultCatalog.register(__t);");
    expect(c).not.toContain("pluginDirs: __plugins.skillDirs");
  });
});
