import { describe, expect, test } from "bun:test";
import type { IrV0 } from "@crewhaus/ir";
import { TargetEmitError, emitCli } from "./index";

function baseIr(overrides: Partial<IrV0> = {}): IrV0 {
  return {
    version: 0,
    name: "smoke",
    target: "cli",
    agent: { model: "claude-sonnet-4-6", instructions: "be helpful" },
    tools: [],
    toolConfigs: {},
    mcp_servers: {},
    permissions: { rules: [] },
    subAgents: [],
    compaction: {},
    ...overrides,
  };
}

describe("emitCli — bundle shape", () => {
  test("returns a single agent.ts file", () => {
    const bundle = emitCli(baseIr());
    expect(bundle.files.length).toBe(1);
    expect(bundle.files[0]?.path).toBe("agent.ts");
  });

  test("the emitted file starts with a bun shebang and DO NOT EDIT marker", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content.startsWith("#!/usr/bin/env bun")).toBe(true);
    expect(content).toContain("Generated by crewhaus. DO NOT EDIT.");
  });

  test("the IR name is embedded in the source-spec comment", () => {
    const content = emitCli(baseIr({ name: "my-bot" })).files[0]?.content ?? "";
    expect(content).toContain('Source spec: "my-bot"');
  });

  test("a newline in the spec name cannot break out of the source-spec comment (#147)", () => {
    const evil = "evil\nglobalThis.__PWNED__ = 1";
    const content = emitCli(baseIr({ name: evil })).files[0]?.content ?? "";
    const header = content.split("\n").find((l) => l.includes("Source spec:")) ?? "";
    expect(header).toContain("\\n"); // the newline is escaped inside the comment
    expect(content).not.toContain("\nglobalThis.__PWNED__ = 1"); // never emitted as live code
  });

  test("the model and instructions are escaped + embedded in the runChatLoop call", () => {
    const content =
      emitCli(
        baseIr({
          agent: { model: "claude-sonnet-4-6", instructions: 'said "hi"\nthen "bye"' },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('model: "claude-sonnet-4-6"');
    // double quotes inside the instruction must be escaped — proves escapeJsonString ran
    expect(content).toContain('said \\"hi\\"');
    expect(content).toContain('then \\"bye\\"');
  });

  test("sessionName defaults to the IR name and sessionTarget is cli", () => {
    const content = emitCli(baseIr({ name: "my-bot" })).files[0]?.content ?? "";
    expect(content).toContain('sessionName: "my-bot"');
    expect(content).toContain('sessionTarget: "cli"');
  });
});

describe("emitCli — tool wiring (Section 2)", () => {
  test("an empty tools list emits no tool imports but still imports defaultCatalog", () => {
    const content = emitCli(baseIr({ tools: [] })).files[0]?.content ?? "";
    // Section 11 parity: defaultCatalog import is unconditional now
    expect(content).toContain('from "@crewhaus/tool-catalog"');
    expect(content).not.toContain("@crewhaus/tool-fs");
    expect(content).not.toContain("@crewhaus/tool-bash");
    // tools field is always defaultCatalog.list()
    expect(content).toContain("tools: defaultCatalog.list()");
  });

  test("a single tool emits one import + one register call", () => {
    const content = emitCli(baseIr({ tools: ["read"] })).files[0]?.content ?? "";
    expect(content).toContain('import { read } from "@crewhaus/tool-fs"');
    expect(content).toContain("defaultCatalog.register(read);");
  });

  test("multiple tools from the same package are grouped into one import", () => {
    const content = emitCli(baseIr({ tools: ["read", "write", "edit"] })).files[0]?.content ?? "";
    // single import line covering all three exports
    expect(content).toMatch(/import \{ edit, read, write \} from "@crewhaus\/tool-fs"/);
    // three separate register calls
    expect(content).toContain("defaultCatalog.register(read);");
    expect(content).toContain("defaultCatalog.register(write);");
    expect(content).toContain("defaultCatalog.register(edit);");
  });

  test("tools across multiple packages each get their own grouped import", () => {
    const content =
      emitCli(baseIr({ tools: ["read", "bash", "todoWrite"] })).files[0]?.content ?? "";
    expect(content).toContain('import { bash } from "@crewhaus/tool-bash"');
    expect(content).toContain('import { read } from "@crewhaus/tool-fs"');
    expect(content).toContain('import { todoWrite } from "@crewhaus/tool-todo"');
  });

  test("an unknown tool name throws TargetEmitError listing known names", () => {
    expect(() => emitCli(baseIr({ tools: ["unknownTool"] }))).toThrow(TargetEmitError);
    try {
      emitCli(baseIr({ tools: ["unknownTool"] }));
    } catch (e) {
      expect(e).toBeInstanceOf(TargetEmitError);
      expect((e as Error).message).toContain('unknown tool "unknownTool"');
      expect((e as Error).message).toContain("known tools:");
      // proves the error is helpful — names a real builtin
      expect((e as Error).message).toContain("read");
    }
  });
});

describe("emitCli — permissions (Section 7)", () => {
  test("no rules and no mode → no permissionMode or permissionRules emitted", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("permissionMode");
    expect(content).not.toContain("permissionRules");
    // and no permission-engine import
    expect(content).not.toContain("@crewhaus/permission-engine");
  });

  test("a permission mode without rules emits permissionMode only", () => {
    const content =
      emitCli(baseIr({ permissions: { mode: "plan", rules: [] } })).files[0]?.content ?? "";
    expect(content).toContain('permissionMode: "plan"');
    expect(content).not.toContain("permissionRules:");
  });

  test("permission rules emit a layered rules object with builtin defaults", () => {
    const content =
      emitCli(
        baseIr({
          permissions: {
            mode: "default",
            rules: [
              { type: "alwaysAllow", pattern: "Read" },
              { type: "alwaysDeny", pattern: "Bash(rm *)" },
            ],
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain(
      'import { BUILTIN_DEFAULT_RULES } from "@crewhaus/permission-engine"',
    );
    expect(content).toContain("permissionRules: {");
    expect(content).toContain("yaml: [");
    expect(content).toContain('type: "alwaysAllow"');
    expect(content).toContain('pattern: "Read"');
    expect(content).toContain('pattern: "Bash(rm *)"');
    expect(content).toContain('source: "yaml"');
    expect(content).toContain("builtin: BUILTIN_DEFAULT_RULES");
  });
});

describe("emitCli — MCP servers (Section 9)", () => {
  test("empty mcp_servers → no McpHost import or boot block", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/mcp-host");
    expect(content).not.toContain("new McpHost()");
    expect(content).not.toContain("disconnectAll");
  });

  test("a stdio MCP server emits boot + cleanup blocks", () => {
    const content =
      emitCli(
        baseIr({
          mcp_servers: {
            everything: {
              transport: "stdio",
              command: "npx",
              args: ["-y", "@modelcontextprotocol/server-everything"],
            },
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('import { McpHost } from "@crewhaus/mcp-host"');
    expect(content).toContain('import { registerMcpServer } from "@crewhaus/tool-mcp"');
    expect(content).toContain("const mcpHost = new McpHost();");
    expect(content).toContain('mcpHost.addServer("everything"');
    expect(content).toContain("await Promise.all([");
    expect(content).toContain("registerMcpServer(mcpHost,");
    // the runChatLoop call is wrapped in try/finally so disconnectAll always runs
    expect(content).toContain("try {");
    expect(content).toContain("} finally {");
    expect(content).toContain("await mcpHost.disconnectAll();");
  });
});

describe("emitCli — extension surface (Section 11)", () => {
  test("hooks/skills/slashCommands imports + boot are emitted unconditionally", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).toContain('import { loadHooks } from "@crewhaus/hooks-engine"');
    expect(content).toContain(
      'import { discoverSkills, createSkillTool } from "@crewhaus/skills-registry"',
    );
    expect(content).toContain('import { loadCommands } from "@crewhaus/slash-commands"');
    expect(content).toContain("const __cwd = process.cwd();");
    expect(content).toContain("loadHooks({ cwd: __cwd })");
    expect(content).toContain("discoverSkills({ cwd: __cwd })");
    expect(content).toContain("loadCommands({ cwd: __cwd })");
    expect(content).toContain("hooks: __hooks");
    expect(content).toContain("skills: __skills");
    expect(content).toContain("slashCommands: __slashCommands");
    // skill-tool registration is conditional on discovery returning entries
    expect(content).toContain(
      "if (__skills.length > 0) defaultCatalog.register(createSkillTool(__skills));",
    );
  });
});

describe("emitCli — sub-agents (Section 13)", () => {
  test("empty subAgents is a no-op (regression: pre-Section-13 shape preserved)", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/tool-task");
    expect(content).not.toContain("@crewhaus/sub-agent-spawner");
    expect(content).not.toContain("__subAgents");
    expect(content).not.toContain("spawnSubAgent");
  });

  test("non-empty subAgents emits imports, registry, Task tool registration, and runChatLoop wiring", () => {
    const content =
      emitCli(
        baseIr({
          subAgents: [
            {
              name: "summarizer",
              description: "summarize text",
              instructions: "Summarize input in 2 sentences.",
              tools: [],
              permissions: "scoped",
              inheritBypass: false,
            },
          ],
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('import { createTaskTool } from "@crewhaus/tool-task"');
    expect(content).toContain('import { spawnSubAgent } from "@crewhaus/sub-agent-spawner"');
    expect(content).toContain('SubAgentDefinition } from "@crewhaus/agent-context-isolation"');
    expect(content).toContain("__subAgents");
    expect(content).toContain('"summarizer"');
    expect(content).toContain('description: "summarize text"');
    expect(content).toContain('permissions: "scoped"');
    expect(content).toContain("inherit_bypass: false");
    expect(content).toContain("createTaskTool({ subAgents: __subAgents })");
    expect(content).toContain("subAgents: __subAgents");
    expect(content).toContain("spawnSubAgent,");
  });

  test("replace-style permissions render as { allow, deny }", () => {
    const content =
      emitCli(
        baseIr({
          subAgents: [
            {
              name: "rep",
              description: "x",
              instructions: "y",
              tools: ["read"],
              permissions: { allow: ["Read", "Glob"], deny: ["Bash(**)"] },
              inheritBypass: false,
            },
          ],
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('allow: ["Read","Glob"]');
    expect(content).toContain('deny: ["Bash(**)"]');
  });
});

describe("emitCli — combined", () => {
  test("everything-on emits all four extension blocks in the right order", () => {
    const content =
      emitCli(
        baseIr({
          tools: ["read", "bash"],
          mcp_servers: {
            things: { transport: "stdio", command: "node", args: ["server.js"] },
          },
          permissions: {
            mode: "default",
            rules: [{ type: "alwaysAllow", pattern: "Read" }],
          },
        }),
      ).files[0]?.content ?? "";
    // imports come before boot blocks; boot blocks before the runChatLoop call
    const importsIdx = content.indexOf('from "@crewhaus/runtime-core"');
    const mcpBootIdx = content.indexOf("new McpHost()");
    const extensionBootIdx = content.indexOf("Promise.all([\n  loadHooks");
    const runChatLoopIdx = content.indexOf("await runChatLoop({");
    expect(importsIdx).toBeGreaterThanOrEqual(0);
    expect(mcpBootIdx).toBeGreaterThan(importsIdx);
    expect(extensionBootIdx).toBeGreaterThan(importsIdx);
    expect(runChatLoopIdx).toBeGreaterThan(mcpBootIdx);
    expect(runChatLoopIdx).toBeGreaterThan(extensionBootIdx);
  });
});

describe("emitCli — CLI banner (Phase 3 §3.3)", () => {
  test("omits banner code when ir.cli.banner is undefined", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("CREWHAUS_RESUMED");
    expect(content).not.toContain("__tagline");
  });

  test("emits a static-mode banner that prints the first tagline", () => {
    const ir = baseIr({
      cli: {
        banner: {
          taglineMode: "static",
          taglines: ["🦞 EXFOLIATE! EXFOLIATE!", "🦞 second tagline"],
        },
      },
    });
    const content = emitCli(ir).files[0]?.content ?? "";
    expect(content).toContain("🦞 EXFOLIATE! EXFOLIATE!");
    expect(content).toContain("__taglines[0]");
    expect(content).not.toContain("Math.random()");
    // Resumed-session suppression
    expect(content).toContain("CREWHAUS_RESUMED");
  });

  test("emits a random-mode banner that picks via Math.random()", () => {
    const ir = baseIr({
      cli: {
        banner: {
          taglineMode: "random",
          taglines: ["one", "two", "three"],
        },
      },
    });
    const content = emitCli(ir).files[0]?.content ?? "";
    expect(content).toContain("Math.floor(Math.random()");
    expect(content).toContain('"one"');
    expect(content).toContain('"two"');
    expect(content).toContain('"three"');
  });

  test("name is escaped against backtick/template injection inside the banner", () => {
    const ir = baseIr({
      name: "evil`${process.exit(1)}",
      cli: {
        banner: { taglineMode: "static", taglines: ["t"] },
      },
    });
    const content = emitCli(ir).files[0]?.content ?? "";
    // The banner emits inside a backtick template literal. Backticks and ${
    // in the name must be escaped so they can't break out of the template
    // and run arbitrary code at startup.
    expect(content).toContain("evil\\`\\${process.exit(1)}");
    // The escaped form should appear specifically in the banner body
    // (after the "process.stdout.write" call introducing the banner).
    const writeIdx = content.indexOf("process.stdout.write(`\\n");
    const escapedIdx = content.indexOf("evil\\`\\${process.exit(1)}");
    expect(escapedIdx).toBeGreaterThan(writeIdx);
  });
});

describe("emitCli — egress matcher (Pillar 3 sink-side, FR-006)", () => {
  test("no security block → no egress-matcher wiring (substring default, zero embedding deps)", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    // The default artifact must not pull in the semantic package or the
    // embedder — the optional-dependency posture (acceptance #4) holds.
    expect(content).not.toContain("@crewhaus/egress-matcher-semantic");
    expect(content).not.toContain("@crewhaus/embedder");
    expect(content).not.toContain("egressMatcher:");
    expect(content).not.toContain("createSemanticEgressMatcher");
    expect(content).not.toContain("__egressMatcher");
  });

  test('egressMatcher: "substring" emits nothing (explicit default is still the bare bundle)', () => {
    const content =
      emitCli(baseIr({ security: { egressMatcher: "substring" } })).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/egress-matcher-semantic");
    expect(content).not.toContain("@crewhaus/embedder");
    expect(content).not.toContain("egressMatcher:");
    expect(content).not.toContain("__egressMatcher");
  });

  test("security with only justification (no egressMatcher) emits no egress wiring", () => {
    // Presence of the security block alone must not trigger emission — only
    // egressMatcher: "semantic" does.
    const content =
      emitCli(baseIr({ security: { justification: { judge: "claude" } } })).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/egress-matcher-semantic");
    expect(content).not.toContain("egressMatcher:");
  });

  test('egressMatcher: "semantic" emits imports, embedder+matcher construction, and the runChatLoop field', () => {
    const content =
      emitCli(baseIr({ security: { egressMatcher: "semantic" } })).files[0]?.content ?? "";
    // Imports for the optional embedding-backed matcher + the embedder.
    expect(content).toContain('import { createEmbedder } from "@crewhaus/embedder"');
    expect(content).toContain(
      'import { createSemanticEgressMatcher } from "@crewhaus/egress-matcher-semantic"',
    );
    // Embedder model resolved at bundle runtime: env override > documented
    // default — the standalone analogue of the run path's resolution.
    expect(content).toContain("process.env.CREWHAUS_EGRESS_EMBEDDER");
    expect(content).toContain('"openai/text-embedding-3-small"');
    // The matcher is constructed with the injected embedder…
    expect(content).toContain("createSemanticEgressMatcher({ embedder: __egressEmbedder })");
    // …and threaded into runChatLoop, mirroring the run path.
    expect(content).toContain("egressMatcher: __egressMatcher");
  });

  test("semantic: the matcher is constructed BEFORE runChatLoop (so the field references a bound symbol)", () => {
    const content =
      emitCli(baseIr({ security: { egressMatcher: "semantic" } })).files[0]?.content ?? "";
    const constructIdx = content.indexOf("const __egressMatcher =");
    const runChatLoopIdx = content.indexOf("await runChatLoop({");
    expect(constructIdx).toBeGreaterThanOrEqual(0);
    expect(runChatLoopIdx).toBeGreaterThan(constructIdx);
  });

  test("semantic + MCP: egress construction sits ahead of the mcp try/finally wrapper", () => {
    // When MCP is present the runChatLoop call is wrapped in try/finally and
    // re-indented; the egress matcher construction must still precede it.
    const content =
      emitCli(
        baseIr({
          security: { egressMatcher: "semantic" },
          mcp_servers: {
            things: { transport: "stdio", command: "node", args: ["server.js"] },
          },
        }),
      ).files[0]?.content ?? "";
    const constructIdx = content.indexOf("const __egressMatcher =");
    const tryIdx = content.indexOf("try {");
    expect(constructIdx).toBeGreaterThanOrEqual(0);
    expect(tryIdx).toBeGreaterThan(constructIdx);
    // And the field is still threaded into the (wrapped) runChatLoop options.
    expect(content).toContain("egressMatcher: __egressMatcher");
  });
});

describe("emitCli — agent.maxTokens (max output tokens)", () => {
  test("emits maxTokens in the runChatLoop call when the IR sets it", () => {
    const content =
      emitCli(
        baseIr({
          agent: { model: "claude-sonnet-4-6", instructions: "be helpful", maxTokens: 16384 },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain("maxTokens: 16384,");
  });

  test("omits maxTokens entirely when the IR leaves it unset", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("maxTokens:");
  });
});
