import { escapeJsonString } from "@crewhaus/infra-utils";
import type { Bundle, IrV0 } from "@crewhaus/ir";

/**
 * Emit a self-contained CLI agent bundle for a CLI-target IR.
 * Slice scope: a single agent.ts that imports @crewhaus/runtime-core and
 * runs a streaming chat loop with the configured model and instructions.
 *
 * Future expansion (per catalog F2 target-cli-bundle): tools, hooks,
 * MCP config, settings.json, multi-file output, bundling for distribution.
 */
export function emitCli(ir: IrV0): Bundle {
  return {
    files: [
      {
        path: "agent.ts",
        content: renderAgent(ir),
      },
    ],
  };
}

function renderAgent(ir: IrV0): string {
  return `#!/usr/bin/env bun
// Generated by crewhaus-factory. DO NOT EDIT.
// Source spec: ${ir.name} (target: cli, ir version: ${ir.version})
import { runChatLoop } from "@crewhaus/runtime-core";

await runChatLoop({
  model: ${escapeJsonString(ir.agent.model)},
  instructions: ${escapeJsonString(ir.agent.instructions)},
});
`;
}
