import { describe, expect, test } from "bun:test";
import type { IrV0 } from "@crewhaus/ir";
import { TargetEmitError, emitCli } from "./index";

function baseIr(overrides: Partial<IrV0> = {}): IrV0 {
  return {
    version: 0,
    name: "smoke",
    target: "cli",
    agent: { model: "claude-sonnet-4-6", instructions: "be helpful" },
    tools: [],
    toolConfigs: {},
    mcp_servers: {},
    permissions: { rules: [] },
    subAgents: [],
    ...overrides,
  };
}

describe("emitCli — bundle shape", () => {
  test("returns a single agent.ts file", () => {
    const bundle = emitCli(baseIr());
    expect(bundle.files.length).toBe(1);
    expect(bundle.files[0]?.path).toBe("agent.ts");
  });

  test("the emitted file starts with a bun shebang and DO NOT EDIT marker", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content.startsWith("#!/usr/bin/env bun")).toBe(true);
    expect(content).toContain("Generated by crewhaus-factory. DO NOT EDIT.");
  });

  test("the IR name is embedded in the source-spec comment", () => {
    const content = emitCli(baseIr({ name: "my-bot" })).files[0]?.content ?? "";
    expect(content).toContain("Source spec: my-bot");
  });

  test("the model and instructions are escaped + embedded in the runChatLoop call", () => {
    const content =
      emitCli(
        baseIr({
          agent: { model: "claude-sonnet-4-6", instructions: 'said "hi"\nthen "bye"' },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('model: "claude-sonnet-4-6"');
    // double quotes inside the instruction must be escaped — proves escapeJsonString ran
    expect(content).toContain('said \\"hi\\"');
    expect(content).toContain('then \\"bye\\"');
  });

  test("sessionName defaults to the IR name and sessionTarget is cli", () => {
    const content = emitCli(baseIr({ name: "my-bot" })).files[0]?.content ?? "";
    expect(content).toContain('sessionName: "my-bot"');
    expect(content).toContain('sessionTarget: "cli"');
  });
});

describe("emitCli — tool wiring (Section 2)", () => {
  test("an empty tools list emits no tool imports but still imports defaultCatalog", () => {
    const content = emitCli(baseIr({ tools: [] })).files[0]?.content ?? "";
    // Section 11 parity: defaultCatalog import is unconditional now
    expect(content).toContain('from "@crewhaus/tool-catalog"');
    expect(content).not.toContain("@crewhaus/tool-fs");
    expect(content).not.toContain("@crewhaus/tool-bash");
    // tools field is always defaultCatalog.list()
    expect(content).toContain("tools: defaultCatalog.list()");
  });

  test("a single tool emits one import + one register call", () => {
    const content = emitCli(baseIr({ tools: ["read"] })).files[0]?.content ?? "";
    expect(content).toContain('import { read } from "@crewhaus/tool-fs"');
    expect(content).toContain("defaultCatalog.register(read);");
  });

  test("multiple tools from the same package are grouped into one import", () => {
    const content = emitCli(baseIr({ tools: ["read", "write", "edit"] })).files[0]?.content ?? "";
    // single import line covering all three exports
    expect(content).toMatch(/import \{ edit, read, write \} from "@crewhaus\/tool-fs"/);
    // three separate register calls
    expect(content).toContain("defaultCatalog.register(read);");
    expect(content).toContain("defaultCatalog.register(write);");
    expect(content).toContain("defaultCatalog.register(edit);");
  });

  test("tools across multiple packages each get their own grouped import", () => {
    const content =
      emitCli(baseIr({ tools: ["read", "bash", "todoWrite"] })).files[0]?.content ?? "";
    expect(content).toContain('import { bash } from "@crewhaus/tool-bash"');
    expect(content).toContain('import { read } from "@crewhaus/tool-fs"');
    expect(content).toContain('import { todoWrite } from "@crewhaus/tool-todo"');
  });

  test("an unknown tool name throws TargetEmitError listing known names", () => {
    expect(() => emitCli(baseIr({ tools: ["unknownTool"] }))).toThrow(TargetEmitError);
    try {
      emitCli(baseIr({ tools: ["unknownTool"] }));
    } catch (e) {
      expect(e).toBeInstanceOf(TargetEmitError);
      expect((e as Error).message).toContain('unknown tool "unknownTool"');
      expect((e as Error).message).toContain("known tools:");
      // proves the error is helpful — names a real builtin
      expect((e as Error).message).toContain("read");
    }
  });
});

describe("emitCli — permissions (Section 7)", () => {
  test("no rules and no mode → no permissionMode or permissionRules emitted", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("permissionMode");
    expect(content).not.toContain("permissionRules");
    // and no permission-engine import
    expect(content).not.toContain("@crewhaus/permission-engine");
  });

  test("a permission mode without rules emits permissionMode only", () => {
    const content =
      emitCli(baseIr({ permissions: { mode: "plan", rules: [] } })).files[0]?.content ?? "";
    expect(content).toContain('permissionMode: "plan"');
    expect(content).not.toContain("permissionRules:");
  });

  test("permission rules emit a layered rules object with builtin defaults", () => {
    const content =
      emitCli(
        baseIr({
          permissions: {
            mode: "default",
            rules: [
              { type: "alwaysAllow", pattern: "Read" },
              { type: "alwaysDeny", pattern: "Bash(rm *)" },
            ],
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain(
      'import { BUILTIN_DEFAULT_RULES } from "@crewhaus/permission-engine"',
    );
    expect(content).toContain("permissionRules: {");
    expect(content).toContain("yaml: [");
    expect(content).toContain('type: "alwaysAllow"');
    expect(content).toContain('pattern: "Read"');
    expect(content).toContain('pattern: "Bash(rm *)"');
    expect(content).toContain('source: "yaml"');
    expect(content).toContain("builtin: BUILTIN_DEFAULT_RULES");
  });
});

describe("emitCli — MCP servers (Section 9)", () => {
  test("empty mcp_servers → no McpHost import or boot block", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/mcp-host");
    expect(content).not.toContain("new McpHost()");
    expect(content).not.toContain("disconnectAll");
  });

  test("a stdio MCP server emits boot + cleanup blocks", () => {
    const content =
      emitCli(
        baseIr({
          mcp_servers: {
            everything: {
              transport: "stdio",
              command: "npx",
              args: ["-y", "@modelcontextprotocol/server-everything"],
            },
          },
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('import { McpHost } from "@crewhaus/mcp-host"');
    expect(content).toContain('import { registerMcpServer } from "@crewhaus/tool-mcp"');
    expect(content).toContain("const mcpHost = new McpHost();");
    expect(content).toContain('mcpHost.addServer("everything"');
    expect(content).toContain("await Promise.all([");
    expect(content).toContain("registerMcpServer(mcpHost,");
    // the runChatLoop call is wrapped in try/finally so disconnectAll always runs
    expect(content).toContain("try {");
    expect(content).toContain("} finally {");
    expect(content).toContain("await mcpHost.disconnectAll();");
  });
});

describe("emitCli — extension surface (Section 11)", () => {
  test("hooks/skills/slashCommands imports + boot are emitted unconditionally", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).toContain('import { loadHooks } from "@crewhaus/hooks-engine"');
    expect(content).toContain(
      'import { discoverSkills, createSkillTool } from "@crewhaus/skills-registry"',
    );
    expect(content).toContain('import { loadCommands } from "@crewhaus/slash-commands"');
    expect(content).toContain("const __cwd = process.cwd();");
    expect(content).toContain("loadHooks({ cwd: __cwd })");
    expect(content).toContain("discoverSkills({ cwd: __cwd })");
    expect(content).toContain("loadCommands({ cwd: __cwd })");
    expect(content).toContain("hooks: __hooks");
    expect(content).toContain("skills: __skills");
    expect(content).toContain("slashCommands: __slashCommands");
    // skill-tool registration is conditional on discovery returning entries
    expect(content).toContain(
      "if (__skills.length > 0) defaultCatalog.register(createSkillTool(__skills));",
    );
  });
});

describe("emitCli — sub-agents (Section 13)", () => {
  test("empty subAgents is a no-op (regression: pre-Section-13 shape preserved)", () => {
    const content = emitCli(baseIr()).files[0]?.content ?? "";
    expect(content).not.toContain("@crewhaus/tool-task");
    expect(content).not.toContain("@crewhaus/sub-agent-spawner");
    expect(content).not.toContain("__subAgents");
    expect(content).not.toContain("spawnSubAgent");
  });

  test("non-empty subAgents emits imports, registry, Task tool registration, and runChatLoop wiring", () => {
    const content =
      emitCli(
        baseIr({
          subAgents: [
            {
              name: "summarizer",
              description: "summarize text",
              instructions: "Summarize input in 2 sentences.",
              tools: [],
              permissions: "scoped",
              inheritBypass: false,
            },
          ],
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('import { createTaskTool } from "@crewhaus/tool-task"');
    expect(content).toContain('import { spawnSubAgent } from "@crewhaus/sub-agent-spawner"');
    expect(content).toContain('SubAgentDefinition } from "@crewhaus/agent-context-isolation"');
    expect(content).toContain("__subAgents");
    expect(content).toContain('"summarizer"');
    expect(content).toContain('description: "summarize text"');
    expect(content).toContain('permissions: "scoped"');
    expect(content).toContain("inherit_bypass: false");
    expect(content).toContain("createTaskTool({ subAgents: __subAgents })");
    expect(content).toContain("subAgents: __subAgents");
    expect(content).toContain("spawnSubAgent,");
  });

  test("replace-style permissions render as { allow, deny }", () => {
    const content =
      emitCli(
        baseIr({
          subAgents: [
            {
              name: "rep",
              description: "x",
              instructions: "y",
              tools: ["read"],
              permissions: { allow: ["Read", "Glob"], deny: ["Bash(**)"] },
              inheritBypass: false,
            },
          ],
        }),
      ).files[0]?.content ?? "";
    expect(content).toContain('allow: ["Read","Glob"]');
    expect(content).toContain('deny: ["Bash(**)"]');
  });
});

describe("emitCli — combined", () => {
  test("everything-on emits all four extension blocks in the right order", () => {
    const content =
      emitCli(
        baseIr({
          tools: ["read", "bash"],
          mcp_servers: {
            things: { transport: "stdio", command: "node", args: ["server.js"] },
          },
          permissions: {
            mode: "default",
            rules: [{ type: "alwaysAllow", pattern: "Read" }],
          },
        }),
      ).files[0]?.content ?? "";
    // imports come before boot blocks; boot blocks before the runChatLoop call
    const importsIdx = content.indexOf('from "@crewhaus/runtime-core"');
    const mcpBootIdx = content.indexOf("new McpHost()");
    const extensionBootIdx = content.indexOf("Promise.all([\n  loadHooks");
    const runChatLoopIdx = content.indexOf("await runChatLoop({");
    expect(importsIdx).toBeGreaterThanOrEqual(0);
    expect(mcpBootIdx).toBeGreaterThan(importsIdx);
    expect(extensionBootIdx).toBeGreaterThan(importsIdx);
    expect(runChatLoopIdx).toBeGreaterThan(mcpBootIdx);
    expect(runChatLoopIdx).toBeGreaterThan(extensionBootIdx);
  });
});
