import { CrewhausError } from "@crewhaus/errors";
import { escapeJsonString } from "@crewhaus/infra-utils";
import type { Bundle, IrWorkflowV0 } from "@crewhaus/ir";

export type EmitOptions = {
  /**
   * Origins the generated Worker should accept on `/chat`. Defaults to the
   * production studio + local dev. Threading this through compile-time
   * lets the studio PWA bake its own origin in so users can host the PWA
   * anywhere (pages.dev, ngrok, LAN IP) without editing the emitter.
   */
  readonly allowedOrigins?: readonly string[];
};

const DEFAULT_ALLOWED_ORIGINS = ["https://studio.crewhaus.ai", "http://localhost:4322"];

/**
 * Emit a Cloudflare Worker bundle for a WORKFLOW-target IR. Workflow sibling
 * of `@crewhaus/target-cf-worker-cli`'s `emitCfWorkerCli`: same self-contained
 * Worker shape and `/chat` SSE protocol, but instead of a single agent it runs
 * the IR's steps sequentially server-side. Each step is one single-turn LLM
 * call; the prior step's terminal assistant text is threaded into the next
 * step's user message (mirrors `@crewhaus/target-workflow`'s local runtime).
 *
 * Like the cli emitter, the worker is fully self-contained — it inlines a
 * minimal Anthropic streaming-SSE client so the studio PWA can upload the
 * bundle directly via the Cloudflare API without a build step on the user's
 * device.
 *
 * Bundle contents:
 *   - `worker.js`        — entrypoint, runs as an ES module Worker
 *   - `wrangler.toml`    — deploy descriptor for users who do prefer CLI
 *   - `package.json`     — declares the runtime version stamp
 *
 * M2 emits a tools-free Worker (the cli sibling does the same). Tools,
 * sub-agents, MCP, hooks, and the security fabric port over when we point the
 * emitter at a shared worker runtime instead of inlining the client.
 */
export function emitCfWorkerWorkflow(ir: IrWorkflowV0, opts: EmitOptions = {}): Bundle {
  if (ir.target !== "workflow") {
    throw new TargetEmitError(
      `emitCfWorkerWorkflow requires target "workflow", got "${ir.target}"`,
    );
  }
  for (const step of ir.steps) {
    if (step.tools.length > 0) {
      throw new TargetEmitError(
        `cf-worker-workflow does not yet support tools (step "${step.name}"); use the local workflow target`,
      );
    }
  }
  const allowedOrigins =
    opts.allowedOrigins && opts.allowedOrigins.length > 0
      ? [...opts.allowedOrigins]
      : DEFAULT_ALLOWED_ORIGINS;
  return {
    files: [
      { path: "worker.js", content: renderWorker(ir, allowedOrigins) },
      { path: "wrangler.toml", content: renderWrangler(ir) },
      { path: "package.json", content: renderPackageJson(ir) },
    ],
  };
}

export class TargetEmitError extends CrewhausError {
  override readonly name = "TargetEmitError";
  constructor(message: string, cause?: unknown) {
    super("compiler", message, cause);
  }
}

function renderWorker(ir: IrWorkflowV0, allowedOrigins: readonly string[]): string {
  // escapeJsonString === JSON.stringify: each of these is a COMPLETE,
  // quoted JS/JSON string literal already. Do NOT wrap them in extra quotes
  // in the template below, or the output becomes `name: ""my-workflow""` — a
  // syntax error Cloudflare rejects at upload time.
  const name = escapeJsonString(ir.name);
  // Build the steps array literal by hand so each field is escaped exactly
  // once. Same fixed-bug discipline as the cli emitter: escapeJsonString
  // already returns a quoted literal, so the surrounding object literal just
  // interpolates it directly.
  const steps = ir.steps
    .map((step) => {
      const stepName = escapeJsonString(step.name);
      const stepModel = escapeJsonString(step.model);
      const stepInstructions = escapeJsonString(step.instructions);
      return `    { name: ${stepName}, model: ${stepModel}, instructions: ${stepInstructions} }`;
    })
    .join(",\n");
  const allowed = JSON.stringify(allowedOrigins);

  return `// Generated by @crewhaus/target-cf-worker-workflow. Do not edit by hand.
// Regenerate via the studio PWA or \`crewhaus compile --target cf-worker-workflow\`.

const CONFIG = {
  name: ${name},
  steps: [
${steps}
  ],
  allowedOrigins: ${allowed},
};

const ANTHROPIC_URL = "https://api.anthropic.com/v1/messages";
const ANTHROPIC_VERSION = "2023-06-01";

export default {
  async fetch(request, env) {
    const origin = request.headers.get("origin");
    const cors = buildCors(origin);
    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });

    const url = new URL(request.url);
    if (request.method === "GET" && url.pathname === "/health") {
      return json({ ok: true, harness: CONFIG.name }, 200, cors);
    }
    if (request.method === "POST" && url.pathname === "/chat") {
      return handleChat(request, env, cors);
    }
    return json({ error: { code: "NOT_FOUND" } }, 404, cors);
  },
};

async function handleChat(request, env, cors) {
  if (!env.ANTHROPIC_API_KEY) {
    return json({ error: { code: "NO_KEY", message: "ANTHROPIC_API_KEY not configured" } }, 500, cors);
  }
  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: { code: "BAD_JSON" } }, 400, cors);
  }
  const messages = normalizeMessages(body && body.messages);
  if (!messages) {
    return json({ error: { code: "BAD_REQUEST", message: "messages must be an array of {role,content}" } }, 400, cors);
  }

  // The workflow's initial input is the user's latest message text. Anthropic
  // rejects empty user content with a 400, so fall back to "begin" (matches
  // the local workflow target's stdin-empty placeholder).
  let initialInput = "";
  for (let i = messages.length - 1; i >= 0; i--) {
    if (messages[i].role === "user") { initialInput = messages[i].content; break; }
  }
  if (!initialInput) initialInput = "begin";

  // Run steps 1..N-1 as non-streaming calls server-side, threading each
  // step's terminal assistant text into the next. The FINAL step streams via
  // the inlined SSE translator so the chat panel renders tokens live.
  const stream = new ReadableStream({
    async start(controller) {
      const enc = new TextEncoder();
      const emit = (event, data) => {
        controller.enqueue(enc.encode(\`event: \${event}\\ndata: \${JSON.stringify(data)}\\n\\n\`));
      };
      const total = CONFIG.steps.length;
      try {
        let priorOutput = "";
        for (let i = 0; i < total; i++) {
          const step = CONFIG.steps[i];
          const stepNum = i + 1;
          // First step gets the incoming user text; later steps get a
          // synthetic message embedding the prior step's output (mirrors the
          // local workflow target's \`## Output of previous step:\` framing).
          const userContent =
            i === 0
              ? initialInput
              : \`## Output of previous step:\\n\${priorOutput}\\n\\n## Your task:\\n(continue based on the previous step's output)\`;

          // Progress marker so the user sees the workflow advancing. The chat
          // panel appends text deltas, so this renders inline.
          emit("text", { text: \`\\n[step \${stepNum}/\${total}: \${step.name}]\\n\` });

          if (i < total - 1) {
            priorOutput = await runStepNonStreaming(env, step, userContent);
          } else {
            const final = await runStepStreaming(env, step, userContent, emit);
            emit("done", { text: final.text, stopReason: final.stopReason });
          }
        }
        // Defensive: a zero-step workflow can't reach the streaming branch.
        // Emit a terminal done so the client doesn't hang.
        if (total === 0) emit("done", { text: "", stopReason: "end_turn" });
      } catch (err) {
        emit("error", { message: err && err.message ? err.message : String(err) });
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    status: 200,
    headers: {
      "Content-Type": "text/event-stream; charset=utf-8",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
      ...cors,
    },
  });
}

// One non-streaming Anthropic call. Reads the full JSON response and
// concatenates the text blocks into a single string.
async function runStepNonStreaming(env, step, userContent) {
  const upstream = await fetch(ANTHROPIC_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": env.ANTHROPIC_API_KEY,
      "anthropic-version": ANTHROPIC_VERSION,
    },
    body: JSON.stringify({
      model: step.model,
      max_tokens: 4096,
      system: step.instructions,
      stream: false,
      messages: [{ role: "user", content: userContent }],
    }),
  });
  if (!upstream.ok) {
    const text = await upstream.text().catch(() => "");
    throw new Error(\`upstream \${upstream.status}: \${text.slice(0, 500)}\`);
  }
  const payload = await upstream.json();
  let acc = "";
  if (payload && Array.isArray(payload.content)) {
    for (const block of payload.content) {
      if (block && block.type === "text" && typeof block.text === "string") acc += block.text;
    }
  }
  return acc;
}

// One streaming Anthropic call. Translates Anthropic's SSE stream into the
// studio's simpler {text} delta vocabulary (the caller emits the terminal
// \`done\`). Buffers across chunks because events can split mid-line. Returns
// the accumulated text + stop reason for the \`done\` event.
async function runStepStreaming(env, step, userContent, emit) {
  const upstream = await fetch(ANTHROPIC_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": env.ANTHROPIC_API_KEY,
      "anthropic-version": ANTHROPIC_VERSION,
    },
    body: JSON.stringify({
      model: step.model,
      max_tokens: 4096,
      system: step.instructions,
      stream: true,
      messages: [{ role: "user", content: userContent }],
    }),
  });

  if (!upstream.ok || !upstream.body) {
    const text = await upstream.text().catch(() => "");
    throw new Error(\`upstream \${upstream.status}: \${text.slice(0, 500)}\`);
  }

  const dec = new TextDecoder();
  const reader = upstream.body.getReader();
  let buffer = "";
  let acc = "";
  let stopReason = "end_turn";
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += dec.decode(value, { stream: true });
    let sep;
    while ((sep = buffer.indexOf("\\n\\n")) !== -1) {
      const raw = buffer.slice(0, sep);
      buffer = buffer.slice(sep + 2);
      let eventName = "message";
      let data = "";
      for (const line of raw.split("\\n")) {
        if (line.startsWith("event: ")) eventName = line.slice(7);
        else if (line.startsWith("data: ")) data += line.slice(6);
      }
      if (!data || data === "[DONE]") continue;
      let payload;
      try { payload = JSON.parse(data); } catch { continue; }
      if (eventName === "content_block_delta" && payload.delta && payload.delta.type === "text_delta") {
        acc += payload.delta.text;
        emit("text", { text: payload.delta.text });
      } else if (eventName === "message_delta" && payload.delta && payload.delta.stop_reason) {
        stopReason = payload.delta.stop_reason;
      }
    }
  }
  return { text: acc, stopReason };
}

function normalizeMessages(raw) {
  if (!Array.isArray(raw)) return null;
  const out = [];
  for (const item of raw) {
    if (!item || typeof item !== "object") return null;
    if (item.role !== "user" && item.role !== "assistant") return null;
    if (typeof item.content !== "string") return null;
    out.push({ role: item.role, content: item.content });
  }
  return out;
}

function buildCors(origin) {
  const allow = origin && CONFIG.allowedOrigins.includes(origin) ? origin : CONFIG.allowedOrigins[0];
  return {
    "Access-Control-Allow-Origin": allow,
    "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    Vary: "Origin",
  };
}

function json(body, status, cors) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8", ...cors },
  });
}
`;
}

function renderWrangler(ir: IrWorkflowV0): string {
  const safeName = ir.name.replace(/[^a-z0-9-]/gi, "-").toLowerCase();
  return `name = "${safeName}"
main = "worker.js"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]

# ANTHROPIC_API_KEY is set as a Worker Secret (never committed):
#   wrangler secret put ANTHROPIC_API_KEY
# The studio PWA sets this automatically via the Deploy flow.

[observability]
enabled = true
`;
}

function renderPackageJson(ir: IrWorkflowV0): string {
  // Sanitize like the wrangler name. A raw ir.name breaks out of the JSON
  // string (this manifest is reachable from the hosted compiler-worker HTTP
  // endpoint), allowing dependency/script injection into package.json (#148).
  const safeName = ir.name.replace(/[^a-z0-9-]/gi, "-").toLowerCase();
  return `{
  "name": "${safeName}",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "deploy": "wrangler deploy",
    "dev": "wrangler dev --local"
  }
}
`;
}
