/**
 * Catalog F2 `target-voice` — Section 24 VOICE.
 *
 * Codegen for the realtime voice target. Emits three files:
 *
 *   - `voice-loop.ts` — the per-call audio I/O loop. Wires the
 *     RealtimeAdapter, vad-engine + barge-in-controller, and an event
 *     emitter that forwards transcripts/audio/tool-uses to the daemon.
 *   - `agent.ts` — config wrapper exporting the spec's model +
 *     instructions + tool list + voice block.
 *   - `daemon.ts` — entrypoint. Either runs a one-shot smoke handler
 *     (when invoked with `--smoke <pcm-path>` it pumps a PCM file in
 *     and emits one JSON event per stdout line; useful for the smoke
 *     test) or boots a long-running WebSocket bridge (placeholder; v0
 *     ships the smoke path, full bridge lands in a follow-up).
 *
 * The emitted bundle is callable headless (no microphone needed) — the
 * daemon reads PCM from stdin or a file path, so the VOICE smoke
 * doesn't require a browser.
 */
import { CrewhausError } from "@crewhaus/errors";
import {
  renderControlDrain,
  renderControlImports,
  renderControlPlaneBoot,
  renderControlStart,
} from "@crewhaus/gateway-protocol/control-codegen";
import { escapeJsonString } from "@crewhaus/infra-utils";
import {
  type Bundle,
  type EmitReadmeOptions,
  type IrVoiceV0,
  renderBundleReadme,
} from "@crewhaus/ir";

export class TargetEmitError extends CrewhausError {
  override readonly name = "TargetEmitError";
  constructor(message: string, cause?: unknown) {
    super("compiler", message, cause);
  }
}

export function emitVoice(ir: IrVoiceV0, opts: EmitReadmeOptions = {}): Bundle {
  const files = [
    { path: "agent.ts", content: renderAgent(ir) },
    { path: "voice-loop.ts", content: renderVoiceLoop(ir) },
    { path: "daemon.ts", content: renderDaemon(ir) },
  ];
  // Item 42 — generated bundle README; default ON (`crewhaus compile
  // --no-readme` opts out).
  if (opts.readme !== false) {
    files.push({ path: "README.md", content: renderBundleReadme(ir) });
  }
  return { files };
}

function renderAgent(ir: IrVoiceV0): string {
  return `// Generated by crewhaus. DO NOT EDIT.
// Source spec: ${escapeJsonString(ir.name)} (target: voice, ir version: ${ir.version}, file: agent.ts)

export const AGENT_CONFIG = {
  name: ${escapeJsonString(ir.name)},
  model: ${escapeJsonString(ir.agent.model)},
  instructions: ${escapeJsonString(ir.agent.instructions)},
  voice: {
    provider: ${escapeJsonString(ir.voice.provider)},
    voiceId: ${escapeJsonString(ir.voice.voiceId)},
    vad: ${escapeJsonString(ir.voice.vad)},
    bargeInTriggerFrames: ${ir.voice.bargeInTriggerFrames},
    bargeInWindowMs: ${ir.voice.bargeInWindowMs},
  },
  telephony: ${
    ir.telephony !== undefined
      ? `{ provider: ${escapeJsonString(ir.telephony.provider)} }`
      : "undefined"
  },
} as const;
`;
}

function renderVoiceLoop(ir: IrVoiceV0): string {
  // Item 23 — surface the ignored failure_taxonomy as a generated comment
  // (mirror of target-workflow's mcp_servers note) so users notice rather
  // than wondering why their declared recovery never fires.
  const taxonomyWarning =
    ir.failureTaxonomy !== undefined && ir.failureTaxonomy.length > 0
      ? "// note: failure_taxonomy configured but target-voice does not yet wire it up — it is ignored\n"
      : "";
  // v0.3.0 — continuity is spec-carried on this shape but not emit-wired in
  // 0.3.0 (only the five agent-loop shapes are). Surface it, 0.2.3-style.
  const continuityWarning =
    ir.continuity !== undefined
      ? "// note: continuity configured but ignored on voice in 0.3.0\n"
      : "";
  // Loop contract 0.4 (G33, short-term) — the spec now accepts `tools:` on
  // voice, but the realtime tool bridge (registering them as session tools
  // on the realtime adapter) is a follow-up. Same ignored-note posture as
  // failure_taxonomy above; the compiler also raises an
  // `accepted-but-unwired` warning for this key.
  const toolsWarning =
    ir.tools.length > 0
      ? "// note: tools configured but target-voice does not yet bridge them into the realtime session — they are ignored\n"
      : "";
  return `// Generated by crewhaus. DO NOT EDIT.
// Source spec: ${escapeJsonString(ir.name)} (target: voice, ir version: ${ir.version}, file: voice-loop.ts)
${taxonomyWarning}${continuityWarning}${toolsWarning}import { createBargeInController } from "@crewhaus/barge-in-controller";
import { createRealtimeAdapter, type RealtimeEvent } from "@crewhaus/voice-runtime";
import { createVadDetector, frames30ms } from "@crewhaus/vad-engine";
import { AGENT_CONFIG } from "./agent.js";

export type VoiceEventListener = (event: RealtimeEvent | { kind: "barge_in"; speechFrames: number }) => void;

export type VoiceCallOptions = {
  /** PCM 16-bit signed mono buffer at 24kHz; the loop frames + streams it. */
  readonly inboundPcm: Int16Array;
  readonly listener: VoiceEventListener;
  /** Time budget for a single call. Defaults to 60s. */
  readonly maxDurationMs?: number;
};

const DEFAULT_MAX_DURATION_MS = 60_000;

export async function runOneCall(opts: VoiceCallOptions): Promise<void> {
  const adapter = createRealtimeAdapter(AGENT_CONFIG.voice.provider);
  // Attach the listener BEFORE connect() so the first session.created
  // event (and any error events during the upgrade) are captured.
  const off = adapter.on((ev) => opts.listener(ev));
  await adapter.connect({
    model: AGENT_CONFIG.model,
    instructions: AGENT_CONFIG.instructions,
    voice: AGENT_CONFIG.voice.voiceId,
    vad: AGENT_CONFIG.voice.vad,
  });

  const detector = createVadDetector({ aggressiveness: 1, sampleRate: 24_000 });
  const bargeIn = createBargeInController({
    adapter,
    detector,
    triggerFrames: AGENT_CONFIG.voice.bargeInTriggerFrames,
    windowMs: AGENT_CONFIG.voice.bargeInWindowMs,
    onBargeIn: ({ speechFrames }) => opts.listener({ kind: "barge_in", speechFrames }),
  });

  const fs = frames30ms(opts.inboundPcm, 24_000);
  for (const f of fs) {
    bargeIn.feedAudioFrame(f);
    adapter.sendAudio(f);
  }
  // Tell the server "this is end-of-utterance — process it now". With
  // server VAD this would happen automatically after silence, but the
  // smoke pumps a single bounded clip and needs a deterministic kick.
  adapter.commitInput();

  // Wait for transcript_final or budget expiry.
  const budget = opts.maxDurationMs ?? DEFAULT_MAX_DURATION_MS;
  let resolved = false;
  await new Promise<void>((resolve) => {
    const timer = setTimeout(() => {
      if (!resolved) resolve();
    }, budget);
    const inner = adapter.on((ev) => {
      if (ev.kind === "transcript_final" || ev.kind === "disconnect") {
        if (!resolved) {
          resolved = true;
          clearTimeout(timer);
          inner();
          resolve();
        }
      }
    });
  });

  bargeIn.stop();
  off();
  await adapter.disconnect();
}
`;
}

function renderDaemon(ir: IrVoiceV0): string {
  // crewhaus.control.v1, from the shared gateway-protocol renderers. The v0
  // voice daemon runs ONE headless call and exits, so it arms no pokeable lane
  // (`/control/v1/wake` answers 404 lane_not_armed) — what control.v1 adds
  // here is the uniform observe (`/status`) + graceful-finish (`/drain`)
  // surface every daemon shape shares, on its own loopback-bound port.
  const controlPlaneBoot = renderControlPlaneBoot({
    name: ir.name,
    target: "voice",
    indent: "  ",
    auditLogExpr: "__controlAudit",
  });
  const controlDrain = renderControlDrain({
    indent: "  ",
    body: `emit({ kind: "drain_requested", via: "control.v1" });
while (__callInFlight) await new Promise((__r) => setTimeout(__r, 100));`,
  });
  const controlStart = renderControlStart({ indent: "  " });
  return `#!/usr/bin/env bun
// Generated by crewhaus. DO NOT EDIT.
// Source spec: ${escapeJsonString(ir.name)} (target: voice, ir version: ${ir.version}, file: daemon.ts)
import { existsSync, readFileSync } from "node:fs";
import { openAuditLog } from "@crewhaus/audit-log";
${renderControlImports()}import { runOneCall } from "./voice-loop.js";

let __callInFlight = false;

function emit(event: Record<string, unknown>): void {
  process.stdout.write(\`\${JSON.stringify(event)}\\n\`);
}

function loadPcm(path: string): Int16Array {
  if (!existsSync(path)) {
    throw new Error("[voice-daemon] PCM file not found: " + path);
  }
  const buf = readFileSync(path);
  // raw PCM 16-bit little-endian mono. Align onto a fresh ArrayBuffer
  // because Buffer's underlying buffer can have an unaligned offset.
  const aligned = new ArrayBuffer(buf.byteLength);
  new Uint8Array(aligned).set(buf);
  return new Int16Array(aligned);
}

async function smokeMode(pcmPath: string): Promise<void> {
  emit({ kind: "smoke_start", pcmPath });
  const pcm = loadPcm(pcmPath);
  emit({ kind: "smoke_pcm_loaded", samples: pcm.length });
  __callInFlight = true;
  try {
    await runOneCall({
      inboundPcm: pcm,
      listener: (ev) => emit({ kind: "voice_event", event: ev }),
    });
  } finally {
    __callInFlight = false;
  }
  emit({ kind: "smoke_done" });
}

async function main(): Promise<void> {
  // control.v1 — the harness-wide hash-chained audit log every control call
  // appends a \`gateway_request\` record to. CREWHAUS_SECURITY_AUDIT=0 opts out.
  const __controlAudit =
    process.env["CREWHAUS_SECURITY_AUDIT"] === "0"
      ? undefined
      : await openAuditLog({ rootDir: \`\${process.cwd()}/.crewhaus/audit\` });
${controlPlaneBoot}${controlDrain}${controlStart}  const args = process.argv.slice(2);
  const smokeIdx = args.indexOf("--smoke");
  if (smokeIdx !== -1 && smokeIdx + 1 < args.length) {
    await smokeMode(args[smokeIdx + 1]!);
    __control.counters.turns++;
    await __control.stop();
    return;
  }
  await __control.stop();
  process.stderr.write(
    "[voice-daemon] no --smoke <pcm-path> provided. v0 ships the headless smoke path; the WebRTC + telephony bridge lands in a follow-up.\\n",
  );
  process.exit(2);
}

main().catch((err) => {
  process.stderr.write(\`[voice-daemon] fatal: \${(err as Error).message}\\n\`);
  process.exit(1);
});
`;
}
