import { CrewhausError } from "@crewhaus/errors";
import { escapeJsonString } from "@crewhaus/infra-utils";
import type { Bundle, IrGraphNode, IrGraphV0 } from "@crewhaus/ir";

/**
 * Emit a single-file `agent.ts` bundle that builds the graph via
 * `@crewhaus/graph-engine` and runs it against `process.stdin`.
 *
 * Each LLM-backed node calls `runChatLoop({ singleTurn: true, ... })`
 * with the node's instructions and a synthetic user message carrying
 * the JSON-stringified upstream state. The node's reply text is added
 * to the state under a key matching the node name (e.g. `state.plan`,
 * `state.execute`, `state.summarise`).
 *
 * HITL: nodes whose IR carries `hitlPrompt` await `ctx.requestApproval`
 * after the LLM turn. The graph-engine's pause/resume flow handles the
 * checkpoint persistence; the bundle emits CLI argument parsing for
 *
 *   bun agent.ts --resume <graphRunId> <decision>
 *   bun agent.ts --branch-from <graphRunId> <checkpointId>
 *
 * so operators can drive time-travel / resume from the shell without
 * any additional tooling.
 *
 * Layer F2. Pairs with `target-cli` (mirrors the codegen contract) and
 * `graph-engine` (R11 — runtime).
 */
export function emitGraph(ir: IrGraphV0): Bundle {
  return {
    files: [
      {
        path: "agent.ts",
        content: renderAgent(ir),
      },
    ],
  };
}

export class TargetEmitError extends CrewhausError {
  override readonly name = "TargetEmitError";
  constructor(message: string, cause?: unknown) {
    super("compiler", message, cause);
  }
}

function validateGraph(ir: IrGraphV0): void {
  const names = new Set(ir.nodes.map((n) => n.name));
  if (!names.has(ir.entry)) {
    throw new TargetEmitError(
      `entry node "${ir.entry}" is not declared in nodes (${[...names].join(", ")})`,
    );
  }
  for (const e of ir.edges) {
    if (!names.has(e.from)) {
      throw new TargetEmitError(`edge references unknown node "${e.from}" (from)`);
    }
    if (!names.has(e.to)) {
      throw new TargetEmitError(`edge references unknown node "${e.to}" (to)`);
    }
  }
}

/**
 * Render a single node's body. The body calls runChatLoop singleTurn
 * with the node's instructions and the upstream state serialised as a
 * user message. Returns the assistant reply text under
 * `state["<nodeName>"]`. When `hitlPrompt` is set, the node calls
 * `ctx.requestApproval` after the LLM turn so the engine can pause.
 */
function renderNodeBody(node: IrGraphNode): string {
  const instructionsJs = escapeJsonString(node.instructions);
  const modelJs = escapeJsonString(node.model);
  const nameJs = escapeJsonString(node.name);
  const hitlBlock =
    node.hitlPrompt !== undefined
      ? `
      const __decision = await ctx.requestApproval(${escapeJsonString(node.hitlPrompt)});
      __next.${node.name}_decision = __decision;`
      : "";
  return `
    async (ctx, prev) => {
      const __seed = [
        { role: "user", content: \`Upstream state:\\n\\\`\\\`\\\`json\\n\${JSON.stringify(prev, null, 2)}\\n\\\`\\\`\\\`\` },
      ];
      const __reply = await runChatLoop({
        model: ${modelJs},
        instructions: ${instructionsJs},
        sessionName: ${escapeJsonString(node.name)} + "-" + ctx.graphRunId,
        sessionTarget: "graph-node",
        seedMessages: __seed,
        singleTurn: true,
        runContext: ctx.runContext,
      });
      const __next = { ...prev, ${node.name}: __reply };${hitlBlock}
      return __next;
    }`;
}

function renderAgent(ir: IrGraphV0): string {
  validateGraph(ir);

  const nodeRegistrations = ir.nodes
    .map((n) => `  .addNode(${escapeJsonString(n.name)}, ${renderNodeBody(n).trim()})`)
    .join("\n");

  const edgeRegistrations = ir.edges
    .map((e) => `  .addEdge(${escapeJsonString(e.from)}, ${escapeJsonString(e.to)})`)
    .join("\n");

  const entryRegistration = `  .setEntry(${escapeJsonString(ir.entry)})`;

  return `#!/usr/bin/env bun
// Generated by crewhaus-factory. DO NOT EDIT.
// Source spec: ${ir.name} (target: graph, ir version: ${ir.version})
import { runChatLoop } from "@crewhaus/runtime-core";
import { createCheckpointStore } from "@crewhaus/checkpoint-store";
import { createGraph } from "@crewhaus/graph-engine";
import { createRunContext } from "@crewhaus/run-context";

const __store = createCheckpointStore();
const __runContext = createRunContext();
const __graph = createGraph({ checkpointStore: __store })
  .setInputAdapter((input) => ({ input }))
${nodeRegistrations}
${edgeRegistrations}
${entryRegistration}
  .compile();

async function readStdinToEnd(): Promise<string> {
  const chunks: Buffer[] = [];
  for await (const chunk of process.stdin) chunks.push(Buffer.from(chunk));
  return Buffer.concat(chunks).toString("utf8").trim();
}

function parseArgs(argv: ReadonlyArray<string>): {
  mode: "fresh" | "resume" | "branch";
  graphRunId?: string;
  checkpointId?: string;
  decision?: string;
} {
  const args = argv.slice(2);
  const idxResume = args.indexOf("--resume");
  if (idxResume >= 0) {
    const id = args[idxResume + 1];
    const decision = args[idxResume + 2] ?? "approve";
    if (id === undefined) throw new Error("--resume requires <graphRunId> <decision>");
    return { mode: "resume", graphRunId: id, decision };
  }
  const idxBranch = args.indexOf("--branch-from");
  if (idxBranch >= 0) {
    const grun = args[idxBranch + 1];
    const ckpt = args[idxBranch + 2];
    if (grun === undefined || ckpt === undefined) {
      throw new Error("--branch-from requires <graphRunId> <checkpointId>");
    }
    return { mode: "branch", graphRunId: grun, checkpointId: ckpt };
  }
  return { mode: "fresh" };
}

async function main(): Promise<void> {
  const cli = parseArgs(process.argv);

  if (cli.mode === "branch" && cli.graphRunId !== undefined && cli.checkpointId !== undefined) {
    const { newGraphRunId, head } = await __store.branch(cli.graphRunId, cli.checkpointId);
    process.stdout.write(\`branched: newRun=\${newGraphRunId} head=\${head.id} from=\${cli.graphRunId}/\${cli.checkpointId}\\n\`);
    // After branching, replay from the head's nodeName.
    const stream = __graph.run(head.state as { input?: string } | unknown, {
      graphRunId: newGraphRunId,
      runContext: __runContext,
      resumeFrom: { checkpointId: head.id, nextNode: head.nodeName },
    });
    let pausedAt: { checkpointId: string; nodeName: string; prompt: string } | undefined;
    for await (const ev of stream) {
      process.stderr.write(\`[graph] \${JSON.stringify(ev)}\\n\`);
      if (ev.kind === "hitl_pause") {
        pausedAt = { checkpointId: ev.checkpointId, nodeName: ev.nodeName, prompt: ev.prompt };
      }
      if (ev.kind === "run_done") {
        process.stdout.write(JSON.stringify(ev.state, null, 2) + "\\n");
      }
    }
    if (pausedAt !== undefined) {
      process.stdout.write(\`paused at \${pausedAt.nodeName}: "\${pausedAt.prompt}" — checkpoint=\${pausedAt.checkpointId}\\n\`);
    }
    return;
  }

  if (cli.mode === "resume" && cli.graphRunId !== undefined) {
    const meta = await __store.meta(cli.graphRunId);
    const head = meta?.head;
    if (head === undefined) {
      throw new Error(\`no head checkpoint for run \${cli.graphRunId}\`);
    }
    const stream = __graph.resume(cli.graphRunId, head, cli.decision ?? "approve", {
      runContext: __runContext,
    });
    for await (const ev of stream) {
      process.stderr.write(\`[graph] \${JSON.stringify(ev)}\\n\`);
      if (ev.kind === "run_done") {
        process.stdout.write(JSON.stringify(ev.state, null, 2) + "\\n");
      }
    }
    return;
  }

  // fresh run
  const stdin = await readStdinToEnd();
  const stream = __graph.run({ input: stdin }, { runContext: __runContext });
  let pausedAt: { checkpointId: string; nodeName: string; prompt: string } | undefined;
  let lastGraphRunId: string | undefined;
  for await (const ev of stream) {
    process.stderr.write(\`[graph] \${JSON.stringify(ev)}\\n\`);
    if (ev.kind === "node_start" || ev.kind === "node_end" || ev.kind === "checkpoint" || ev.kind === "hitl_pause" || ev.kind === "run_done") {
      lastGraphRunId = ev.graphRunId;
    }
    if (ev.kind === "hitl_pause") {
      pausedAt = { checkpointId: ev.checkpointId, nodeName: ev.nodeName, prompt: ev.prompt };
    }
    if (ev.kind === "run_done") {
      process.stdout.write(JSON.stringify(ev.state, null, 2) + "\\n");
    }
  }
  if (pausedAt !== undefined) {
    process.stdout.write(\`paused at \${pausedAt.nodeName}: "\${pausedAt.prompt}" — checkpoint=\${pausedAt.checkpointId} run=\${lastGraphRunId ?? "?"}\\n\`);
    process.stdout.write(\`to resume: bun \${process.argv[1]} --resume \${lastGraphRunId ?? "?"} <decision>\\n\`);
  }
}

await main();
`;
}
