import { type TargetShape, isTargetShape } from "@crewhaus/docker-images";
import { CrewhausError } from "@crewhaus/errors";

/**
 * Section 44 — `@crewhaus/cloud-adapter-flyio`
 *
 * One-click deploy adapter for [Fly.io](https://fly.io). Three surfaces:
 *
 *   - `flyTomlFor({target, appName, region, …})` — emits a deterministic
 *     `fly.toml` config: HTTP service block for web shapes, process
 *     groups for batch workers, VM sizing, env vars, healthchecks.
 *
 *   - `flyDockerfileFor({target, baseImage})` — wraps the §32 docker-images
 *     base with a Fly-tuned `EXPOSE` + healthcheck against the internal
 *     port (default 8080). Fly's load balancer probes via `[http_service.checks]`
 *     so a container HEALTHCHECK is optional, but we add one for shapes
 *     that already define `/healthz` to match the §44 contract.
 *
 *   - `deployToFly({apiToken, appName, …})` — creates the app + first
 *     machine via the Machines API (`https://api.machines.dev/v1`).
 *     Live calls gated on `FLY_API_TOKEN` env (or explicit `apiToken`)
 *     plus injectable `fetchImpl` test seam.
 *
 * SECURITY (T8 credential-leak guard): `scrubApiToken()` runs every
 * error path before surfacing to the caller — same approach as the
 * §37 `exporter-datadog` `scrubApiKey` helper, mirrored from
 * §44 `cloud-adapter-render`.
 *
 * Targets: daemon shapes only (channel, managed, batch, voice, browser).
 * One-shot shapes throw `FlyAdapterError`.
 */

export class FlyAdapterError extends CrewhausError {
  override readonly name = "FlyAdapterError";
  constructor(message: string, cause?: unknown) {
    super("config", message, cause);
  }
}

export const FLY_TARGET_SHAPES = [
  "channel",
  "managed",
  "batch",
  "voice",
  "browser",
] as const satisfies readonly TargetShape[];

export type FlyTargetShape = (typeof FLY_TARGET_SHAPES)[number];

export function isFlyTargetShape(value: unknown): value is FlyTargetShape {
  return typeof value === "string" && (FLY_TARGET_SHAPES as readonly string[]).includes(value);
}

/**
 * Subset of Fly's primary regions. Fly publishes the full list at
 * https://fly.io/docs/reference/regions/ — we accept any 3-letter code,
 * but the named list here makes typos cheaper for the common cases.
 */
export const FLY_REGIONS = [
  "iad",
  "ord",
  "lax",
  "sjc",
  "lhr",
  "fra",
  "ams",
  "sin",
  "syd",
  "nrt",
  "gru",
] as const;
export type FlyRegion = (typeof FLY_REGIONS)[number];

export type FlyVmPreset = "shared-1x" | "shared-2x" | "performance-1x" | "performance-2x";

const VM_SIZING: Readonly<
  Record<FlyVmPreset, { cpuKind: string; cpus: number; memoryMb: number }>
> = {
  "shared-1x": { cpuKind: "shared", cpus: 1, memoryMb: 256 },
  "shared-2x": { cpuKind: "shared", cpus: 2, memoryMb: 512 },
  "performance-1x": { cpuKind: "performance", cpus: 1, memoryMb: 2048 },
  "performance-2x": { cpuKind: "performance", cpus: 2, memoryMb: 4096 },
};

const SERVICE_TYPE_FOR_TARGET: Readonly<Record<FlyTargetShape, "web" | "worker">> = {
  channel: "web",
  managed: "web",
  voice: "web",
  browser: "web",
  batch: "worker",
};

const APP_NAME_PATTERN = /^[a-z0-9](?:[a-z0-9-]{0,28}[a-z0-9])?$/;

function assertFlyTarget(target: TargetShape): asserts target is FlyTargetShape {
  if (!isFlyTargetShape(target)) {
    throw new FlyAdapterError(
      `target shape "${target}" is not supported by Fly.io. Supported daemon shapes: ${FLY_TARGET_SHAPES.join(", ")}.`,
    );
  }
}

function assertAppName(name: string): void {
  if (!APP_NAME_PATTERN.test(name)) {
    throw new FlyAdapterError(
      `app name "${name}" is invalid. Must be lowercase alphanumerics + hyphens, 1-30 chars, no leading/trailing hyphen.`,
    );
  }
}

function tomlEscape(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export type FlyTomlOptions = {
  readonly target: TargetShape;
  readonly appName: string;
  readonly primaryRegion?: FlyRegion | string;
  readonly internalPort?: number;
  readonly vm?: FlyVmPreset;
  /** Plain-text env vars merged into `[env]`. Secret values must come from `fly secrets set`. */
  readonly envVars?: Readonly<Record<string, string>>;
  /** Path to the Dockerfile inside the build context. Defaults to `Dockerfile.fly`. */
  readonly dockerfilePath?: string;
};

const TOML_HEADER = "# Generated by @crewhaus/cloud-adapter-flyio — do not edit by hand";

export function flyTomlFor(opts: FlyTomlOptions): string {
  if (!isTargetShape(opts.target)) {
    throw new FlyAdapterError(`unknown target shape "${opts.target}"`);
  }
  assertFlyTarget(opts.target);
  assertAppName(opts.appName);

  const serviceType = SERVICE_TYPE_FOR_TARGET[opts.target];
  const region = opts.primaryRegion ?? "iad";
  const port = opts.internalPort ?? 8080;
  const vm = VM_SIZING[opts.vm ?? "shared-1x"];
  const dockerfilePath = opts.dockerfilePath ?? "Dockerfile.fly";

  const lines: string[] = [
    TOML_HEADER,
    `app = "${tomlEscape(opts.appName)}"`,
    `primary_region = "${tomlEscape(region)}"`,
    "",
    "[build]",
    `  dockerfile = "${tomlEscape(dockerfilePath)}"`,
  ];

  if (opts.envVars && Object.keys(opts.envVars).length > 0) {
    lines.push("", "[env]");
    for (const key of Object.keys(opts.envVars).sort()) {
      const value = opts.envVars[key];
      if (value === undefined) continue;
      lines.push(`  ${key} = "${tomlEscape(value)}"`);
    }
  }

  if (serviceType === "web") {
    lines.push(
      "",
      "[http_service]",
      `  internal_port = ${port}`,
      "  force_https = true",
      "  auto_stop_machines = true",
      "  auto_start_machines = true",
      "  min_machines_running = 0",
      "",
      "  [[http_service.checks]]",
      '    interval = "30s"',
      '    timeout = "5s"',
      '    grace_period = "10s"',
      '    method = "GET"',
      '    path = "/healthz"',
    );
  } else {
    lines.push("", "[processes]", `  worker = "node /app/dist/agent.js"`);
  }

  lines.push(
    "",
    "[[vm]]",
    `  cpu_kind = "${vm.cpuKind}"`,
    `  cpus = ${vm.cpus}`,
    `  memory_mb = ${vm.memoryMb}`,
  );

  return `${lines.join("\n")}\n`;
}

export type FlyDockerfileOptions = {
  readonly target: TargetShape;
  readonly baseImage: string;
  /** Internal port the container listens on (matches `flyTomlFor.internalPort`). */
  readonly internalPort?: number;
};

export function flyDockerfileFor(opts: FlyDockerfileOptions): string {
  if (!isTargetShape(opts.target)) {
    throw new FlyAdapterError(`unknown target shape "${opts.target}"`);
  }
  assertFlyTarget(opts.target);
  const isWeb = SERVICE_TYPE_FOR_TARGET[opts.target] === "web";
  const port = opts.internalPort ?? 8080;
  const lines = [
    `# Fly.io-tuned wrapper around ${opts.baseImage}`,
    `FROM ${opts.baseImage}`,
    `ENV PORT=${port}`,
  ];
  if (isWeb) {
    lines.push(`EXPOSE ${port}`);
  }
  return `${lines.join("\n")}\n`;
}

export type FlyDeployRecord = {
  readonly appName: string;
  readonly machineId: string;
  readonly status: string;
  readonly region: string;
};

export type DeployToFlyOptions = {
  readonly appName: string;
  readonly imageRef: string;
  readonly target: TargetShape;
  readonly region?: FlyRegion | string;
  readonly apiToken?: string;
  readonly apiBaseUrl?: string;
  /** Org slug the app belongs to. Defaults to "personal". */
  readonly orgSlug?: string;
  readonly fetchImpl?: typeof fetch;
};

export const FLY_DEFAULT_API_BASE = "https://api.machines.dev/v1";

function resolveApiToken(provided: string | undefined): string {
  const key = provided ?? process.env["FLY_API_TOKEN"];
  if (key === undefined || key.length === 0) {
    throw new FlyAdapterError(
      "FLY_API_TOKEN is required. Pass `apiToken` explicitly or set the env var.",
    );
  }
  return key;
}

export function scrubApiToken(message: string, apiToken: string | undefined): string {
  if (apiToken === undefined || apiToken.length < 8) return message;
  return message.split(apiToken).join("[REDACTED:FLY_API_TOKEN]");
}

/**
 * Two-step deploy: (1) create app (idempotent — Fly returns 409 if it
 * exists, which we treat as success), (2) launch first machine running
 * the image. Returns a `FlyDeployRecord`. All errors run through
 * `scrubApiToken()` before surfacing.
 */
export async function deployToFly(opts: DeployToFlyOptions): Promise<FlyDeployRecord> {
  if (!isTargetShape(opts.target)) {
    throw new FlyAdapterError(`unknown target shape "${opts.target}"`);
  }
  assertFlyTarget(opts.target);
  assertAppName(opts.appName);
  const apiToken = resolveApiToken(opts.apiToken);
  const baseUrl = opts.apiBaseUrl ?? FLY_DEFAULT_API_BASE;
  const region = opts.region ?? "iad";
  const fetchFn = opts.fetchImpl ?? fetch;
  const orgSlug = opts.orgSlug ?? "personal";

  const headers = {
    Authorization: `Bearer ${apiToken}`,
    "Content-Type": "application/json",
    Accept: "application/json",
  };

  // Step 1: create app (treat 409 conflict as already-exists, which is fine).
  let createResponse: Response;
  try {
    createResponse = await fetchFn(`${baseUrl}/apps`, {
      method: "POST",
      headers,
      body: JSON.stringify({ app_name: opts.appName, org_slug: orgSlug }),
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new FlyAdapterError(
      `Fly Machines API request failed: ${scrubApiToken(msg, apiToken)}`,
      err,
    );
  }
  if (!createResponse.ok && createResponse.status !== 409) {
    const body = scrubApiToken(await createResponse.text(), apiToken);
    throw new FlyAdapterError(
      `Fly app create returned ${createResponse.status} ${createResponse.statusText}: ${body}`,
    );
  }

  // Step 2: launch the first machine.
  let launchResponse: Response;
  try {
    launchResponse = await fetchFn(`${baseUrl}/apps/${opts.appName}/machines`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        region,
        config: {
          image: opts.imageRef,
          auto_destroy: false,
          restart: { policy: "always" },
        },
      }),
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new FlyAdapterError(
      `Fly Machines API request failed: ${scrubApiToken(msg, apiToken)}`,
      err,
    );
  }
  const launchText = await launchResponse.text();
  const scrubbed = scrubApiToken(launchText, apiToken);
  if (!launchResponse.ok) {
    throw new FlyAdapterError(
      `Fly machine launch returned ${launchResponse.status} ${launchResponse.statusText}: ${scrubbed}`,
    );
  }

  let parsed: { id?: string; state?: string };
  try {
    parsed = JSON.parse(launchText);
  } catch (err) {
    throw new FlyAdapterError(`Fly Machines API returned non-JSON body: ${scrubbed}`, err);
  }
  const machineId = parsed.id;
  if (typeof machineId !== "string") {
    throw new FlyAdapterError(`Fly Machines API response missing machine id: ${scrubbed}`);
  }
  return {
    appName: opts.appName,
    machineId,
    status: parsed.state ?? "created",
    region,
  };
}
