import { type TargetShape, isTargetShape } from "@crewhaus/docker-images";
import { CrewhausError } from "@crewhaus/errors";

/**
 * Section 44 — `@crewhaus/cloud-adapter-heroku`
 *
 * One-click deploy adapter for [Heroku](https://heroku.com). Four surfaces:
 *
 *   - `herokuYmlFor({target, …})` — emits a deterministic `heroku.yml`
 *     manifest pointing at the Container stack with a Docker build for
 *     each process type (web for daemon shapes, worker for batch).
 *
 *   - `appJsonFor({target, name, …})` — emits a `app.json` Heroku Setup
 *     manifest (`stack: container`, env vars, formation).
 *
 *   - `herokuDockerfileFor({target, baseImage})` — wraps the §32 base
 *     image with a Heroku-tuned `ENV PORT=$PORT` and shell-form CMD —
 *     Heroku injects `$PORT` at runtime and expects the container to
 *     bind to it. No fixed `EXPOSE`.
 *
 *   - `deployToHeroku({apiKey, appName, …})` — creates an app via the
 *     Heroku Platform API and sets the stack to `container`. Live
 *     calls gated on `HEROKU_API_KEY` (or explicit `apiKey`) + an
 *     injectable `fetchImpl`.
 *
 * SECURITY (T8 credential-leak guard): `scrubApiKey()` wraps every
 * error path. Mirrors the §37 exporter-datadog approach.
 *
 * Targets: daemon shapes (channel, managed, batch, voice, browser).
 */

export class HerokuAdapterError extends CrewhausError {
  override readonly name = "HerokuAdapterError";
  constructor(message: string, cause?: unknown) {
    super("config", message, cause);
  }
}

export const HEROKU_TARGET_SHAPES = [
  "channel",
  "managed",
  "batch",
  "voice",
  "browser",
] as const satisfies readonly TargetShape[];

export type HerokuTargetShape = (typeof HEROKU_TARGET_SHAPES)[number];

export function isHerokuTargetShape(value: unknown): value is HerokuTargetShape {
  return typeof value === "string" && (HEROKU_TARGET_SHAPES as readonly string[]).includes(value);
}

export type HerokuDynoSize = "basic" | "standard-1x" | "standard-2x" | "performance-m";

const PROCESS_FOR_TARGET: Readonly<Record<HerokuTargetShape, "web" | "worker">> = {
  channel: "web",
  managed: "web",
  voice: "web",
  browser: "web",
  batch: "worker",
};

const APP_NAME_PATTERN = /^[a-z][a-z0-9-]{2,28}[a-z0-9]$/;

// Free-form strings (`dockerfilePath`, `baseImage`) are interpolated verbatim
// into the generated heroku.yml / Dockerfile. A newline or other control
// character would let a caller inject arbitrary YAML sections or Dockerfile
// instructions (e.g. a top-level `release:` block, or a `RUN` directive that
// executes at build time). Legitimate filesystem paths and image references
// never contain control characters, so reject them outright.
// Matches C0 control characters (U+0000–U+001F) and DEL (U+007F).
// eslint-disable-next-line no-control-regex
// biome-ignore lint/suspicious/noControlCharactersInRegex: intentional control-character detection/sanitization
const CONTROL_CHAR_PATTERN = /[\u0000-\u001f\u007f]/;

function assertHerokuTarget(target: TargetShape): asserts target is HerokuTargetShape {
  if (!isHerokuTargetShape(target)) {
    throw new HerokuAdapterError(
      `target shape "${target}" is not supported by Heroku. Supported daemon shapes: ${HEROKU_TARGET_SHAPES.join(", ")}.`,
    );
  }
}

function assertAppName(name: string): void {
  if (!APP_NAME_PATTERN.test(name)) {
    throw new HerokuAdapterError(
      `app name "${name}" is invalid. Must be lowercase letters/digits/hyphens, 4-30 chars, starts with a letter, no trailing hyphen.`,
    );
  }
}

function assertNoInjection(label: string, value: string): void {
  if (value.length === 0) {
    throw new HerokuAdapterError(`${label} must not be empty.`);
  }
  if (CONTROL_CHAR_PATTERN.test(value)) {
    throw new HerokuAdapterError(`${label} must not contain newlines or control characters.`);
  }
}

export type HerokuYmlOptions = {
  readonly target: TargetShape;
  readonly dockerfilePath?: string;
};

/**
 * Heroku.yml is YAML but small + deterministic enough to template
 * inline. Three top-level sections: build, run, release (release omitted
 * for now — no DB migrations in the shipped scope).
 */
export function herokuYmlFor(opts: HerokuYmlOptions): string {
  if (!isTargetShape(opts.target)) {
    throw new HerokuAdapterError(`unknown target shape "${opts.target}"`);
  }
  assertHerokuTarget(opts.target);
  const dockerfilePath = opts.dockerfilePath ?? "Dockerfile.heroku";
  assertNoInjection("dockerfilePath", dockerfilePath);
  const processName = PROCESS_FOR_TARGET[opts.target];
  const lines = [
    "# Generated by @crewhaus/cloud-adapter-heroku — do not edit by hand",
    "build:",
    "  docker:",
    `    ${processName}: ${dockerfilePath}`,
    "run:",
    `  ${processName}: bun run start`,
  ];
  return `${lines.join("\n")}\n`;
}

export type AppJsonOptions = {
  readonly target: TargetShape;
  readonly name: string;
  readonly description?: string;
  readonly envVars?: Readonly<Record<string, { value?: string; required?: boolean }>>;
  readonly dynoSize?: HerokuDynoSize;
  readonly quantity?: number;
};

/**
 * `app.json` Heroku Setup manifest. Deterministic key order, sorted
 * env-var keys.
 */
export function appJsonFor(opts: AppJsonOptions): string {
  if (!isTargetShape(opts.target)) {
    throw new HerokuAdapterError(`unknown target shape "${opts.target}"`);
  }
  assertHerokuTarget(opts.target);
  assertAppName(opts.name);
  const processName = PROCESS_FOR_TARGET[opts.target];
  const formation = {
    [processName]: {
      quantity: opts.quantity ?? 1,
      size: opts.dynoSize ?? "basic",
    },
  };
  const env: Record<string, { value?: string; required?: boolean }> = {};
  if (opts.envVars) {
    for (const key of Object.keys(opts.envVars).sort()) {
      const value = opts.envVars[key];
      if (value === undefined) continue;
      env[key] = value;
    }
  }
  const manifest: Record<string, unknown> = {
    name: opts.name,
    stack: "container",
    formation,
  };
  if (opts.description !== undefined) {
    manifest["description"] = opts.description;
  }
  if (Object.keys(env).length > 0) {
    manifest["env"] = env;
  }
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

export type HerokuDockerfileOptions = {
  readonly target: TargetShape;
  readonly baseImage: string;
};

export function herokuDockerfileFor(opts: HerokuDockerfileOptions): string {
  if (!isTargetShape(opts.target)) {
    throw new HerokuAdapterError(`unknown target shape "${opts.target}"`);
  }
  assertHerokuTarget(opts.target);
  assertNoInjection("baseImage", opts.baseImage);
  // Heroku injects $PORT at runtime; container must bind to it. No EXPOSE.
  const lines = [
    `# Heroku-tuned wrapper around ${opts.baseImage}`,
    `FROM ${opts.baseImage}`,
    "ENV PORT=${PORT:-8080}",
  ];
  return `${lines.join("\n")}\n`;
}

export type HerokuDeployRecord = {
  readonly appId: string;
  readonly appName: string;
  readonly webUrl: string;
};

export type DeployToHerokuOptions = {
  readonly appName: string;
  readonly region?: "us" | "eu";
  readonly apiKey?: string;
  readonly apiBaseUrl?: string;
  readonly fetchImpl?: typeof fetch;
};

export const HEROKU_DEFAULT_API_BASE = "https://api.heroku.com";

function resolveApiKey(provided: string | undefined): string {
  const key = provided ?? process.env["HEROKU_API_KEY"];
  if (key === undefined || key.length === 0) {
    throw new HerokuAdapterError(
      "HEROKU_API_KEY is required. Pass `apiKey` explicitly or set the env var.",
    );
  }
  return key;
}

export function scrubApiKey(message: string, apiKey: string | undefined): string {
  if (apiKey === undefined || apiKey.length < 8) return message;
  return message.split(apiKey).join("[REDACTED:HEROKU_API_KEY]");
}

/**
 * Create an app via Heroku Platform API. Stack is pinned to `container`
 * so the heroku.yml + Dockerfile build path is used. All errors run
 * through `scrubApiKey()`.
 */
export async function deployToHeroku(opts: DeployToHerokuOptions): Promise<HerokuDeployRecord> {
  assertAppName(opts.appName);
  const apiKey = resolveApiKey(opts.apiKey);
  const baseUrl = opts.apiBaseUrl ?? HEROKU_DEFAULT_API_BASE;
  const fetchFn = opts.fetchImpl ?? fetch;
  const region = opts.region ?? "us";

  let response: Response;
  try {
    response = await fetchFn(`${baseUrl}/apps`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        Accept: "application/vnd.heroku+json; version=3",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ name: opts.appName, stack: "container", region }),
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new HerokuAdapterError(
      `Heroku Platform API request failed: ${scrubApiKey(msg, apiKey)}`,
      err,
    );
  }
  const text = await response.text();
  const scrubbed = scrubApiKey(text, apiKey);
  if (!response.ok) {
    throw new HerokuAdapterError(
      `Heroku Platform API returned ${response.status} ${response.statusText}: ${scrubbed}`,
    );
  }
  let parsed: { id?: string; name?: string; web_url?: string };
  try {
    parsed = JSON.parse(text);
  } catch (err) {
    throw new HerokuAdapterError(`Heroku Platform API returned non-JSON body: ${scrubbed}`, err);
  }
  if (typeof parsed.id !== "string" || typeof parsed.name !== "string") {
    throw new HerokuAdapterError(`Heroku Platform API response missing id/name: ${scrubbed}`);
  }
  return {
    appId: parsed.id,
    appName: parsed.name,
    webUrl: parsed.web_url ?? `https://${parsed.name}.herokuapp.com/`,
  };
}
