/**
 * `crontab -l` in, a line-accurate model out, and a rewrite that changes only
 * the bytes it was asked to change.
 *
 * A user crontab is a FILE, and this package's only job on it is to remove a
 * line. Everything else in it — `MAILTO=`, `PATH=`, the user's own comments,
 * their blank lines, the jobs this tool was not asked about — has to come out
 * the other side identical, because a "reformatted" crontab is a silent edit
 * to somebody's production schedule.
 *
 * Four traps this file exists to avoid, each of which has bitten somebody:
 *
 *   1. **The five-field grammar is not the only cron grammar.** `crontab -l`
 *      lists a USER crontab, where fields 1-5 are the schedule and everything
 *      after is the command. `/etc/crontab` and `/etc/cron.d/*` have a SIXTH
 *      field naming the user, and Quartz-style expressions put SECONDS first.
 *      Reading a six-field expression as five fields does not fail — it
 *      succeeds, with the wrong schedule and a one-token command. So this
 *      parser states `cron5` on every line it returns, and flags a line whose
 *      command is a single cron-shaped token instead of quietly accepting it.
 *   2. **The trailing newline is load-bearing, and so is every other one.**
 *      Several crond implementations ignore a final entry that is not
 *      newline-terminated (Debian 13 refuses the whole file), so a rewrite
 *      always ends in exactly one. The endings in the MIDDLE are the subtler
 *      half: they belong to the lines that carry them, one line at a time. A
 *      file with one stray CRLF in it is not a CRLF file, and re-terminating
 *      every line with `\r\n` because one line had it appends a carriage
 *      return to commands the caller never asked to touch — cron then runs
 *      `/usr/local/bin/backup.sh\r`, which is not a program. Each line is
 *      therefore written back with ITS OWN terminator.
 *   3. **`%` is not an ordinary character.** In a crontab command an
 *      unescaped `%` ends the command; what follows is fed to it on stdin,
 *      with each further `%` a newline. A tool that reports the whole line as
 *      the command is reporting something the host never runs.
 *   4. **Some crond implementations write their own banner.** Classic Vixie
 *      cron prepends a "DO NOT EDIT THIS FILE" block when a crontab is
 *      installed from a file, and prints it back out of `-l`. Installing that
 *      text verbatim stacks a second copy, and then a third. It is detected
 *      and dropped on write, and the drop is reported rather than done
 *      quietly.
 */
import { type JobEntry, type Schedule, fingerprint } from "./entries";

/** cron's own macros. `@reboot` is in the list but is an event, not a time. */
const MACROS: ReadonlySet<string> = new Set([
  "@yearly",
  "@annually",
  "@monthly",
  "@weekly",
  "@daily",
  "@midnight",
  "@hourly",
]);

/**
 * The bytes that ended this line in the file it was read from: `\n`, `\r\n`,
 * or `""` for a final line with no terminator at all. Kept per line, because
 * that is the only way a rewrite can leave the lines it did not touch alone;
 * see trap 2.
 */
export type LineEnding = "\n" | "\r\n" | "";

/**
 * The union WITHOUT the terminator: what the line parser produces. Kept
 * separate because `Omit` over a union collapses it, and the discriminated
 * shape is the whole value of this model.
 */
export type ParsedLine =
  | { readonly kind: "blank"; readonly line: number; readonly text: string }
  | { readonly kind: "comment"; readonly line: number; readonly text: string }
  | {
      readonly kind: "assignment";
      readonly line: number;
      readonly text: string;
      readonly name: string;
      readonly value: string;
    }
  | {
      readonly kind: "job";
      readonly line: number;
      readonly text: string;
      readonly expression: string;
      readonly grammar: "cron5" | "cron-macro" | "cron-reboot";
      readonly command: string;
      /** Text after the first unescaped `%`, which cron feeds in on stdin. */
      readonly stdin?: string;
      /** cronie's leading `-`: run, but do not log. */
      readonly logSuppressed?: boolean;
      readonly notes?: readonly string[];
    }
  | {
      readonly kind: "unparsed";
      readonly line: number;
      readonly text: string;
      readonly reason: string;
    };

/** Every variant of `ParsedLine`, each carrying its own terminator. */
export type CrontabLine = ParsedLine extends infer Variant
  ? Variant extends ParsedLine
    ? Variant & { readonly ending: LineEnding }
    : never
  : never;

export type ParsedCrontab = {
  readonly lines: readonly CrontabLine[];
  /**
   * The ending the file uses most — used ONLY for a line that had none (the
   * last line of a file with no trailing newline). Every other line keeps its
   * own; see trap 2.
   */
  readonly lineEnding: "\n" | "\r\n";
  /** True when the file mixes `\n` and `\r\n`, which is worth saying out loud. */
  readonly mixedLineEndings: boolean;
  /** How many leading lines are a crond-generated banner; see trap 4. */
  readonly bannerLines: number;
  /** True when the text had no final newline — see trap 2. */
  readonly missingTrailingNewline: boolean;
};

const ASSIGNMENT = /^([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/;
/** Only the characters a cron FIELD can be made of — see `suspectSixField`. */
const CRON_FIELD_SHAPED = /^[0-9*/,?\-LW#]+$/;

export function parseCrontab(text: string): ParsedCrontab {
  const missingTrailingNewline = text.length > 0 && !text.endsWith("\n");
  // Split so that each line keeps the terminator it actually had. A plain
  // `split(/\r?\n/)` loses that, and the join that puts the file back
  // together then has to pick ONE ending for every line — which is how a
  // single CRLF line ends up rewriting its neighbours (trap 2).
  const raw: { text: string; ending: LineEnding }[] = [];
  // The body is LAZY on purpose. Greedy, `[^\n]*` swallows the `\r` of a
  // CRLF pair and leaves the `\n` to terminate the line, so every CRLF line
  // comes back with a carriage return glued to its command and an ending of
  // `\n` — the exact corruption this is here to prevent, inverted.
  for (const match of text.matchAll(/([^\n]*?)(\r\n|\n|$)/g)) {
    const body = match[1] ?? "";
    const ending = match[2] as LineEnding;
    // The final `$` match is the empty string after the last terminator: it
    // is the end of the file, not a blank line.
    if (body === "" && ending === "") break;
    raw.push({ text: body, ending });
  }

  const lines: CrontabLine[] = raw.map((line, index) => ({
    ...parseLine(line.text, index + 1),
    ending: line.ending,
  }));
  const endings = new Set(lines.map((line) => line.ending).filter((end) => end !== ""));
  const lineEnding = endings.has("\r\n") && !endings.has("\n") ? "\r\n" : "\n";
  return {
    lines,
    lineEnding,
    mixedLineEndings: endings.size > 1,
    bannerLines: countBanner(lines),
    missingTrailingNewline,
  };
}

function parseLine(text: string, line: number): ParsedLine {
  const trimmed = text.trim();
  if (trimmed === "") return { kind: "blank", line, text };
  if (trimmed.startsWith("#")) return { kind: "comment", line, text };

  const assignment = ASSIGNMENT.exec(trimmed);
  if (assignment !== null) {
    return {
      kind: "assignment",
      line,
      text,
      name: assignment[1] as string,
      value: (assignment[2] as string).trim(),
    };
  }

  // cronie lets a job line start with `-` to mean "do not log this run". It
  // is not part of the schedule, and leaving it on the front would make the
  // first field unparseable to any cron parser.
  const logSuppressed = trimmed.startsWith("-");
  const body = logSuppressed ? trimmed.slice(1).trimStart() : trimmed;

  if (body.startsWith("@")) return parseMacroLine(body, text, line, logSuppressed);

  const fields = body.split(/\s+/);
  if (fields.length < 6) {
    return {
      kind: "unparsed",
      line,
      text,
      reason:
        fields.length < 5
          ? `only ${fields.length} whitespace-separated field${fields.length === 1 ? "" : "s"} — a user crontab job needs five schedule fields and a command`
          : "five schedule fields but no command after them",
    };
  }
  const expression = fields.slice(0, 5).join(" ");
  const rest = body.slice(body.indexOf(fields[5] as string, expression.length));
  const split = splitPercent(rest);
  const notes: string[] = [];
  if (suspectSixField(split.command)) {
    notes.push(
      `${JSON.stringify(split.command)} is the whole command on this line, and it is itself cron-shaped — if the line came from a six-field scheduler (seconds-first, or /etc/crontab's user field) then cron is reading that sixth field as the program to run`,
    );
  }
  return {
    kind: "job",
    line,
    text,
    expression,
    grammar: "cron5",
    command: split.command,
    ...(split.stdin !== undefined ? { stdin: split.stdin } : {}),
    ...(logSuppressed ? { logSuppressed: true } : {}),
    ...(notes.length > 0 ? { notes } : {}),
  };
}

function parseMacroLine(
  body: string,
  text: string,
  line: number,
  logSuppressed: boolean,
): ParsedLine {
  const space = body.search(/\s/);
  const macro = (space === -1 ? body : body.slice(0, space)).toLowerCase();
  const rest = space === -1 ? "" : body.slice(space).trim();
  if (macro !== "@reboot" && !MACROS.has(macro)) {
    return {
      kind: "unparsed",
      line,
      text,
      reason: `${macro} is not a cron macro this parser knows (@yearly @annually @monthly @weekly @daily @midnight @hourly @reboot)`,
    };
  }
  if (rest === "") {
    return { kind: "unparsed", line, text, reason: `${macro} with nothing to run after it` };
  }
  const split = splitPercent(rest);
  return {
    kind: "job",
    line,
    text,
    expression: macro,
    grammar: macro === "@reboot" ? "cron-reboot" : "cron-macro",
    command: split.command,
    ...(split.stdin !== undefined ? { stdin: split.stdin } : {}),
    ...(logSuppressed ? { logSuppressed: true } : {}),
  };
}

/**
 * Split a crontab command at its first UNESCAPED `%`. `\%` is a literal
 * percent and stays put; everything past a bare one is stdin.
 */
export function splitPercent(rest: string): { command: string; stdin?: string } {
  let out = "";
  for (let i = 0; i < rest.length; i++) {
    const ch = rest[i] as string;
    if (ch === "\\" && rest[i + 1] === "%") {
      out += "\\%";
      i++;
      continue;
    }
    if (ch === "%") {
      // cron turns each further `%` into a newline before feeding it in.
      return {
        command: out.trimEnd(),
        stdin: rest
          .slice(i + 1)
          .split("%")
          .join("\n"),
      };
    }
    out += ch;
  }
  return { command: out.trimEnd() };
}

function suspectSixField(command: string): boolean {
  if (command === "" || /\s/.test(command)) return false;
  return CRON_FIELD_SHAPED.test(command);
}

/** See trap 4. Only a leading, contiguous, crond-shaped block counts. */
function countBanner(lines: readonly CrontabLine[]): number {
  const first = lines[0];
  if (first === undefined || first.kind !== "comment") return 0;
  if (!/^#\s*DO NOT EDIT THIS FILE/i.test(first.text.trim())) return 0;
  let count = 1;
  for (let i = 1; i < lines.length && i < 3; i++) {
    const line = lines[i];
    // The other two banner lines are parenthesised: "(… installed on …)" and
    // "(Cron version -- $Id: …)". A user comment is not, so this stops before
    // eating one.
    if (line === undefined || line.kind !== "comment" || !/^#\s*\(/.test(line.text.trim())) break;
    count++;
  }
  return count;
}

/** The entries a caller sees, one per job line. */
export function crontabEntries(parsed: ParsedCrontab): JobEntry[] {
  const entries: JobEntry[] = [];
  for (const line of parsed.lines) {
    if (line.kind !== "job") continue;
    const schedule: Schedule = {
      grammar: line.grammar,
      expression: line.expression,
      ...(line.grammar === "cron-reboot"
        ? { note: "@reboot fires when cron starts, so it has no next firing time" }
        : {}),
    };
    const notes = [...(line.notes ?? [])];
    if (line.stdin !== undefined) {
      notes.push("text after an unescaped % is fed in on stdin, not run");
    }
    if (line.logSuppressed === true) {
      notes.push(
        "the leading - is cronie's 'do not log this run' marker, not part of the schedule",
      );
    }
    entries.push({
      source: "crontab",
      // A crontab line has no identity of its own. The line number is the
      // handle the host understands, and `fingerprint` is what makes using it
      // safe — see entries.ts.
      id: `line:${line.line}`,
      idKind: "crontab-line",
      fingerprint: fingerprint(line.text),
      line: line.line,
      schedule,
      command: line.command,
      scope: "user",
      ...(notes.length > 0 ? { notes } : {}),
    });
  }
  return entries;
}

export type RemovalPlan = {
  /** Exactly what to install, banner already dropped and newline ensured. */
  readonly nextText: string;
  readonly removed: readonly { readonly line: number; readonly text: string }[];
  /** Comment lines left directly above a removed job — kept, and reported. */
  readonly orphanComments: readonly { readonly line: number; readonly text: string }[];
  readonly bannerDropped: number;
};

/**
 * Build the text that would replace the current crontab.
 *
 * Pure: it takes the listing and the line numbers and returns bytes. Nothing
 * here runs anything, which is what lets the dry run and the real delete
 * share one code path — the dry run is this function plus a report, and the
 * delete is this function plus an install.
 */
export function planRemoval(parsed: ParsedCrontab, lineNumbers: readonly number[]): RemovalPlan {
  const doomed = new Set(lineNumbers);
  const removed: { line: number; text: string }[] = [];
  const kept: CrontabLine[] = [];
  for (const line of parsed.lines) {
    if (doomed.has(line.line)) removed.push({ line: line.line, text: line.text });
    else kept.push(line);
  }

  const orphanComments: { line: number; text: string }[] = [];
  for (const line of removed) {
    const above = parsed.lines[line.line - 2];
    if (above !== undefined && above.kind === "comment" && !doomed.has(above.line)) {
      // Not removed: a comment may describe several jobs, or be a note to a
      // human, and deleting somebody's prose because it sat above a line they
      // asked to remove is a second edit they did not ask for.
      orphanComments.push({ line: above.line, text: above.text });
    }
  }

  const bannerDropped = parsed.bannerLines;
  const body = kept.filter((line) => line.line > bannerDropped);
  // Trap 2, both halves. Each kept line is written back with the terminator it
  // arrived with, so a file that mixes endings comes back mixed exactly as it
  // was rather than converted wholesale. The LAST line is the one exception:
  // it must end in a newline or crond refuses the file ("new crontab file is
  // missing newline before EOF, can't install." — Debian 13, captured), so a
  // final line that had none is given the file's prevailing ending. An empty
  // crontab is empty text: a lone newline would install one blank line.
  const nextText = body
    .map((line, index) =>
      index === body.length - 1 && line.ending === ""
        ? `${line.text}${parsed.lineEnding}`
        : `${line.text}${line.ending}`,
    )
    .join("");
  return { nextText, removed, orphanComments, bannerDropped };
}
