/**
 * Recorded output from real schedulers, pasted as string literals.
 *
 * Every fixture below was captured by running the command, not written from
 * memory. That distinction earned its keep three times while this package was
 * being built:
 *
 *   - systemd 257 prints `NextElapseUSecRealtime=Sat 2026-09-19 07:44:13 UTC`,
 *     NOT the microsecond integer the property name implies. A hand-written
 *     fixture would have encoded the integer, the parser would have passed
 *     its tests, and every timer on a modern host would have reported no next
 *     run at all.
 *   - A timer with two `OnCalendar=` lines prints two SEPARATE
 *     `TimersCalendar={ … }` lines. Last-one-wins parsing silently loses half
 *     the schedule.
 *   - Debian's crontab REFUSES a file with no trailing newline
 *     ("new crontab file is missing newline before EOF, can't install.")
 *     rather than dropping the last entry quietly.
 *
 * WHERE EACH ONE CAME FROM
 *
 *   macOS   — Darwin 25.6.0 (macOS 15), the machine this package was written
 *             on: `crontab -l`, `launchctl list`, `plutil -convert json -o -`
 *             over `/System/Library/LaunchAgents`, `/Library/LaunchAgents`
 *             and `~/Library/LaunchAgents`.
 *   Linux   — Debian GNU/Linux 13 (trixie) in a container, cron 3.0pl1 and
 *             systemd 257 booted as PID 1.
 *   Windows — none. This package does not read Task Scheduler, so there is
 *             nothing to record; see the README.
 *
 * SANITISATION. Labels and paths that identified the machine or its owner
 * were replaced with `alice` / `com.example.*` equivalents of the same SHAPE
 * (same length class, same separators, same nesting). Vendor and Apple plists
 * are kept verbatim — they are identical on every Mac and carry nothing
 * personal. Anything edited says so in the comment above it.
 *
 * One fixture is NOT a capture and is marked RECONSTRUCTED: the pre-250
 * systemd timestamp form, which needs a host old enough that none was
 * available here. It is the documented older behaviour and exists so the
 * integer branch of the timestamp reader is exercised.
 */

// ---------------------------------------------------------------------------
// crontab
// ---------------------------------------------------------------------------

/** Debian 13, `crontab -l` after installing a file. Exit 0. */
export const LINUX_CRONTAB_L = `# my jobs
MAILTO=ops@example.com
*/15 * * * * /usr/local/bin/sync.sh
@daily /usr/local/bin/rotate.sh
`;

/** Debian 13, `crontab -l` for a user with none: this on stderr, exit 1. */
export const LINUX_CRONTAB_NONE_STDERR = "no crontab for root\n";

/** macOS 15 prefixes the same sentence with the program name. Exit 1. */
export const MACOS_CRONTAB_NONE_STDERR = "crontab: no crontab for alice\n";

/** Debian 13, installing a file whose last line has no newline. Exit 1. */
export const LINUX_CRONTAB_NO_NEWLINE_STDERR =
  "new crontab file is missing newline before EOF, can't install.\n";

/** Debian 13, installing a file with an unparseable line. Exit 1. */
export const LINUX_CRONTAB_BAD_LINE_STDERR = `"/tmp/ct3":1: bad command
errors in crontab file, can't install.
`;

/** macOS 15, `crontab <path>` where the path does not exist. Exit 1. */
export const MACOS_CRONTAB_MISSING_FILE_STDERR =
  "crontab: /private/tmp/definitely-missing-file-xyz: No such file or directory\n";

/**
 * A crontab with every shape this parser has to survive, assembled from lines
 * observed in real crontabs: assignments, a comment above a job, a macro, an
 * `@reboot` event, cronie's leading `-`, a `%` stdin split, an escaped `\%`,
 * and a line that is a SIX-field expression pasted into a five-field file —
 * the one that parses "successfully" into the wrong schedule.
 */
export const CRONTAB_EVERY_SHAPE = `SHELL=/bin/sh
PATH=/usr/local/bin:/usr/bin:/bin
MAILTO=ops@example.com

# nightly database dump
30 2 * * * /usr/local/bin/backup.sh --full
*/15 9-17 * * 1-5 /usr/local/bin/poll.sh
@daily /usr/local/bin/rotate.sh
@reboot /usr/local/bin/warm-cache.sh
-0 4 * * 0 /usr/local/bin/quiet-job.sh
0 6 * * * /usr/bin/mail-report%subject: nightly%body line one%body line two
15 3 * * * /usr/bin/printf 'done 100\\% ok'
0 0 12 * * ?
not a crontab line at all
`;

/**
 * Classic Vixie cron's banner. Some implementations write it when a crontab
 * is installed from a file and print it back from `-l`; Debian 13 does not.
 * Reinstalling text that still carries it stacks a second copy.
 */
export const CRONTAB_WITH_BANNER = `# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.7Xq1a2 installed on Thu Sep 18 09:12:00 2026)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
# my own comment
0 3 * * * /usr/local/bin/nightly.sh
`;

// ---------------------------------------------------------------------------
// launchd
// ---------------------------------------------------------------------------

/**
 * macOS 15, `launchctl list`, trimmed to the interesting rows: the header, an
 * agent with no pid, one running, one whose last "status" is a negative
 * SIGNAL number, and two of the user's own (relabelled). Tabs are real tabs.
 */
export const MACOS_LAUNCHCTL_LIST = `PID\tStatus\tLabel
-\t0\tcom.apple.SafariHistoryServiceAgent
874\t0\tapplication.com.example.desktop.28769829.28770129
-\t-9\tcom.apple.cloudphotod
675\t0\tcom.apple.Finder
-\t0\tcom.example.gc.scheduler
-\t78\tcom.example.relay
`;

/**
 * Verbatim from `~/Library/LaunchAgents/com.adobe.GC.Invoker-1.0.plist`,
 * relabelled. THE POINT OF THIS FIXTURE: the file is named `…Invoker-1.0`
 * and the Label inside it is `…Scheduler-1.0`. A path derived from a label
 * (or a label from a path) addresses the wrong job.
 */
export const MACOS_PLIST_CALENDAR_DICT = `{"ProgramArguments":["\\/Library\\/Application Support\\/Example\\/GCClient\\/gcinvokerutility","-mode=scheduled"],"Label":"com.example.gc.scheduler","StartCalendarInterval":{"Hour":8,"Minute":31},"Program":"\\/Library\\/Application Support\\/Example\\/GCClient\\/gcinvokerutility"}`;

/** Verbatim, Apple's own: StartCalendarInterval as an ARRAY of dicts. */
export const MACOS_PLIST_CALENDAR_ARRAY = `{"Label":"com.apple.talagent","EnvironmentVariables":{"NSRunningFromLaunchd":"1"},"ProcessType":"App","LimitLoadToSessionType":"Aqua","StartCalendarInterval":[{"Weekday":1,"Hour":3},{"Weekday":4,"Hour":3}],"EnablePressuredExit":true,"Program":"\\/System\\/Library\\/CoreServices\\/talagentd"}`;

/** Verbatim, Apple's own: an hour, a minute and a weekday together. */
export const MACOS_PLIST_CALENDAR_WEEKDAY = `{"Label":"com.apple.pluginkit.pkreporter","ProgramArguments":["\\/usr\\/libexec\\/pkreporter"],"StartCalendarInterval":{"Hour":6,"Minute":10,"Weekday":6}}`;

/** Verbatim from `/Library/LaunchAgents`, relabelled: StartInterval seconds. */
export const MACOS_PLIST_INTERVAL = `{"ProgramArguments":["\\/Applications\\/Example.app\\/Contents\\/Library\\/LaunchAgents\\/ExampleUpdater.app\\/Contents\\/MacOS\\/ExampleUpdater","--update"],"AssociatedBundleIdentifiers":["com.example.app"],"Label":"com.example.updater","KeepAlive":false,"RunAtLoad":false,"StartInterval":3600}`;

/**
 * Verbatim from a Homebrew-installed agent: no schedule at all, just
 * RunAtLoad and KeepAlive. A listing that called this "scheduled" would be
 * lying about when it runs.
 */
export const MACOS_PLIST_KEEPALIVE = `{"RunAtLoad":true,"WorkingDirectory":"\\/usr\\/local\\/var","EnvironmentVariables":{"EXAMPLE_FLAG":"1"},"StandardOutPath":"\\/usr\\/local\\/var\\/log\\/example.log","LimitLoadToSessionType":["Aqua","Background","LoginWindow","StandardIO","System"],"ProgramArguments":["\\/usr\\/local\\/opt\\/example\\/bin\\/example","serve"],"StandardErrorPath":"\\/usr\\/local\\/var\\/log\\/example.log","KeepAlive":true,"Label":"homebrew.mxcl.example"}`;

/** A user agent, with the home directory replaced. Hourly, and disabled. */
export const MACOS_PLIST_USER_DISABLED = `{"Label":"com.example.relay","Disabled":true,"StartCalendarInterval":{"Minute":0},"ProgramArguments":["\\/Users\\/alice\\/bin\\/relay","--serve"],"StandardOutPath":"\\/tmp\\/relay.log"}`;

/** macOS 15, `plutil` on a file that is not a plist. Exit 1, on stderr. */
export const MACOS_PLUTIL_ERROR_STDERR =
  "/Users/alice/Library/LaunchAgents/broken.plist: Property List error: Unexpected character n at line 1 / JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0.\n";

/** macOS 15, `launchctl bootout` for a label that is not loaded. Exit 3. */
export const MACOS_BOOTOUT_MISSING_STDERR = "Boot-out failed: 3: No such process\n";

// ---------------------------------------------------------------------------
// systemd
// ---------------------------------------------------------------------------

/** Debian 13 / systemd 257, `systemctl list-units --type=timer --all --no-legend --plain`. */
export const LINUX_LIST_UNITS_TIMERS = `apt-daily-upgrade.timer      loaded active   waiting Daily apt upgrade and clean activities
apt-daily.timer              loaded active   waiting Daily apt download activities
backup.timer                 loaded active   waiting Nightly backup timer
dpkg-db-backup.timer         loaded active   waiting Daily dpkg database backup timer
fstrim.timer                 loaded inactive dead    Discard unused filesystem blocks once a week
logrotate.timer              loaded active   waiting Daily rotation of log files
systemd-tmpfiles-clean.timer loaded active   waiting Daily Cleanup of Temporary Directories
`;

/**
 * systemd 257, `systemctl show` for a timer with TWO `OnCalendar=` lines.
 * Note the two separate `TimersCalendar=` lines, the pretty-printed
 * timestamp, and the EMPTY `LastTriggerUSec=` meaning "never".
 */
export const LINUX_SHOW_MULTI_ONCALENDAR = `Unit=backup.service
TimersCalendar={ OnCalendar=Mon *-*-* 09:00:00 ; next_elapse=Mon 2026-09-21 09:00:00 UTC }
TimersCalendar={ OnCalendar=*-*-* 02:30:00 ; next_elapse=Sat 2026-09-19 02:30:00 UTC }
NextElapseUSecRealtime=Sat 2026-09-19 02:30:00 UTC
NextElapseUSecMonotonic=0
LastTriggerUSec=
Id=backup.timer
Description=Nightly backup timer
ActiveState=active
FragmentPath=/etc/systemd/system/backup.timer
UnitFileState=enabled
`;

/** systemd 257, two blocks separated by one blank line. */
export const LINUX_SHOW_TWO_TIMERS = `Unit=apt-daily.service
TimersCalendar={ OnCalendar=*-*-* 06,18:00:00 ; next_elapse=Sat 2026-09-19 06:00:00 UTC }
NextElapseUSecRealtime=Sat 2026-09-19 07:44:13 UTC
NextElapseUSecMonotonic=0
LastTriggerUSec=
Id=apt-daily.timer
Description=Daily apt download activities
ActiveState=active
FragmentPath=/usr/lib/systemd/system/apt-daily.timer
UnitFileState=enabled

Unit=dpkg-db-backup.service
TimersCalendar={ OnCalendar=*-*-* 00:00:00 ; next_elapse=Sun 2026-09-20 00:00:00 UTC }
NextElapseUSecRealtime=Sun 2026-09-20 00:00:00 UTC
NextElapseUSecMonotonic=0
LastTriggerUSec=
Id=dpkg-db-backup.timer
Description=Daily dpkg database backup timer
ActiveState=active
FragmentPath=/usr/lib/systemd/system/dpkg-db-backup.timer
UnitFileState=enabled
`;

/**
 * systemd 257: a monotonic timer and an inactive one. `NextElapseUSecMonotonic`
 * is a DURATION string here ("6d 18h 50min 33.481175s") and `infinity` there —
 * neither is a number, and both would become a 1970 timestamp if parsed as one.
 */
export const LINUX_SHOW_MONOTONIC_AND_INACTIVE = `Unit=systemd-tmpfiles-clean.service
TimersMonotonic={ OnUnitActiveUSec=1d ; next_elapse=0 }
TimersMonotonic={ OnBootUSec=15min ; next_elapse=6d 18h 50min 33.481175s }
NextElapseUSecRealtime=
NextElapseUSecMonotonic=6d 18h 50min 33.481175s
LastTriggerUSec=
Id=systemd-tmpfiles-clean.timer
Description=Daily Cleanup of Temporary Directories
ActiveState=active
FragmentPath=/usr/lib/systemd/system/systemd-tmpfiles-clean.timer
UnitFileState=static

Unit=fstrim.service
TimersCalendar={ OnCalendar=Mon *-*-* 00:00:00 ; next_elapse=(null) }
NextElapseUSecRealtime=
NextElapseUSecMonotonic=infinity
LastTriggerUSec=
Id=fstrim.timer
Description=Discard unused filesystem blocks once a week
ActiveState=inactive
FragmentPath=/usr/lib/systemd/system/fstrim.timer
UnitFileState=enabled
`;

/**
 * RECONSTRUCTED, not captured: systemd before ~v250 printed these properties
 * as raw microseconds since the epoch. No host that old was available, so
 * this is the documented older form, kept so the integer branch of the
 * timestamp reader is covered.
 */
export const LINUX_SHOW_OLD_USEC_FORM = `Id=legacy.timer
Unit=legacy.service
TimersCalendar={ OnCalendar=*-*-* 04:00:00 ; next_elapse=Sat 2026-09-19 04:00:00 UTC }
NextElapseUSecRealtime=1789790400000000
NextElapseUSecMonotonic=0
LastTriggerUSec=1789704000000000
ActiveState=active
FragmentPath=/etc/systemd/system/legacy.timer
UnitFileState=enabled
`;

/** Debian 13, systemctl in a container that is not booted with systemd. Exit 1. */
export const LINUX_SYSTEMCTL_NOT_BOOTED_STDERR = `System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to system scope bus via local transport: Host is down
`;

/** Debian 13, `systemctl --user` with no session: exit 1. */
export const LINUX_SYSTEMCTL_NO_BUS_ENV_STDERR =
  "Failed to connect to user scope bus via local transport: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)\n";

/** Same command where XDG_RUNTIME_DIR exists but no user manager runs. Exit 1. */
export const LINUX_SYSTEMCTL_NO_BUS_FILE_STDERR =
  "Failed to connect to user scope bus via local transport: No such file or directory\n";

/** systemd 257, a successful `disable --now`, on stdout. Exit 0. */
export const LINUX_DISABLE_OK_STDOUT =
  "Removed '/etc/systemd/system/timers.target.wants/backup.timer'.\n";

/** systemd 257, disabling a unit that does not exist. Exit 1. */
export const LINUX_DISABLE_MISSING_STDERR =
  "Failed to disable unit: Unit nosuch.timer does not exist\n";
