/**
 * Regenerate `packages/docker-images/src/embedded.ts` from the checked-in
 * `docker/<target>/Dockerfile` files.
 *
 * Why generated literals rather than `with { type: "text" }` imports — the
 * mechanism the Helm chart and default-skills both use:
 *
 *   Bun's `--compile` does not embed EXTENSIONLESS files. `.tpl`, `.yaml` and
 *   `.md` assets inline correctly; a bare `Dockerfile` resolves to `undefined`
 *   in the standalone binary while working fine under the interpreter — which
 *   is the worst shape a bug can have, since every local check passes.
 *
 * So the bodies are baked into TypeScript source, which every path handles
 * identically. The checked-in Dockerfiles remain the single source of truth;
 * `index.test.ts` asserts each embedded body is byte-identical to its file, so
 * editing a Dockerfile without re-running this script fails CI rather than
 * silently shipping a stale image definition.
 *
 *   bun scripts/gen-dockerfile-bodies.ts
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DOCKER_ROOT = join(REPO_ROOT, "packages", "docker-images", "docker");
const OUT = join(REPO_ROOT, "packages", "docker-images", "src", "embedded.ts");

const targets = readdirSync(DOCKER_ROOT, { withFileTypes: true })
  .filter((e) => e.isDirectory() && existsSync(join(DOCKER_ROOT, e.name, "Dockerfile")))
  .map((e) => e.name)
  .sort();

if (targets.length === 0) throw new Error(`no Dockerfiles found under ${DOCKER_ROOT}`);

const entries = targets
  .map((t) => {
    const body = readFileSync(join(DOCKER_ROOT, t, "Dockerfile"), "utf8");
    return `  ${JSON.stringify(t)}: ${JSON.stringify(body)},`;
  })
  .join("\n");

writeFileSync(
  OUT,
  `// GENERATED by scripts/gen-dockerfile-bodies.ts — do not edit by hand.
// Re-run that script after changing any docker/<target>/Dockerfile;
// docker-images' tests assert these bodies match the files byte-for-byte.
/**
 * Build-time-baked bodies of the per-shape \`docker/<target>/Dockerfile\`
 * files.
 *
 * Reading them package-relative broke \`crewhaus build-image\` on every
 * PUBLISHED channel — \`dockerfile missing for target cli (expected at
 * /$bunfs/docker/cli/Dockerfile)\` from the compiled binary, and the same miss
 * against an npm tarball whose \`files\` array omitted \`docker/\`. Both are now
 * fixed: the bodies live here, and \`docker/\` ships in \`files\` so the real
 * files are still present for a build context.
 *
 * These are literals rather than \`with { type: "text" }\` imports because Bun's
 * \`--compile\` does not embed EXTENSIONLESS files: a bare \`Dockerfile\` inlines
 * fine under the interpreter and resolves to \`undefined\` in the standalone
 * binary. \`digests.json\` is deliberately absent — \`loadDigests\` already
 * returns an empty file when it is missing, and it is only read or written
 * from a source checkout during the release workflow.
 */
export const DOCKERFILE_BODIES: Readonly<Record<string, string>> = {
${entries}
};
`,
);

console.log(`wrote ${OUT} (${targets.length} Dockerfiles: ${targets.join(", ")})`);
