import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { REGISTRY_VERSION, TOOL_REGISTRY, projectRegistryEntry } from "./index";

/**
 * What this file can check, and what it cannot.
 *
 * This package is dependency-free by design, so it cannot import a tool and
 * therefore cannot prove that a description here matches the tool it claims to
 * describe. That check lives in `apps/cli/src/tool-registry.test.ts`, which
 * CAN import every builtin — the same division `@crewhaus/tool-categories`
 * already uses.
 *
 * What IS provable here is the manifest's own shape: that it is populated,
 * internally consistent, canonically projected, and free of the one kind of
 * row it must never contain.
 */

const entries = Object.entries(TOOL_REGISTRY);

describe("the manifest is populated", () => {
  /**
   * The count assertion, first and on its own.
   *
   * A truncated or half-written `generated.ts` still type-checks and still
   * satisfies every per-entry loop below, because a loop over nothing passes.
   * The exact cross-check against `BUILTIN_TOOL_MAP` is in apps/cli; this is
   * the floor that fails HERE, in the package that owns the data, when the
   * file has been emptied.
   */
  test("it holds a builtin-set-sized number of tools", () => {
    expect(entries.length).toBeGreaterThanOrEqual(500);
  });

  test("the generated file still says it is generated", () => {
    const text = readFileSync(join(import.meta.dir, "generated.ts"), "utf-8");
    expect(text.startsWith("// GENERATED by scripts/gen-tool-registry.ts")).toBe(true);
  });

  test("the version stamp is a release version", () => {
    expect(REGISTRY_VERSION).toMatch(/^\d+\.\d+\.\d+/);
  });
});

describe("every row is well formed", () => {
  test("the map key and the row's own key agree", () => {
    const mismatched = entries.filter(([key, entry]) => key !== entry.key);
    expect(mismatched.map(([key, entry]) => `${key} !== ${entry.key}`)).toEqual([]);
  });

  test("each row carries the fields a person needs to recognise the tool", () => {
    const thin: string[] = [];
    for (const [key, entry] of entries) {
      if (entry.name.length === 0) thin.push(`${key}: no name`);
      if (entry.description.length === 0) thin.push(`${key}: no description`);
      if (!entry.package.startsWith("@crewhaus/tool-")) thin.push(`${key}: ${entry.package}`);
      if (entry.categories.length === 0) thin.push(`${key}: no category`);
    }
    expect(thin).toEqual([]);
  });

  test("keys are spec casing and names are session-log casing", () => {
    const wrong = entries.filter(
      ([key, entry]) =>
        key[0] !== key[0]?.toLowerCase() || entry.name[0] !== entry.name[0]?.toUpperCase(),
    );
    expect(wrong.map(([key, entry]) => `${key}/${entry.name}`)).toEqual([]);
  });
});

/**
 * The asymmetry, asserted rather than described.
 *
 * `registerMcpServer` registers whatever a server offers at connect time, and
 * a spec declares the server rather than its tool list, so this manifest can
 * never describe an MCP tool. A single `mcp__` row would turn "this is the
 * builtin set" into "this is the set", and a reader would then present an
 * MCP-free answer as complete.
 */
describe("the manifest is builtins only", () => {
  test("no row is an MCP tool, and the scan actually looked", () => {
    const scanned = entries.length;
    expect(scanned).toBeGreaterThanOrEqual(500);
    const mcp = entries.filter(
      ([key, entry]) => key.startsWith("mcp__") || entry.name.startsWith("mcp__"),
    );
    expect(mcp.map(([key]) => key)).toEqual([]);
  });
});

/**
 * The projection is canonical.
 *
 * `apps/cli/src/tool-registry.test.ts` compares a fresh projection against
 * these rows byte for byte, which only means anything if the field ORDER is
 * fixed. Re-projecting a row from itself proves it is: a reordered field list
 * in `projectRegistryEntry` shows up here rather than as a confusing
 * whole-manifest mismatch in another package.
 */
describe("projectRegistryEntry round-trips every row", () => {
  test("re-projecting a row reproduces its exact bytes", () => {
    const drifted: string[] = [];
    for (const [key, entry] of entries) {
      const again = projectRegistryEntry({
        key: entry.key,
        tool: entry,
        categories: entry.categories,
        package: entry.package,
        keywords: entry.keywords,
      });
      if (JSON.stringify(again) !== JSON.stringify(entry)) drifted.push(key);
    }
    expect(drifted).toEqual([]);
  });

  test("an absent ioCapability stays absent rather than becoming undefined", () => {
    const projected = projectRegistryEntry({
      key: "x",
      tool: {
        name: "X",
        description: "d",
        readOnly: true,
        destructive: false,
        scope: "internal",
        requiresSandbox: false,
        requireJustification: false,
      },
      categories: ["c"],
      package: "@crewhaus/tool-x",
      keywords: [],
    });
    expect("ioCapability" in projected).toBe(false);
  });
});
