import { CrewhausError } from "@crewhaus/errors";
import { escapeJsonString } from "@crewhaus/infra-utils";
import type { Bundle, IrManagedV0 } from "@crewhaus/ir";

/**
 * Emit a managed-daemon bundle. Generates `daemon.ts` that wires:
 *   - `@crewhaus/gateway-server` listening on `process.env.PORT`
 *     (default 3000) with the JWT secret from
 *     `process.env.CREWHAUS_GATEWAY_JWT_SECRET`,
 *   - per-tenant routing via `@crewhaus/tenancy`,
 *   - per-tenant audit log via `@crewhaus/audit-log`,
 *   - the runChatLoop dispatcher inside `runs.create` / `runs.continue`,
 *   - a pluggable `@crewhaus/durable-state` BudgetStore
 *     (`CREWHAUS_BUDGET_STORE=sqlite:<path>` for restart-safe accounting)
 *     shared with the boot-time self-heal janitor (ops item 36), which
 *     clears crash-leaked reservations at boot, evicts expired sessions,
 *     and reports orphaned tool_use entries — boot run + hourly re-run
 *     (`CREWHAUS_JANITOR=0` / `CREWHAUS_JANITOR_INTERVAL_MS` to tune).
 *
 * The agent.ts emitted alongside is shape-compatible with the cli
 * target so existing tools, hooks, skills, and slash commands surface
 * inside the managed daemon without rewrite.
 *
 * Layer F2. Pairs with `gateway-server`, `tenancy`, `audit-log`,
 * `policy-engine`.
 */
export function emitManaged(ir: IrManagedV0): Bundle {
  return {
    files: [
      { path: "agent.ts", content: renderAgent(ir) },
      { path: "daemon.ts", content: renderDaemon(ir) },
    ],
  };
}

export class TargetEmitError extends CrewhausError {
  override readonly name = "TargetEmitError";
  constructor(message: string, cause?: unknown) {
    super("compiler", message, cause);
  }
}

function renderAgent(ir: IrManagedV0): string {
  return `#!/usr/bin/env bun
// Generated by crewhaus. DO NOT EDIT.
// Source spec: ${escapeJsonString(ir.name)} (target: managed, ir version: ${ir.version})
import { runChatLoop } from "@crewhaus/runtime-core";
import type { RunChatLoopOptions } from "@crewhaus/runtime-core";

export type ManagedAgentArgs = {
  readonly tenantId: string;
  readonly sessionId: string;
  readonly input: string;
  readonly extraOptions?: Partial<RunChatLoopOptions>;
};

export async function runOneTurn(args: ManagedAgentArgs): Promise<string> {
  return await runChatLoop({
    model: ${escapeJsonString(ir.agent.model)},
    instructions: ${escapeJsonString(ir.agent.instructions)},
    sessionName: args.sessionId,
    sessionTarget: "managed",
    seedMessages: [{ role: "user", content: args.input }],
    singleTurn: true,
    ...(args.extraOptions ?? {}),
  });
}
`;
}

function renderDaemon(ir: IrManagedV0): string {
  const tenantList = ir.tenants
    .map(
      (t) =>
        `  ${escapeJsonString(t.id)}: { id: ${escapeJsonString(
          t.id,
        )}, budget: { maxInputTokens: ${t.budget.maxInputTokens}, maxOutputTokens: ${t.budget.maxOutputTokens} } }`,
    )
    .join(",\n");
  return `#!/usr/bin/env bun
// Generated by crewhaus. DO NOT EDIT.
// Source spec: ${escapeJsonString(ir.name)} (target: managed, ir version: ${ir.version})
import { createBudgetStore } from "@crewhaus/durable-state";
import { createGatewayServer } from "@crewhaus/gateway-server";
import { auditPolicyDecision, evaluatePolicy } from "@crewhaus/policy-engine";
import { createJanitor } from "@crewhaus/runtime-core";
import { buildTenant, type Tenant } from "@crewhaus/tenancy";
import { runOneTurn } from "./agent.ts";

import { randomBytes } from "node:crypto";
const TENANTS_ROOT = process.env.CREWHAUS_TENANTS_ROOT ?? "/tmp/crewhaus-tenants";
const PORT = Number(process.env.PORT ?? 3000);
const ENV_JWT_SECRET = process.env.CREWHAUS_GATEWAY_JWT_SECRET;
if (ENV_JWT_SECRET !== undefined && ENV_JWT_SECRET.length < 16) {
  console.error(
    "[managed] CREWHAUS_GATEWAY_JWT_SECRET is set but too short (min 16 chars). Refusing to start.",
  );
  process.exit(1);
}
const JWT_SECRET: string = ENV_JWT_SECRET ?? randomBytes(24).toString("hex");
if (ENV_JWT_SECRET === undefined) {
  // Dev-mode autogeneration. The doc-side contract is that the operator
  // copies this line and re-exports it for subsequent runs (otherwise
  // every restart invalidates previously-minted tokens). In production,
  // set CREWHAUS_GATEWAY_JWT_SECRET explicitly.
  console.error(
    \`[managed] no CREWHAUS_GATEWAY_JWT_SECRET in env — generated a one-shot dev secret. Export it to re-use:\\n  export CREWHAUS_GATEWAY_JWT_SECRET=\${JWT_SECRET}\`,
  );
}

const TENANT_OVERRIDES: Record<string, Partial<Tenant>> = {
${tenantList}
};

const tenantOverrides: Record<string, Tenant> = {};
for (const [id, override] of Object.entries(TENANT_OVERRIDES)) {
  tenantOverrides[id] = { ...buildTenant(id, { tenantsRoot: TENANTS_ROOT }), ...override };
}

// Budget accounting backend (audit R3). Default in-memory; set
// CREWHAUS_BUDGET_STORE=sqlite:<path> so recorded usage and in-flight
// reservations survive restarts and are shared by every process on this host.
const BUDGET_STORE = createBudgetStore(process.env.CREWHAUS_BUDGET_STORE ?? "memory");

// Boot-time self-heal janitor (ops item 36): clears crash-leaked budget
// reservations (durable-state's documented boot contract — a process that
// died between tryReserve and release leaks its reservation in the sqlite
// backend), evicts expired sessions in every tenant's session root, and
// reports orphaned tool_use entries in recent transcripts (report-only).
// CREWHAUS_JANITOR=0 disables entirely; CREWHAUS_JANITOR_INTERVAL_MS
// overrides the hourly re-run (0 keeps only the boot run).
const janitor = createJanitor({
  budgetStore: BUDGET_STORE,
  sessionRootDirs: Object.values(tenantOverrides).map((t) => t.sessionRoot),
});
if (process.env.CREWHAUS_JANITOR !== "0") {
  const janitorReport = await janitor.runOnce();
  console.error(\`[managed] janitor: \${JSON.stringify(janitorReport.steps)}\`);
  janitor.start(Number(process.env.CREWHAUS_JANITOR_INTERVAL_MS ?? 3_600_000));
}

const gateway = createGatewayServer({
  jwtSecret: JWT_SECRET,
  tenantsRoot: TENANTS_ROOT,
  tenantOverrides,
  budgetStore: BUDGET_STORE,
  handler: async ({ method, params, tenant }) => {
    if (method === "runs.create" || method === "runs.continue") {
      const p = params as { input: string; sessionId?: string };
      const sessionId = p.sessionId ?? \`sess_\${Math.random().toString(36).slice(2, 18).padEnd(16, "0")}\`;
      const log = await gateway.getAuditLog(tenant);
      const policy = evaluatePolicy(
        { toolName: "runChatLoop", sideEffect: "external", input: p.input, tenantId: tenant.id },
      );
      await auditPolicyDecision(log, { toolName: "runChatLoop", input: p.input, tenantId: tenant.id }, policy);
      if (policy.decision === "deny") {
        throw new Error(\`policy denied: \${policy.reason ?? "no reason"}\`);
      }
      const reply = await runOneTurn({ tenantId: tenant.id, sessionId, input: p.input });
      const inputTokens = Math.ceil(p.input.length / 4);
      const outputTokens = Math.ceil(reply.length / 4);
      await gateway.recordUsage(tenant.id, { input: inputTokens, output: outputTokens });
      await log.append({
        kind: "model_call",
        payload: { tenantId: tenant.id, sessionId, inputTokens, outputTokens },
      });
      return { runId: \`run_\${Math.random().toString(36).slice(2, 10)}\`, sessionId, tenantId: tenant.id, reply };
    }
    if (method === "runs.cancel") {
      return { ok: true };
    }
    if (method === "audit.tail") {
      const log = await gateway.getAuditLog(tenant);
      const rows: unknown[] = [];
      for await (const r of log.read()) rows.push(r);
      return { rows };
    }
    return { ok: true, method };
  },
});

const handle = await gateway.listen(PORT);
console.error(\`[managed] gateway listening on :\${handle.port}\`);

process.on("SIGTERM", async () => {
  console.error("[managed] SIGTERM — closing gateway");
  janitor.stop();
  await handle.close();
  process.exit(0);
});
process.on("SIGINT", async () => {
  console.error("[managed] SIGINT — closing gateway");
  janitor.stop();
  await handle.close();
  process.exit(0);
});
`;
}
